### ISSUE TITLE
Is it possible to have a tree view on the groups props?

### ISSUE THREAD

**Issue by jrojospingine** [namespace-ee/react-calendar-timeline#102]
Would it be possible to render a group tree just like in this demo => 
[https://cdn.rawgit.com/chenglou/react-treeview/aa72ed8b9e0b31fabc09e2f8bd4084947d48bb09/demos/index.html]()
from 
[https://github.com/chenglou/react-treeview]()

It would be great to have something like this =>

`const groups = [
    {id: 1, title: 'group 1'},
    {id: 2, title: 'group 2', children: [
            {id: 3, title: 'group 3'}
        ]},
];`

:+1:

**Comment by signalwerk** [comment]
This is right now not supported. But I would also be interested in something like that. Do you plan to implement it?

**Comment by mariusandra** [comment]
Hey! While we don't have this kind of groups supported out of the box, it's definitely possible to simulate this yourself. See the [treeGroups demo](http://namespace.ee/react-calendar-timeline-docs/#/treeGroups) for a simple example. :)

The trick is to just hide/show groups depending on what is open or closed in the tree... and to show the buttons to open/close in the sidebar.

Could this work for you?

**Comment by jrojospingine** [comment]
@mariusandra Awesome! Yep, that's definitely going to work. @signalwerk Sorry for the late response. I got so busy with day job and stuff but yeah, I'd love to do some work to contribute to this project but marius already implemented it :) :+1: :100:

**Comment by mariusandra** [comment]
Cool :). Closing this. Reopen if you have any other related questions!
