### ISSUE TITLE
Can I disable horizontal scroll onclick ? Instead I only want to scroll it from horizontal y-axis bar

### ISSUE THREAD

**Issue by mfahad1** [namespace-ee/react-calendar-timeline#104]
![image](https://cloud.githubusercontent.com/assets/14197859/26675250/a6ff3608-46dc-11e7-80f8-7719737bf8b4.png)

I just want to disable scroll when clicking on cells of grid

**Comment by signalwerk** [comment]
This is looking kind of weird and should not happen. Could you please provide an Example? Here a [webpackbin](https://www.webpackbin.com/bins/-KnBvRcj2FzvwL8QbT01) you can play with.

**Comment by mariusandra** [comment]
@mfahad1  it's possible that there's something overriding the default CSS styles that should prevent this scrollbar from being visible. Are you still experiencing the issue or did you manage to solve it?

**Comment by mariusandra** [comment]
I'm closing this issue as there hasn't been any update for ~40 days. @mfahad1, feel free to reopen if you still have problems!
