### ISSUE TITLE
Performance issues scrolling linked timelines with 0.14 release

### ISSUE THREAD

**Issue by nicocrm** [namespace-ee/react-calendar-timeline#109]
The redrawing performance seems to have dropped a lot with the last release.  I thought it was the extra resize() call in componentWillReceiveProps, but even removing that it is very slow to scroll.  I have 2 timelines on the screen that are linked by visibleTimeStart / visibleTimeEnd and that is most likely triggering the problem because if I remove either one of them the scroll is back to smooth.  I am going to dig into it further when I can but wanted to give a heads up in case you have an idea of what could be causing this.

[Scrolling with 0.14](https://www.dropbox.com/s/hmxhcoh4io3z4wz/scroll-0.14.mp4?dl=0)
[Scrolling with 0.13](https://www.dropbox.com/s/tmhd76kqtnjnz7a/scroll-0.13.mp4?dl=0)

**Comment by mariusandra** [comment]
Hey!

I started to investigate this and ran into a different issue with that extra `resize()` call. I couldn't get the timeline to act as controlled at all. It behaved like this: https://youtu.be/8lZWT9eplGY

Commenting out the call to resize (https://github.com/namespace-ee/react-calendar-timeline/commit/a93417ddcef9fb3ad4ec20e28a0d2c10f96c7df1) that was introduced in #75 made it again possible to control the component: https://youtu.be/BYgpm__SDEo

In the end I made it call resize only if the sidebar width changed. I think that was the original intention behind #75 .

I released `0.14.4` with the updates. Can you check if this fixes your problems? And if not (you did say that removing the `resize()` did nothing), can you reproduce this behaviour in the new [demo](http://namespace.ee/react-calendar-timeline-docs/) called `linkedTimelines`? At least on the demo page the timeline seems to work pretty fast for me.

**Comment by nicocrm** [comment]
I think that did it, thank you so much!
