### ISSUE TITLE
Is it possible to change color of item according to its content? 

### ISSUE THREAD

**Issue by 0riesok** [namespace-ee/react-calendar-timeline#11]
I have two type of items: standard item and analysis item. I would like to distinguish them with different color? Is there any way how to do that? If yes, can you please give me a help?

**Comment by xmityaz** [comment]
Items have a "className" parameter. You can just add an "analysis" class for your analysis items and then change the css backgroundColor property for them.

You would usually need to override the default rule:
```
.react-calendar-timeline .rct-items .rct-item.analysis {
  backgroundColor: #68efad;
}
```

**Comment by 0riesok** [comment]
@xmityaz Thank you!!!

**Comment by mariusandra** [comment]
Thank you @xmityaz for helping! I have added your response to a new FAQ section in the README. Hope it's OK :).
