### ISSUE TITLE
Change React.PropTypes to prop-types to support React 15.5+

### ISSUE THREAD

**Issue by rkait** [namespace-ee/react-calendar-timeline#110]
Thanks for your work on this component!

I am wondering if there is anyone who is planning on changing the imports to remove the warnings in React 15.5+, or can submit a merge request.

Codemod:
https://github.com/reactjs/react-codemod#react-proptypes-to-prop-types

**Comment by signalwerk** [comment]
yapp. we need to do that. do you feel like sending a pull request? I would be happy to review and merge it.

**Comment by mariusandra** [comment]
Hey! I ran the codemod and pushed out `0.14.2` which uses `prop-types`. Thanks for bringing up the topic! 👍

**Comment by signalwerk** [comment]
thanks @mariusandra great

**Comment by rkait** [comment]
thank you @mariusandra for the quick turnaround!
