### ISSUE TITLE
Scroll-Issue → in x-direction with resizedetector

### ISSUE THREAD

**Issue by signalwerk** [namespace-ee/react-calendar-timeline#114]
When I wanted to check for https://github.com/namespace-ee/react-calendar-timeline/issues/39 I came along a scroll issue when I activate the `resizedetector` introduced with https://github.com/namespace-ee/react-calendar-timeline/pull/94:

[Code Example](https://www.webpackbin.com/bins/-KnBdyBTrJ6LZci5lubl) → try to scroll sideways

![scrollbug](https://user-images.githubusercontent.com/992878/27409535-35722408-56e2-11e7-8fe8-2d001427a410.gif)

The `resizedetector` caused since the introduction some issues (https://github.com/namespace-ee/react-calendar-timeline/issues/109) but I think it's good to work on it and make it smooth. Other people could really use it once its bullet proof.

**Comment by mariusandra** [comment]
Hey! This was because when the height of the timeline changed due to stacking updates, it triggered a `resize` and got stuck. I changed it and now only changes in width are registered. Fixed with PR #124
