### ISSUE TITLE
Is it possible to get back to defaultTimeStart-defaultTimeEnd?

### ISSUE THREAD

**Issue by LitvinaviciusM** [namespace-ee/react-calendar-timeline#119]
I need to have a button which changes calendar render view to its default position. Is there any way to do it?

**Comment by mariusandra** [comment]
Hi, for this you need to have a controlled component. Switch from using `defaultTimeStart` and `defaultTimeEnd` to `visibleTimeStart` and `visibleTimeEnd`. You will need to listen to the component's `onTimeChange` callback and update your `visibleTimeStart` and `visibleTimeEnd` accordingly.

See the ["linked timelines" demo](https://github.com/namespace-ee/react-calendar-timeline/blob/master/demo/app/demo-linked-timelines/index.js) for an example on how to do this.

Then to revert to the default position, you just reset your `visibleTimeStart` and `visibleTimeEnd` to what they were initially.

I hope this helps! Feel free to reopen if you have any other questions.

**Comment by signalwerk** [comment]
@LitvinaviciusM also feel free to post a link if you have a cool project public with it. We are always interested to see what people do with the component.

**Comment by t-hughes** [comment]
@LitvinaviciusM Did you get this to work?
