### ISSUE TITLE
Handling onClick

### ISSUE THREAD

**Issue by flyalex** [namespace-ee/react-calendar-timeline#12]
Hi,

Sorry for nooby question, but I cant understand how to handle onClick event on item. 

Thanks for sharing this great component!

**Comment by xmityaz** [comment]
There is [onItemClick](https://github.com/namespace-ee/react-calendar-timeline#onitemclickitemid) property in the Timeline component. But notice that it only triggers when item is already selected.

**Comment by flyalex** [comment]
thank you for reply! That's what I found in the doc, but how then I can use it?

**Comment by mariusandra** [comment]
Hey, I added a [onItemSelect](https://github.com/namespace-ee/react-calendar-timeline#onitemselectitemid) to also catch the first click. 0.7.7 p

@flyalex, what exactly are you having issues with?

Just create a function that should be called when an item is clicked:

```
function onItemClick (id) {
  console.log('it got clicked')
}
```

and pass it to the `<Timeline />` tag:

```
<Timeline
  .... other args ... 
  onItemClick={onItemClick}   
/>
```

**Comment by flyalex** [comment]
@mariusandra thanks! 
(I forgot to add "this.", now it works fine)
Thank you again for sharing!

**Comment by Shadowman4205** [comment]
Hello, what if i want open modal on click with data from itemProps; 
Do i have make changes in master code?

**Comment by marchiartur** [comment]
> There is [onItemClick](https://github.com/namespace-ee/react-calendar-timeline#onitemclickitemid) property in the Timeline component. But notice that it only triggers when item is already selected.

Can I disable this trigger? I'd like to execute the function after the item to be clicked.
