### ISSUE TITLE
itemRenderer implementation

### ISSUE THREAD

**Issue by irmantasp** [namespace-ee/react-calendar-timeline#129]
Hey, guys, I tried implementing this code piece to my code to get custom layout:
`itemRenderer = ({ item }) => {
  return (
    <div className='custom-item'>
      <span className='title'>{item.title}</span>
      <p className='tip'>{item.tip}</p>
    </div>
  )
}`

But I am not sure, where I should put it? 
In <Timeline> component as prop? 
can you give an example?

**Comment by LucidityDesign** [comment]
@irmantasp have a look at https://github.com/namespace-ee/react-calendar-timeline/blob/5017c49efdd9f47ae33d040f3f1632f0e00d5b11/demo/app/demo-main/index.js

**Comment by signalwerk** [comment]
@irmantasp the example @LucidityDesign is commented but there you see it. You find it on [L111-L118](https://github.com/namespace-ee/react-calendar-timeline/blob/5017c49efdd9f47ae33d040f3f1632f0e00d5b11/demo/app/demo-main/index.js#L111-L118)
I close the Issue but feel free if you need any further assistance. ok?

@LucidityDesign thx for your help! Good to see new people coming in!
