### ISSUE TITLE
Calendar Week Unit

### ISSUE THREAD

**Issue by kmueller** [namespace-ee/react-calendar-timeline#130]
As mentioned in another thread I like the calendar component very much.

Today I have tried to add another unit into the calendar: the week. This is a requirement for my current work, so I tried out the following HACK (!) without deeper knowledge of the component... I'd like to share it because the result is sufficient for the moment, but not yet optimum. You can start by default to display the current week by setting the defaultTimeStart and defaultTimeEnd:

```js
var startOfWeek = moment().startOf('week').toDate(); // try also 'isoweek' instead of 'week'
var endOfWeek   = moment().endOf('week').toDate(); // try also 'isoweek' instead of 'week'
```

```js
defaultTimeStart: startOfWeek,
defaultTimeEnd: endOfWeek,
```

---------------------------------
First, here are some screenshots.
<img width="930" alt="week" src="https://user-images.githubusercontent.com/811789/27828389-442cb880-60bc-11e7-8fb1-dd89a35b13c4.png">
<img width="930" alt="month" src="https://user-images.githubusercontent.com/811789/27828398-4ada0d0e-60bc-11e7-8c04-606c87f08824.png">

---------------------------------
This is where I added "week":

1. In Timeline.js 	

a)
```js
export const defaultTimeSteps = {
  second: 1,
  minute: 1,
  hour: 1,
  day: 1,
  week: 1,
  month: 1,
  year: 1
}
```

b)
```js
export const defaultHeaderLabelFormats = {
  yearShort: 'YY',
  yearLong: 'YYYY',
  monthShort: 'MM/YY',
  monthMedium: 'MM/YYYY',
  monthMediumLong: 'MMM YYYY',
  monthLong: 'MMMM YYYY',
  week: 'W',
  dayShort: 'L',
  dayLong: 'dddd, LL',
  hourShort: 'HH',
  hourMedium: 'HH:00',
  hourMediumLong: 'L, HH:00',
  hourLong: 'dddd, LL, HH:00',
  time: 'LLL'
}
```

c) 
```js
export const defaultSubHeaderLabelFormats = {
  yearShort: 'YY',
  yearLong: 'YYYY',
  monthShort: 'MM',
  monthMedium: 'MMM',
  monthLong: 'MMMM',
  week: 'W',
  dayShort: 'D',
  dayMedium: 'dd D',
  dayMediumLong: 'ddd, Do',
  dayLong: 'dddd, Do',
  hourShort: 'HH',
  hourLong: 'HH:00',
  minuteShort: 'mm',
  minuteLong: 'HH:mm'
  }
```
  
d) 
```js
headerLabelFormats: PropTypes.shape({
      yearShort: PropTypes.string,
      yearLong: PropTypes.string,
      monthShort: PropTypes.string,
      monthMedium: PropTypes.string,
      monthMediumLong: PropTypes.string,
      monthLong: PropTypes.string,
	  week: PropTypes.string,
      dayShort: PropTypes.string,
      dayLong: PropTypes.string,
      hourShort: PropTypes.string,
      hourMedium: PropTypes.string,
      hourMediumLong: PropTypes.string,
      hourLong: PropTypes.string
    }),
```

e) 
```js
subHeaderLabelFormats: PropTypes.shape({
      yearShort: PropTypes.string,
      yearLong: PropTypes.string,
      monthShort: PropTypes.string,
      monthMedium: PropTypes.string,
      monthLong: PropTypes.string,
	  week: PropTypes.string,
      dayShort: PropTypes.string,
      dayMedium: PropTypes.string,
      dayMediumLong: PropTypes.string,
      dayLong: PropTypes.string,
      hourShort: PropTypes.string,
      hourLong: PropTypes.string,
      minuteShort: PropTypes.string,
      minuteLong: PropTypes.string
    }),
```

2. In Header.js
a)
```js
headerLabel (time, unit, width) {
    const { headerLabelFormats: f } = this.props

    if (unit === 'year') {
      return time.format(width < 46 ? f.yearShort : f.yearLong)
    } else if (unit === 'month') {
      return time.format(width < 65 ? f.monthShort : width < 75 ? f.monthMedium : width < 120 ? f.monthMediumLong : f.monthLong)
    } else if (unit === 'week') {
      return 'Week ' + time.format(f.week)
    } else if (unit === 'day') {
      return time.format(width < 150 ? f.dayShort : f.dayLong)
    } else if (unit === 'hour') {
      return time.format(width < 50 ? f.hourShort : width < 130 ? f.hourMedium : width < 150 ? f.hourMediumLong : f.hourLong)
    } else {
      return time.format(f.time)
    }
  }
```

b) 
```js
subHeaderLabel (time, unit, width) {
    const { subHeaderLabelFormats: f } = this.props

    if (unit === 'year') {
      return time.format(width < 46 ? f.yearShort : f.yearLong)
    } else if (unit === 'month') {
      return time.format(width < 37 ? f.monthShort : width < 85 ? f.monthMedium : f.monthLong)
    } else if (unit === 'week') {
      return 'Week ' + time.format(f.week)
    } else if (unit === 'day') {
      return time.format(width < 47 ? f.dayShort : width < 80 ? f.dayMedium : width < 120 ? f.dayMediumLong : f.dayLong)
    } else if (unit === 'hour') {
      return time.format(width < 50 ? f.hourShort : f.hourLong)
    } else if (unit === 'minute') {
      return time.format(width < 60 ? f.minuteShort : f.minuteLong)
    } else {
      return time.get(unit)
    }
  }
```

3. In utils.js

a)
```js
export function getMinUnit (zoom, width, timeSteps) {
  let timeDividers = {
    second: 1000,
    minute: 60,
    hour: 60,
    day: 24,
	week: 7,
    month: 30,
    year: 12
  }
```

b) 
```js
export function getNextUnit (unit) {
  let nextUnits = {
    second: 'minute',
    minute: 'hour',
    hour: 'day',
    day: 'week',
	week: 'month',
    month: 'year'
  }

  return nextUnits[unit] || ''
  }
```
  
---------------------------------
What I noticed:

- It's not possible to change from week to month and year on header clicks
- It's possible to zoom to month and year by pinching
- The week starts from Sunday until Saturday
- The header is not localizable (of course...)

---------------------------------
My wishlist for the calendar:

- A property to add other units like "week" or "quarter year"
- Week definition according iso standard ( in momentjs "isoweek" ) from Monday to Sunday
- Localization for Header title
- Nice to have: A way to zoom out by click (e.g. from week to month to year)

**Comment by signalwerk** [comment]
hey @kmueller!
I like your correction! I just read the code quickly but would like to give it a run. I think I can use it also in my project. 

If @mariusandra agrees I would like to have your code also in the master branch here. 

### Contributor
I could take your code and copy it to the files. But then I get the credit for your code (git tracks it). And I always like when people get credit for their work. Plus I like to have new contributors to this repo. So if you like you could also do a Pull Request. Did you do that before? The steps would be:
* fork this repo
* clone your repo to your local machine
* create a new branch and do the corrections
* push that branch to your github-account 
* do a pull request

With that behaviour you get the credits and you become a contributor (plus you make our live easier :). Sorry if I explained you steps you already know. 
But please wait for the opinion of @mariusandra if we wanna have it in master.


### Your Wishlist
Nice!
* A property to add other units like "week" or "quarter year" → it would be good to have something like a configuration for that! Maybe control that via `timeSteps` (don't ask how... :) what would you suggest @mariusandra ?
* Week definition according iso standard ( in momentjs "isoweek" ) from Monday to Sunday → see last point
* Localization for Header title → you mean according to your language? 
* Nice to have: A way to zoom out by click (e.g. from week to month to year) → I would solve that by an additional component that controls `defaultTimeStart` and `defaultTimeEnd`. But it would also be cool to have that on a elegant position in the component. Would you have an idea for it?

### Github-Comments
No critics at all! We love to hear from you no matter how. But probably you didn't know. If you have something like:

```
{
  test: 1
}
```
and you past it with no editing you get:

{
  test: 1
}

just write:

````
```js
{
  test: 1
}
``` 
````
then you get the correct formatting:
```js
{
  test: 1
}
``` 

I changed your comment to give it code-formatting and get colorzzz 😍

**Comment by kmueller** [comment]
@signalwerk Thanks for your comment! Contributing is new to me, so thanks for the steps. I'd like to make life easier for you, credits are not important. So -> next time ;-) I'll give it a try. This time it maybe makes sense that you invent some kind of configuration before including the "week" and take over the changes as you like - otherwise the current behavior of the calendar with day/month/year will be broken. 

Localization is on the list because I didn't succeed to concatenate a string to the momentjs format 'W' (e.g. week: 'Week W' in the header label format results in a strange output). I'd like the header to display "Week 26" in locale en, or "Woche 26" for locale de.

The last point with the "zoom out by click" is really difficult, because the component wins because of its "simplicity" i.e. the less buttons the better (but that's my opinion). I have no good idea in the moment that's why I said "nice to have"...

**Comment by brentoneill** [comment]
Subscribing to this issue as this is a feature that I need to implement as well.

**Comment by t-hughes** [comment]
@kmueller any movement on this?

**Comment by kmueller** [comment]
@t-hughes Hi Talon, sorry for the late reply (holiday season...). I also don't know if there are some plans to integrate "weeks" by a new configuration feature. 
Regarding your question about the gray borders I am not quite sure if I understand you right: Is the styling in my example other than you expected? (I took the screenshots from some other project than the default example)

**Comment by jabidof** [comment]
Hello there,
Week unit is a common feature for plannings and alike.

Is there any plan to integrate it to RCT?

Thanks.
J.

**Comment by jabidof** [comment]
@kmueller do you mind publishing your above code/snapshot related? I'd like to give it a shot.

**Comment by kmueller** [comment]
@jabidof Hi, everything I changed in the code can be found in the original post above. I personally did not create a regular React component from it, but I used the build configuration from [gabriel-deliu](https://github.com/gabriel-deliu/react-calendar-fine-timeline) to create a JavaScript library...

**Comment by jabidof** [comment]
@kmueller
Thanks 
Enjoy the weekend

**Comment by mcMickJuice** [comment]
hey @jabidof i implemented @kmueller s changes in this branch - https://github.com/namespace-ee/react-calendar-timeline/tree/feature/weeks-view

The logic that still needs to be tweaked is in this file - https://github.com/namespace-ee/react-calendar-timeline/commit/ad279d244a9d940e28aa0e2a49fbc92ece79c42f#diff-cb66ba9b01505371573edba866680f91

That details the commit of changes i made to get weeks to show when you toggle/click the header.  When i find time, I am going to work on this too but right now:

- when in "day: hour view", clicking the day brings us to "week: day" view.  This is correct behavior IMO
- when in "week: day view", clicking the week causes us to stay in "week: day: view, but it expands the timeline range. This seems like a bug to me. Clicking on the header should ALWAYS change the units in the header

I think we need to heavily refactor getMinUnit and maybe change how units are changed when clicking in the header.  good luck and let me know what you find out after digging into the code.

**Comment by jabidof** [comment]
@mcMickJuice thanks very much for the input. I'll do my homework soon to test it and dig in the code.

Currently I'm having some difficulties managing big amount of items (~5k) in the timeline. I noticed it re-renders a lot although nothing changed except the time scale.
I tried using recompose (https://github.com/acdlite/recompose) without success till now. 
Except `fullUpdate={false}` is there a way you could point me to to avoid some re-render and make it smoother?

**Comment by mcMickJuice** [comment]
re: performance, lets take the discussion over to issue https://github.com/namespace-ee/react-calendar-timeline/issues/247

**Comment by mcMickJuice** [comment]
@jabidof what are your use cases when you see performance degradation in the timeline?

**Comment by mcMickJuice** [comment]
Closing in favor of https://github.com/namespace-ee/react-calendar-timeline/issues/361.  All discussion will continue over there.

**Comment by azeghers** [comment]
Sorry about necrobumping, but I'd like to know if the point about making Monday the first day of the week was addressed anywhere and if so, how I can enable it.

**Comment by AO19** [comment]
> first day of the week

Did you find a solution?

**Comment by AO19** [comment]
> Sorry about necrobumping, but I'd like to know if the point about making Monday the first day of the week was addressed anywhere and if so, how I can enable it.

@azeghers  Did you find a solution?
