### ISSUE TITLE
Sticky Offset

### ISSUE THREAD

**Issue by kmueller** [namespace-ee/react-calendar-timeline#135]
For my work I have the need to define the offset for the fixedHeader "sticky". 

The motivation is the following: I have a Bootstrap Navbar scrolling up. At a certain point the Navbar is fixed in its position with a certain height. I want the calendar header scroll up and to be sticky up to the height of the Navbar.

See the screenshots below.

I have added this locally to the my calendar. If you are interested in this feature I will do all this fork/contribute stuff... 

![stickyoffset1](https://user-images.githubusercontent.com/811789/28167211-1bbc6028-67db-11e7-999f-734252d4b014.png)
...scroll scroll scroll...
![stickyoffset2](https://user-images.githubusercontent.com/811789/28167224-2322979c-67db-11e7-8ece-ff0594feaa9c.png)
...scroll scroll scroll...
![stickyoffset3](https://user-images.githubusercontent.com/811789/28167232-2a2792c2-67db-11e7-95ed-203e5eece95e.png)

**Comment by signalwerk** [comment]
personally speaking I love "fork/contribute stuff" 😂
I think it would be nice to have that option in the repo. @mariusandra your opinion?

**Comment by mariusandra** [comment]
Hey, this is indeed a nice option to have! I can see myself using it as well. I merged your PR and pushed out 0.15.1, thus closing the issue. Thanks! :)
