### ISSUE TITLE
Tree Groups Open on page load

### ISSUE THREAD

**Issue by malindamiller** [namespace-ee/react-calendar-timeline#136]
Hi, I am trying to mimic your treeGroups example, and it works except I would like the groups to be open when I load the page. So when I set my groups and items in my componentDidMount(), I set the openGroups to be all of my groups. 
```
      this.setState({
        appointments: appointments,
       groups: assignments,
        openGroups: assignments
      });
```
As shown in the screenshot, it works for the top of the list of groups, but then suddenly they are not expanded anymore. Then the last group in the list is expanded
![image](https://user-images.githubusercontent.com/5913642/28288644-e5d2513a-6b0d-11e7-94a0-aec0e6d0a326.png)

Here is my code in the render method to create the groups:
   ```
  const newGroups = groups.filter(g => g.root || groups[g.parent]).map(group => {
       return Object.assign({}, group, {
         title: group.root ? (
           <div onClick={() => this.toggleGroup(group.id)} style={{ cursor: 'pointer' }}>
             {groups[parseInt(group.id)] ? '[-]' : '[+]'} {group.title}
           </div>
         ) : (
           <div style={{paddingLeft: 20}}>
             {group.title}
           </div>
         )
       }
```
Any idea why this could be happening?

**Comment by mariusandra** [comment]
Hey, it sounds like an issue with mutating data.

The first thing I notice: in the [groups demo](https://github.com/namespace-ee/react-calendar-timeline/blob/master/demo/app/demo-tree-groups/index.js), `openGroups` is an object with this structure: `{ groupId: true, otherGroupId: false }`. You seem to be assigning the same object to `groups` and `openGroups`, which makes me believe that your `openGroups` is an object of objects, not an object of booleans. 

It's hard to see more from the small code examples you provided. Is it possible to have a version of this on [webpackbin](https://www.webpackbin.com/bins/-Kmp5BRA25HDJy1SoW47) so I could debug further?

**Comment by malindamiller** [comment]
Closing this, as I no longer need this functionality.
