### ISSUE TITLE
How to control the unit of time?

### ISSUE THREAD

**Issue by gyarasu** [namespace-ee/react-calendar-timeline#138]
Hi.

I'm developing gantt chart on my project and using this module.
I want to deal with minimum time unit as a day.
In my project, I don't need the time unit smaller than a day, (hour, minute, or less).

Do you have any way to control the unit of time?

Thanks.

**Comment by brentoneill** [comment]
The `minZoom` prop should cover that. Set to `minZoom={60 * 60 * 1000 * 24}` (1 day)
https://github.com/namespace-ee/react-calendar-timeline#minzoom

**Comment by gyarasu** [comment]
@brentoneill 
Thanks for your response!
My description was not enough, I'm sorry.
And I solved my problem by myself.
