### ISSUE TITLE
How to return the item Object when an item is selected

### ISSUE THREAD

**Issue by shahsnidhi** [namespace-ee/react-calendar-timeline#139]
I am using onItemSelect() to to display important information about a particular item. 
I see the onItemSelect only returns itemId and not the itemObject

Is there are way to return the item Object or have access to the selected itemObject?

Thanks

**Comment by mariusandra** [comment]
Hey, not at this moment. The logic assumes that they cod which listens to the callbacks where you get the ID of the object, also has access to the objects themselves.

For a future release we should rethink the API and decide if it's wiser to return objects or just object IDs like now. But for now, no changes are expected.

**Comment by mcMickJuice** [comment]
A workaround for this is to `JSON.stringify` your object and set as the id.  In the item callback, `JSON.parse` the string to get your object

**Comment by mcMickJuice** [comment]
@shahsnidhi im going to close this as the workaround above (https://github.com/namespace-ee/react-calendar-timeline/issues/139#issuecomment-343765038) should help you achieve this
