### ISSUE TITLE
How to disable sidebar ?

### ISSUE THREAD

**Issue by ochervak** [namespace-ee/react-calendar-timeline#14]
I wan't to disable sidebar because of specific requirements, and i pass `sidebarWidth={0}`. Timeline rendered on large screen, but on smaller (1500px width) it just disappeared.

If i remove `sidebarWidth={0}` all works fine. Maybe there is a better way to disable sidebar ?

**Comment by mariusandra** [comment]
Hey, I pushed out 0.7.9 that fixes `sidearWidth={0}`.

**Comment by ochervak** [comment]
@mariusandra thank you so much!
