### ISSUE TITLE
Create onHeaderClick and onSubHeaderClick callbacks

### ISSUE THREAD

**Issue by brentoneill** [namespace-ee/react-calendar-timeline#140]
Originally I thought I could just use the `onBoundChange` to accomplish what I was trying to do, but it fires on when the user scrolls left/right and changes the timeline bounds that way.

So, I propose adding two callbacks as props:
- `onHeaderClick(time, unitOfTime, event)` 
- `onSubHeaderClick(time, unitOfTime, event)`.

They would pass the header/subheader datetime, the current "unit" of time in the timeline (hour, day, month, year), and the click event as args. I need this to track changes in the unit of time in my container component. 

Working on a PR for this right now.

**Comment by t-hughes** [comment]
@brentoneill any progress on this? Thinking I may need this as well and could possibly help.

**Comment by mcMickJuice** [comment]
@t-hughes  @brentoneill I believe this would be pretty straightforward to implement. Maybe have the signature be

`onHeaderClick(time, prevUnitOfTime, nextUnitOfTime, event)` in case you want to know how the unit of time is changing

**Comment by Ilaiwi** [comment]
This can be achieved by leveraging Custom headers like the following. 

https://codesandbox.io/s/x9m2r5941p

**Comment by Ilaiwi** [comment]
released in 0.25.0
