### ISSUE TITLE
ToolTipRenderer

### ISSUE THREAD

**Issue by gyarasu** [namespace-ee/react-calendar-timeline#144]
Hi.

When I put mouse pointer an item, I can see a tooltip.Tooltip seems to be including the title of a item by default.
I want render a tooltip freely as well as item and group.
In the case of item and group, there are properties to edit the element, groupRenderer and itemRenderer.
Is there the way to edit tooltip element already?

<img width="362" alt="2017-07-25 15 48 52" src="https://user-images.githubusercontent.com/4948588/28559330-12c0ba12-7151-11e7-8b8b-80a465f6c528.png">

Thnaks.

**Comment by mariusandra** [comment]
Hi, the tooltip that you see is the standard browser tooltip (title tag). Unfortunately there is no way to edit the content and style of this element. If you wish to have a tooltip that you can edit, you need to wrap your items in some tooltip library.

One that I have used in the past is called [`rc-tooltip`](https://github.com/react-component/tooltip). 

With it your code could look something like this:

```js
itemRenderer = ({ item }) => {
  return (
    <Tooltip placement="left" trigger={['click']} overlay={<span>tooltip</span>}>
      <div className='custom-item'>
        <span className='title'>{item.title}</span>
      </div>
    </Tooltip>
  )
}
```

**Comment by gyarasu** [comment]
@mariusandra 
I understand.
Thank you for your answer.
