### ISSUE TITLE
Custom styles

### ISSUE THREAD

**Issue by clementino36** [namespace-ee/react-calendar-timeline#145]
Hi, I don't see anything in the docs about styling the timeline. 
So far I've been able to style groups and items using `itemRenderer` and `groupRenderer` but this doesn't allow one to do much on styling.  For example, applying a background color to an item will only put a color on top of the default blue one, and some blue pixels will still be visible (margin and padding don't solve this): 
![capture](https://user-images.githubusercontent.com/6041593/28574636-d6012d7a-714e-11e7-929e-302f7a114312.PNG)
Shouldn't there be some props to easily change the color when items are selected/unselected, etc ... ?
Same with the timeline's grid and header, how to change the header (red by default) or the weekend columns (pale yellow) color for example ?
Hopefully I'm not missing something obvious but I think this is essential.

**Comment by brentoneill** [comment]
Simply change the styles via CSS? They style are nested so they are hard to override, but it is possible. Inspect the elements and just copy/paste the selectors to your own CSS/Less/SCSS files.

**Comment by clementino36** [comment]
Ok thanks i'll do that!
