### ISSUE TITLE
Disable scrolling

### ISSUE THREAD

**Issue by clementino36** [namespace-ee/react-calendar-timeline#147]
Hi! Is there an easy way to disable horizontal scrolling when holding shift ? 
Basically, is there a way to change keyboard + mouse actions ? 
Thanks for an amazing library.

**Comment by mariusandra** [comment]
Hey, there is no such action at the moment. We have tried to keep the scrolling modifier actions to sane defaults that work for 99% of the people, see the discussion in #79. That said, I have nothing against the option of making the defaults configurable.

If you're willing to give a crack at implementing it, we can help in whatever way we can.

The things that need to be done for this are:

1. Propose and agree on an API to change the defaults (what props do what).
2. Implement this by changing the behaviour of the `onWheel` function in src/lib/Timeline.js
3. Document the API in the README
4. Create a demo that showcases the new feature.

**Comment by clementino36** [comment]
If my schedule allows it, i'll be glad to give it a try! Closing for now but might come back to this.

**Comment by kayoshi** [comment]
Hi! Is there any changes for this issue?

**Comment by mcMickJuice** [comment]
No, I personally don't plan on addressing this any time soon

**Comment by gino8080** [comment]
not the best and clean solution, but this works

```javascript
 document.querySelector('.rct-scroll').onwheel = function (e) {
      e.preventDefault();
      e.stopPropagation();
      return false;
    };
```
