### ISSUE TITLE
Upgrading to 0.15.0 causes Unexpected token

### ISSUE THREAD

**Issue by bavicj** [namespace-ee/react-calendar-timeline#148]
Hi,
after I upgraded Timeline to 0.15.0 I have problems building my bundle due to class attributes.
`
Module parse failed: xxx/node_modules/react-calendar-timeline/src/lib/Timeline.js Unexpected token (73:19)
You may need an appropriate loader to handle this file type.
|
| export default class ReactCalendarTimeline extends Component {
|   static propTypes = {
|     groups: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
|     items: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
`

Using "import Timeline from 'react-calendar-timeline/lib'" solves this problem (as suggested in README and #51 ), but still, my babel config is using preset-0 and everything worked until version 0.15.0.
My babel presets are : ['es2015', 'stage-0', 'react']

Any suggestion what change in 0.15.0 could cause this behaviour?

**Comment by mariusandra** [comment]
Hey, it's possible in your webpack config you have `babel-loader` set to exclude `node_modules`. With this exclusion there, webpack will take the ES6 code of `react-calendar-timeline`, but won't transpile it to ES5... and your stage-0 config will have no effect.

The only solution I know is to remove the exclusion of `node_modules`. Does anyone know of a better way?

**Comment by bavicj** [comment]
Hey, thanks for quick response.
Yes, that is exactly how my webpack config is configured -> excluded node_modules.
Thing is I don't want babel to process all my node_modules because it makes build very slow. I can probably exclude node_modules except timeline library.
But strange thing is, that once I revert to 0.14.11, everything works. With any other changes in webpack

**Comment by mariusandra** [comment]
Hey, there were many changes between 0.14.11 and 0.15.0, but the relevant one here is [this change](https://github.com/namespace-ee/react-calendar-timeline/commit/a0a7f5a093ebdd1f54095e2739564a862c4c59c7) of adding the `module` field to `package.json`.

I recently ran into the same issue with [a different project](https://github.com/keajs/kea-website/commit/1c2f4fe8e97c50fc922b7f9b533f1f4104643cff) and just started to transpile everything. In theory there should be way to just transpile code in webpack 2+ that uses the `module` import paths, but I'm not sure how. 

Here's [a package](https://github.com/andersdjohnson/webpack-babel-env-deps) that tries to do that... and the relevant discussion on the [webpack repo](https://github.com/webpack/webpack/issues/2031).

**Comment by bavicj** [comment]
okey, so I tried what they proposed in webpack repo and it is working.
Solution for my babel-loader:
exclude: /node_modules(?!\/react-calendar-timeline)/,

Thank you and keep up in great work ;)

**Comment by nygardk** [comment]
An alternative way to make this work is to add webpack module alias:
```
alias: {
  'react-calendar-timeline': 'react-calendar-timeline/lib',
},
```
I think it is cleaner, and doesn't needlessly compile the library.

**Comment by asaf** [comment]
This is not needed, just include js from the lib folder

```js
import Timeline from 'react-calendar-timeline/lib'
```
