### ISSUE TITLE
Customizing Item after some zoom?

### ISSUE THREAD

**Issue by efthpt** [namespace-ee/react-calendar-timeline#150]
Hello,
i downloaded all src file to my project. After some zoom out i make item to appear as dots. But i cannot align them vertically in center. Any suggestion how make this happen?

**Comment by mcMickJuice** [comment]
Are you referring to the items in the timeline turning into dots when you zoom out? If so, this is a great idea!

If you could submit your changes as a PR, that'd be great!  I could then review what you're trying to achieve and help you out :)

**Comment by mcMickJuice** [comment]
See the example [here](https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples#custom-item-rendering-using-timelinecontext---conditionally-render-components) on how to use the `timelineContext` passed to an `itemRenderer` to change how you're displaying an item.  Re: your specific issue with centering, you can override the css classes that are imported in the timeline.css. See [FAQ](https://github.com/namespace-ee/react-calendar-timeline#how-can-i-have-items-with-different-colors)
