### ISSUE TITLE
Running forked version of this project

### ISSUE THREAD

**Issue by malindamiller** [namespace-ee/react-calendar-timeline#151]
Hi, I need to fork this project and use the forked version in my package.json. Do you have any suggestions for doing this? 

```json
{
  "name": "conductor-schedular-3",

  "version": "0.1.0",

  "private": true,

  "dependencies": {
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "bootstrap": "^3.3.7",
    "custom-react-scripts": "^0.0.23",
    "interact.js": "^1.2.8",
    "moment": "^2.18.1",
    "react": "^15.6.1",
    "react-calendar-timeline": "github:malindamiller/react-calendar-timeline",
    "react-dom": "^15.6.1",
    "react-hot-loader": "^3.0.0-beta.7",
    "react-modal": "^2.2.2",
    "react-time-select": "^2.2.1"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "node-sass": "^4.5.3"
  },
  "scripts": {
    "build:react-calendar-timeline": "cd ./node_modules/react-calendar-timeline && npm run build:lib:local && cd ../../",
    "start": "npm run build:react-calendar-timeline && react-scripts start",
    "build": "npm run build:react-calendar-timeline && react-scripts build",
    "test": "npm run build:react-calendar-timeline && react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}
` ``
The build scripts' file paths do not seem to work when used in this context, but when I attempted to modify them, I encounter more errors.

**Comment by eamonpenland** [comment]
i removed lib from .gitignore

**Comment by mcMickJuice** [comment]
@malindamiller did @eamonpenland s comment help you?

Instead of running a build step as part of your project that consumes react-calendar-timeline, did you also consider running the build script in your forked version and pushing those to your github repo (thats referenced in the package.json dependencies)?

FYI, I tried running this build step on my windows machine and it failed.  Running it on a mac worked however.

**Comment by mcMickJuice** [comment]
to fix issue on windows for build, just remove the relative path to node_modules:

`echo '!!! Building Library' && babel src --out-dir lib && node-sass src/lib/Timeline.scss lib/lib/Timeline.css && sed -i'.bak' 's/Timeline\\.scss/Timeline\\.css/g' lib/lib/Timeline.js && rm lib/lib/Timeline.js.bak"`

**Comment by mcMickJuice** [comment]
Closing as you can remove lib from gitignore and build the project locally
