### ISSUE TITLE
performance in horizontal scrolling 

### ISSUE THREAD

**Issue by mrgreenward** [namespace-ee/react-calendar-timeline#153]
Hello! I use this great component with a lot items. Sometimes more than 1000.
http://prntscr.com/g6nmvj
 To get a normal performance i added lazy load component for vertical scrolling:
  ```
 title:
                            <LazyLoad height={862} offsetVertical={100}>
                                <UserItem user={user}
                                          drivers={props.drivers}
                                          updateData={updateData}
                                          handleOpen={handleOpen}
                                          handleClose={handleClose}
                                          getUserData={getUserData}
                                />
                            </LazyLoad>
```
 Partially it resolve my problem. But horizontal scrolling still not smoothly.I didn't understand how to wrap lazyload to items?

**Comment by mcMickJuice** [comment]
Is it possible for you to post working code via sandbox or other means? It would greatly help us troubleshoot this problem.

You can use this as a starting point:

https://codesandbox.io/s/x3ql17x204

**Comment by mcMickJuice** [comment]
I'm going to close this as performance with 1000s of items will tend to be bad with many libraries :)

No but seriously, I imagine in the near future we'll push a release that focuses solely on performance...maybe even use virtualization!  Thanks for the issue though.

**Comment by anujgakhar** [comment]
Is there any update here? In terms of performance and virtualization?
