### ISSUE TITLE
 onCanvasClick reports the incorrect groupId

### ISSUE THREAD

**Issue by Darkdragon14** [namespace-ee/react-calendar-timeline#159]
Hey,
My problem is when I click on a line after the scroll, the Timeline take the id of the first apparence.
**Exemple** : 
      after the scroll if I click on the fisrt line I get back the fisrt id of my group

I hope you can help me and thank for your good job 👍

**Comment by beeant** [comment]
happens to me too... >.<

**Comment by beeant** [comment]
seems like it works fine on Safari

**Comment by Darkdragon14** [comment]
Yes it works on safari with the mac's track pad  but when you use on other laptop this is a problem

**Comment by mcMickJuice** [comment]
Hello, I know this is an old issue but could you provide an example of this bug occurring?  You can use https://codesandbox.io/s/x3ql17x204 as a starter

**Comment by Darkdragon14** [comment]
I am sorry but I don't see the solution with your example... because my problem is with the vertical scroll :/
But think you for your possibility 👍

**Comment by Darkdragon14** [comment]
It's good, I make my bug on the sandbox. So when you click some where on the calendar if you scroll, the id correspond to the first group or second group
I hope that I am understanding ^^
think you for your help 👍

**Comment by vasdee** [comment]
@mcMickJuice if I understand this problem correctly I think it is todo with dynamic content that pushes the timeline vertically down. The effect this has is to offset all the click events and report the wrong group id.

Check the sandbox link, click the add content button a few times until the timeline shifts, then double click an area to see that the group is incorrect.

https://codesandbox.io/s/myn3zw2qw8

If this isn't the same issue then I can raise this in a separate ticket

**Comment by mcMickJuice** [comment]
Thanks for the demo @vasdee that really helps.

**Comment by Darkdragon14** [comment]
@vasdee Thanks, you understood the problem, but for the moment, I can not try. Normally, I return on this project soon so I will tell you if your solution is correct 😃

**Comment by mcMickJuice** [comment]
This should be fixed in 0.16.x:

https://github.com/namespace-ee/react-calendar-timeline/issues/296
