### ISSUE TITLE
Ability to remove items.

### ISSUE THREAD

**Issue by t-hughes** [namespace-ee/react-calendar-timeline#160]
is there a built in option to remove items from the timeline? I am not seeing one.

**Comment by brentoneill** [comment]
Use the itemRenderer function and add a button w/ a callback that removes the item from the list of items you pass in?

**Comment by mcMickJuice** [comment]
@t-hughes did @brentoneill 's suggestion help you?

**Comment by t-hughes** [comment]
@mcMickJuice Yes, my apologies. I got carried away on my project. Thank you @brentoneill ! I will close this issue.
