### ISSUE TITLE
Changing the date shown on a button click

### ISSUE THREAD

**Issue by malindamiller** [namespace-ee/react-calendar-timeline#163]
I want to default the view to today, and then have a button that opens a calendar date picker to select a date to show.  I tried to set the defaultTimeStart and defaultTimeEnd as states but it does not update the date range shown.  I don't know what I am missing.  Here is an example,  for simplicity I am just trying to change the time shown to a static time.

```  
changeDate() {
        this.setState({
          viewStart: moment().startOf('day').hour(8).minute(0).valueOf(),
          viewEnd: moment().startOf('day').hour(11).minute(0).valueOf()
        }, function () {
          this.forceUpdate()
        });
  }

          <button  onClick={() => this.changeDate()}>Change Date</button>
          <Timeline groups={newGroups}
            items={this.state.appointments}
            defaultTimeStart={this.state.viewStart}
            defaultTimeEnd={this.state.viewEnd}
            />
```

**Comment by brentoneill** [comment]
Try updating the props: `visibleTimeStart` and `visibleTimeEnd` instead of `defaultTimeStart` and `defaultTimeEnd`

**Comment by mcMickJuice** [comment]
hey @malindamiller did @brentoneill 's tip help you?  

Also, separately, in your `changeDate` handler, you dont need to call `this.forceUpdate()` since setState will trigger a re-render

**Comment by malindamiller** [comment]
yes, this helped me. I can close this issue.
