### ISSUE TITLE
Calculate linewidth from groupRender

### ISSUE THREAD

**Issue by Najarana** [namespace-ee/react-calendar-timeline#164]
I was excited to see the groupRenderer prop but it seems like the line height does not take the content into consideration. Seeing as the line height can grow and shrink with stacked items I was expecting the same behavior when using a custom groupRenderer. 

The use case for this is that I have different types of groups which might or might not need additional info in the grouplabel.

Is there any way to achieve this functionality?

**Comment by mcMickJuice** [comment]
The lineHeight is needed to align the group element height to the height of the individual heights of items in the timeline.  These elements are really not related to each other in the dom so to ensure that the "tracks" line up together, we calculate group height based on `lineHeight` * number of items stacked.  We can't accommodate (right now) the content of your group into its height.

The alternatives are a popover in the group that, when you hover or click, shows all of the contents.  Or provide a large lineheight to the library.
