### ISSUE TITLE
Is it possible to try out the component in online editor e.g. Sandbox?

### ISSUE THREAD

**Issue by gam0ny** [namespace-ee/react-calendar-timeline#166]
Sorry for posting this, but i'm struggling to try out the component via online editor (sandbox) and looks like have difficulties for include it into the project. 
Is there any specific on using the packages?

proxyConsole.js:68 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

https://codesandbox.io/s/p5ypq4zo5j

**Comment by mcMickJuice** [comment]
I didnt get the same error you referenced but in your link, you weren't passing in some required attributes:

https://codesandbox.io/s/x3ql17x204

Does the above link work for you?

**Comment by gam0ny** [comment]
Hey, thanks for your response. Looks like my issue isn't reproducible anymore. Required parameters haven't been specified in my case, because the issue was about accessing Timeline component. For some reason it was coming as null. Anyway not it's not applicable anymore.
