### ISSUE TITLE
typescript definitions for react-calendar-timeline

### ISSUE THREAD

**Issue by radziksh** [namespace-ee/react-calendar-timeline#17]
I'm creating typescript definition for react-calendar-timeline. Can you, please, say which properties is required in Timeline conponent? defaultTimeStart and defaultTimeEnd? Or there is no required properties?

**Comment by radziksh** [comment]
@mariusandra @meikoudras @xmityaz can you, please, review my PR in DefinitelyTyped project. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/9158

**Comment by mariusandra** [comment]
Hi, the only required ones are `items` and `groups`.

I have never used TypeScript, so I can't comment much on the PR. However from what I see, perhaps also add a 

```
groups: {
  id: number;
  title: string;
}
```

and remove the `?` from `items?`, and add the `?` to `defaultTimeStart` and `defaultTimeEnd`.

**Comment by comlaterra** [comment]
@radziksh would be possible to update the types, if I'm not wrong they are quite outdated
