### ISSUE TITLE
onCanvasClick returns wrong row when page scrolled in most browsers

### ISSUE THREAD

**Issue by dbhaasis** [namespace-ee/react-calendar-timeline#170]
After chrome updated to 61, I noticed onCanvasClick is not returning the correct row when the whole page is scrolled. They changed the scroll element to HTML instead of BODY, however offsetParent returns BODY as top level element throwing off calculation of position when the page is scrolled. It always return the row as if the page were not scrolled.  Firefox and Edge had the same issue. I created a pull request with the modification I had to use to fix the problem in my forked repository. 

I want to switch back to using the regular react-calendar-timeline as soon as this issue is resolved.

**Comment by mariusandra** [comment]
Hey, I merged in the PR. Thanks for the patch :)

**Comment by mcMickJuice** [comment]
@dbhaasis is this still in issue? If not can you please close this issue?
