### ISSUE TITLE
Increase height of Group and Demo's not working

### ISSUE THREAD

**Issue by nickpricks** [namespace-ee/react-calendar-timeline#172]
I need to render a big div with loads of data instead of single line as Item. But it does not automatically takes height of div. How can I deal with this issue. Please suggest something and also demo code url's are not working. For more details check this link. https://prnt.sc/gvgu5t

**Comment by mcMickJuice** [comment]
created an issue for demo page not working https://github.com/namespace-ee/react-calendar-timeline/issues/178

**Comment by mcMickJuice** [comment]
Do you sample code that you can provide? either via codesandbox or other so we can see how you're creating the div that's shown in the timeline?

**Comment by mcMickJuice** [comment]
Closing due to non-response
