### ISSUE TITLE
State isn't properly updated when ending resize

### ISSUE THREAD

**Issue by Biohazord** [namespace-ee/react-calendar-timeline#173]
In each ```Item``` we only call the ```onResized``` props event if there's a [non-zero change](https://github.com/namespace-ee/react-calendar-timeline/blob/6a83d8721294b388db82479639ad7fa1024da3c5/src/lib/items/Item.js#L297). This leads to an incorrect state within the Timeline since its [```resizedItem``` callback ](https://github.com/namespace-ee/react-calendar-timeline/blob/cb91b393829535866374eaeb9be36ea1b5747976/src/lib/Timeline.js#L749) is never called, leaving the state values ```resizeTime```, ```resizingEdge```, and ```resizingItem``` in their previous state. 

Should the item always trigger the callback and pass the time delta back so that the ```Timeline``` itself? It can then decide how to deal with the change.

**Comment by mcMickJuice** [comment]
This will be fixed with next release 0.15.6
