### ISSUE TITLE
Horizontal line between items

### ISSUE THREAD

**Issue by candaya** [namespace-ee/react-calendar-timeline#175]
Hello,

Is there a way to render a horizontal line connecting elements?

**Comment by mcMickJuice** [comment]
What is the use case here? Is there a relationship between items on the timeline?

**Comment by mcMickJuice** [comment]
I'm going to close this issue. As I don't think we'll implement a feature where there's a relationship between items.  I'll reopen if you could provide a use case that fits the scope of this library.
