### ISSUE TITLE
When push new groups & items, errors appears

### ISSUE THREAD

**Issue by ochervak** [namespace-ee/react-calendar-timeline#18]
Error appear, when i push new props to the timeline.
`Items.js:113 Uncaught TypeError: Cannot read property 'dimensions' of undefined`

Transpiled line: `dimensions: sortedDimensionItems[(0, _utils._get)(item, itemIdKey)].dimensions,` in `render`
My setup:
- React 15.0.2
- Timeline 0.7.9

**Comment by Janckk** [comment]
Same here, it has to do with re-rendering. If you try to zoom in you will now be able to stop getting that error and everything runs normal again. Looking for a workaround

**Comment by ochervak** [comment]
@Janckk so i should reduce re-rending counts?

**Comment by Janckk** [comment]
Haven't found a solution yet. But if I zoom in and out the rerendering happens. Because if I push the new prop to the timeline I don't see immediate result. For example: I push another item and I only see it displayed after zoom in/out or when I drag other already existing items. If you add a new item you see it immediately rendered?

**Comment by mariusandra** [comment]
Hey, the timeline expects your `items` and `groups` arrays, and actually all other props as well, to be immutable. That means if you change something in `items`, you must pass it a new array with new items. Just adding something into the existing array will not work.

The `sortedDimensionItems` array is only updated when [this condition](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src%2Flib%2FTimeline.jsx#L231) is met:

```
nextProps.items !== this.props.items || nextProps.groups !== this.props.groups
```

That means, don't mutate your items array, pass in a new items array.

**Comment by mariusandra** [comment]
For some example code, I assume this is what you currently do:

```
var items = []
<Timeline items={items} />

items.push({id: 1})
items.push({id: 2})
items.push({id: 3})
```

But this is what you should be doing:

```
var items = []
<Timeline items={items} />

items = items.concat([{id: 1}])
items = items.concat([{id: 2}])
items = items.concat([{id: 3}])
```

This makes the timeline aware that the items array changed. Otherwise it's not smart (nor fast) enough to check every element inside items for changes.
