### ISSUE TITLE
Npm build scripts fail on windows

### ISSUE THREAD

**Issue by mcMickJuice** [namespace-ee/react-calendar-timeline#181]
`build`, `build:demo` and `build:lib` all fail on windows, related to using relative paths in the script.  I think these scripts should be rewritten in the same fashion that `build.js`, taking into account differences in environments

**Comment by Biohazord** [comment]
I would also like to note that, on windows, I ran into two issues when using the command ```build:demo```

First off setting ```BABEL_ENV=react``` fails on windows. I had to install cross-env and then change the line to ```"build:demo": "echo '!!! Building Demo' && cross-env BABEL_ENV=react node build.js production",```.
Second issue was within the build.js file. The relative path for webpack was not found. The quick fix was this.

```
var path = require('path')

var webpackPath = path.join(__dirname, '/node_modules/.bin/webpack')
var cmdLine = webpackPath + ' --progress'
```

**Comment by mcMickJuice** [comment]
Fixed with https://github.com/namespace-ee/react-calendar-timeline/pull/271
