### ISSUE TITLE
MouseLeave while dragging causes component to think its still in "dragging" state

### ISSUE THREAD

**Issue by mcMickJuice** [namespace-ee/react-calendar-timeline#182]
If you start dragging the timeline, leave the component, release the mouse and mouse enter the component, drag is still in effect.  This causes bad UX when dealing with modals (https://github.com/namespace-ee/react-calendar-timeline/issues/169) and in general when scrolling.

You can easily reproduce here:
https://codesandbox.io/s/x3ql17x204

If you start a drag, mouse leave the component while still holding down the mouse button, then mouse enter the component and release, it works as you would expect.

**Comment by Zhanadil1509** [comment]
I'm added onItemSelect
onItemSelect - need for project.
not worked onContextMenuClick, when i'm click (mousedown) to item and draggable, after click (mouseup) works onItemSelect. How to fix, that worked (onItemSelect) just on click, don't work on draggable and mouseup???

https://codesandbox.io/s/timeline-demo-working-example-forked-b7s03?file=/CustomTimeline.jsx
