### ISSUE TITLE
Timeline rendered in hidden DIVs will not display until browser resize

### ISSUE THREAD

**Issue by sabina4** [namespace-ee/react-calendar-timeline#184]
Hello,

I have a page with tabs if i put the timeline on the active tab on load, it shows perfectly.
However, if i put it on another tab then it doesn't display until browser resize.

![calendar_timeline1](https://user-images.githubusercontent.com/6688473/32769539-f963e522-c924-11e7-9c93-6904481b0bd9.JPG)

**Comment by mcMickJuice** [comment]
Hey @sabina4 could you reproduce this issue in codesandbox and share a link in this thread?

You can use this link as a starter:
https://codesandbox.io/s/x3ql17x204

Just the bare minimum to reproduce this issue and then we can help from there. Thanks!

**Comment by sabina4** [comment]
@mcMickJuice 
https://codesandbox.io/s/j3x50qk3r5

**Comment by mcMickJuice** [comment]
ah I see. Probably cuz display none is not allowing the canvas to know its width when it initially renders.

Can you implement the tabs NOT using display none to hide each tab (instead using a ternary to mount/unmount the component)?  That's the immediate solution and albeit not a very good one.

**Comment by sabina4** [comment]
i am using tabs of bootstrap hiding and showing tabs is done by changing activeTab so i can't rlly controle it

**Comment by mcMickJuice** [comment]
@sabina4 this is a temporary workaround:

https://codesandbox.io/s/vyxxx19x53

dispatch resize event on window when you toggle

**Comment by sabina4** [comment]
thanks!

**Comment by universezzz** [comment]
@mcMickJuice Thank you so much. You've saved me a lot of time.

**Comment by AdityaACE** [comment]
@mcMickJuice You're the best.
