### ISSUE TITLE
Hide the expand button when the group is empty

### ISSUE THREAD

**Issue by leizard** [namespace-ee/react-calendar-timeline#189]
Hi, thank you for great package. I enjoy using it.
Would it be possible not to display the [+] next to the group name when there is nothing in the tree (i.e. no items to display) ?

**Comment by mcMickJuice** [comment]
When looking at the tree demo, is that not how the current code works?

The tree view example is an illustration of how to achieve a tree view with this calendar, it's not something that's built into the library.  That being said, you have complete control over what's rendered in the group when constructing the `newGroups` collection in the example:

```jsx
 render () {
    const { groups, items, defaultTimeStart, defaultTimeEnd, openGroups } = this.state

    // hide (filter) the groups that are closed, for the rest, patch their "title" and add some callbacks or padding
    const newGroups = groups.filter(g => g.root || openGroups[g.parent]).map(group => {
      return Object.assign({}, group, {
        title: group.root ? (
          <div onClick={() => this.toggleGroup(parseInt(group.id))} style={{ cursor: 'pointer' }}>
{/* logic here to hide or show the plus or minus */}
            {openGroups[parseInt(group.id)] ? '[-]' : '[+]'} {group.title}
          </div>
        ) : (
          <div style={{paddingLeft: 20}}>
            {group.title}
          </div>
        )
      })
    })
```

Play around with that function and you should be able to achieve hiding the icon
