### ISSUE TITLE
Cannot find module "./Timeline.scss"

### ISSUE THREAD

**Issue by Janckk** [namespace-ee/react-calendar-timeline#19]
Hi guys,

any idea on what is going on here? Seems like the requires/imports are correctly used but I'm getting this webpack problem.

I'm using versions:

>  "babel": "^6.5.2",
>     "babel-core": "^6.8.0",
>     "babel-loader": "^6.2.4",
>     "babel-preset-es2015": "^6.6.0",
>     "babel-preset-react": "^6.5.0",
>     "css-loader": "^0.23.1",
>     "extract-text-webpack-plugin": "^1.0.1",
>     "interact.js": "^1.2.6",
>     "moment": "^2.13.0",
>     "node-sass": "^3.7.0",
>     "react": "^15.0.2",
>     "react-calendar-timeline": "^0.7.9",
>     "react-dom": "^15.0.2",
>     "sass-loader": "^3.2.0",
>     "style-loader": "^0.13.1",
>     "webpack": "^1.13.0",

    "webpack-dev-server": "^1.14.1"

**Comment by radziksh** [comment]
I think you should configure webpack.config.js, something like:

> module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style", "css", "sass"]
      }
    ]
  }
};

https://github.com/jtangelder/sass-loader

**Comment by mariusandra** [comment]
Hi, indeed even though you have "sass-loader" in your package.json, it appears your webpack is not configured to handle .scss files.

Closing this for now, feel free to reopen if there's a bug.

**Comment by nandito** [comment]
I have the same issue, I tried with many webpack configs, css/sass loaders but nothing helped.
If I comment out the `require('./Timeline.scss');` in the Timeline.js, and import the that scss manually in my webpack's stylesheet entry file, it works.

My webpack config (which works properly on each node_modules, except react-calendar-timeline):

```
module: {
      loaders: [
        {
          test: /\.s?css$/,
          loader: ExtractTextPlugin.extract( "css-loader!postcss-loader!sass-loader" )
        },
        {
          test: /\.s?css$/,
          include: /node_modules/,
          loaders: ['style-loader','css-loader', 'sass-loader']
        }
      ]
    }
```

**Comment by jmerriweather** [comment]
I use Brunch and get the following:
```
Cannot find module 'react-calendar-timeline/modules/lib/Timeline.scss' from 'react-calendar-timeline/modules/lib/Timeline.js'
```
