### ISSUE TITLE
Adding Left Column title tool tip

### ISSUE THREAD

**Issue by leizard** [namespace-ee/react-calendar-timeline#190]
Hi, sometimes the title in the left column is too long and we need to hover it to see all the content. How can we archive it ?
![image](https://user-images.githubusercontent.com/5291692/33309505-e6d11fce-d450-11e7-9429-fd961fb13c15.png)

**Comment by mcMickJuice** [comment]
You have control over what html is rendered in the sidebars using [groupRenderer](https://github.com/namespace-ee/react-calendar-timeline#grouprenderer).  The html that you render can have a `title` attribute, which gives you native hover/popover behavior. Or you can implement really anything you want to achieve popover functionality,

**Comment by mcMickJuice** [comment]
Example here using groupRenderer and HTMLElement.title attribute: https://codesandbox.io/s/n1w9vky250
