### ISSUE TITLE
"href" attribute on header "div"s

### ISSUE THREAD

**Issue by pfronczak** [namespace-ee/react-calendar-timeline#193]
Hi,

What is the purpose of the `href="#"` attribute on all header divs (see: [Header.js:142](https://github.com/namespace-ee/react-calendar-timeline/blob/92f779e87b82a9ff091fdf3e0af18b93da67955a/src/lib/layout/Header.js#L142))?
When using the Timeline component in a container which validates the DOM elements, this gives me a ton of warnings (since `href` attribute is not valid for `div` element: https://www.w3schools.com/tags/att_href.asp).
Would it be possible to remove it?

**Comment by mcMickJuice** [comment]
I have no clue why theres that attribute on the header div.  I'll be sure to remove for next release.

**Comment by mcMickJuice** [comment]
fixed with 0.15.5
