### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by maido155** [namespace-ee/react-calendar-timeline#196]
I have the following issue:

```
./~/react-calendar-timeline/src/lib/Timeline.js
Module parse failed: C:\Axity\lab\projects\lms\dev\lms-admin\node_modules\react-calendar-timeline\src\lib\Timeline.js Unexpected token (73:19)
You may need an appropriate loader to handle this file type.
|
| export default class ReactCalendarTimeline extends Component {
|   static propTypes = {
|     groups: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
|     items: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,

```
Can somebody help me?

**Comment by mcMickJuice** [comment]
Check out this [issue](https://github.com/namespace-ee/react-calendar-timeline/issues/148).

Alternatively, in your code, try importing the Timeline from the lib directory. From the docs:

```
// import Timeline from 'react-calendar-timeline'  // ESnext version
import Timeline from 'react-calendar-timeline/lib' // ES5 version
```

**Comment by baconprestosh** [comment]
Adding /lib cleared that error but now I have a different error that looks similar. 

`./~/react-calendar-timeline/lib/lib/Timeline.css
Module parse failed: /Users/jasonprestosh/response_project/node_modules/react-calendar-timeline/lib/lib/Timeline.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .react-calendar-timeline * {
|   box-sizing: border-box; }
|`

**Comment by mcMickJuice** [comment]
Are you using webpack? You will need to add a css-loader to the mix as this project imports css:

https://github.com/webpack-contrib/css-loader

Does that fix your issue?

**Comment by mcMickJuice** [comment]
Closing due to non-response. Let me know if you still haven't fixed this.
