### ISSUE TITLE
Item sometimes incorrectly changes its size after moving

### ISSUE THREAD

**Issue by roku66** [namespace-ee/react-calendar-timeline#197]
Steps to reproduce:
1. Start resizing an item, but at the end leave the previous size.
2. Move this item to another group.

The bug can be reproduced on the demo.

![peek 2017-12-15 17-15](https://user-images.githubusercontent.com/5857975/34048539-c2f1632e-e1bc-11e7-950f-88c1fd79cf5d.gif)

**Comment by vdmkotai** [comment]
looks like it's fixed now

**Comment by mcMickJuice** [comment]
yes, i believe this was fixed with https://github.com/namespace-ee/react-calendar-timeline/pull/174

Please let me know if thats not the case
