### ISSUE TITLE
Too long items for accuracy down to one second

### ISSUE THREAD

**Issue by lukasmartinelli** [namespace-ee/react-calendar-timeline#20]
I am having a timeline where I want accuracy down to one second. Somehow the timeline creates weird overlappings. I marked how it actually should be.

![selection_019](https://cloud.githubusercontent.com/assets/1288339/15007176/1e38313e-11d7-11e6-8a14-1761c0c6d093.png)

And this is the log when I click on these items and just output the start and end time.

1.Span [231] starting from 4/5/2016, 6:04:34 AM until 4/5/2016, 6:05:35 AM
2. Span [232] starting from 4/5/2016, 6:05:35 AM until 4/5/2016, 6:24:32 AM
3. Span [234] starting from 4/5/2016, 6:26:04 AM until 4/5/2016, 6:29:39 AM
4. Span [235] starting from 4/5/2016, 6:29:39 AM until 4/5/2016, 6:45:01 AM

**Comment by mariusandra** [comment]
Hey,

Could you build a codepen (or similar) that shows this issue?

It's easiest to just fork this one: http://codepen.io/mariusandra/pen/ONrQaX


Marius

**Comment by mariusandra** [comment]
Also, just guessing, perhaps it's the prop `dragSnap` that's causing issues?

**Comment by mariusandra** [comment]
@lukasmartinelli from the :+1: I assume the issue is fixed?

**Comment by lukasmartinelli** [comment]
> @lukasmartinelli from the  I assume the issue is fixed?

Sorry @mariusandra. I am pretty sure this will resolve the issues (since it is exactly the 15minutes interval)
The issue is I no longer have access to that codebase to fix it now (yes contract work is really weird sometimes 😁 ).

Thanks for the effort and tips.
