### ISSUE TITLE
Showing lines for every half hour

### ISSUE THREAD

**Issue by malindamiller** [namespace-ee/react-calendar-timeline#206]
I want to show lines on the grid for every half hour instead of every hour.  I don't want to zoom in anymore, though. Is this possible?

**Comment by mcMickJuice** [comment]
This is not currently possible given how the library works with units.  I believe that lines are drawn only for each unit that is displayed (e.g. hour, day, month, etc).  We currently don't have a half hour unit.

Not saying this won't be implemented at some point, just saying I don't believe this is possible with the current state of the library

**Comment by malindamiller** [comment]
Thank You!
