### ISSUE TITLE
using compoment instead string in 'title' of items.

### ISSUE THREAD

**Issue by radziksh** [namespace-ee/react-calendar-timeline#21]
In our project we need to use more complicate code then just string in 'title' of items. For example: several text input fields with 'cancel' and 'ok' buttons. Is it possible use component instead of string in 'title'?

**Comment by mariusandra** [comment]
Hi, it may be possible. Have you tried it?

The only issue I see is that the title is also passed as an actual `title` attribute to a `<div />`:

```jsx
      // Item.jsx
      <div ...
           title={this.itemTitle}>
        <div className='rct-item-overflow'>
          <div className='rct-item-content'>
            {this.itemTitle}
          </div>
        </div>
        ...
      </div>
```

I don't know how react handles components passed to the `title` attribute, thus it might need to be split into `itemTitle` and `itemContent`, while being backwards compatible.

Feel free to work on it and submit a PR if need be.

**Comment by radziksh** [comment]
yes, it's possible, for example, if I send this component to title instead of string then it will be rendered correctly:
 title: <TimelineItem reservationUnits={model.reservationUnits} availableUnits={model.availableUnits}/>,
