### ISSUE TITLE
Render background color for the visible group items

### ISSUE THREAD

**Issue by Cignite** [namespace-ee/react-calendar-timeline#213]
Hi,
I am trying to render background colors for the group items for a `visibleStartTime` and `visibleEndTime` but couldn't succeed. I looked into demo plugins `[demo-plugin](https://github.com/namespace-ee/react-calendar-timeline/blob/master/demo/app/demo-plugins/index.js)` and tried similar approach using Backgroundpainter but no luck. 

[Demo](https://lpln4jnm8m.codesandbox.io/)

<img width="1420" alt="screen shot 2018-01-13 at 16 24 55" src="https://user-images.githubusercontent.com/1145027/34906863-58bfb996-f87e-11e7-9c74-ec5e1612b02c.png">

When the visibleStartTime and visibleEndTime are changed then background doesn't change.

Desired result I am looking for. 

![itemrenderer](https://user-images.githubusercontent.com/1145027/34906510-c369473c-f877-11e7-8bf9-13404ef73cda.png)

Any pointers or help are greatly appreciated!

**Comment by echee** [comment]
did you manage to figure this out @Cignite ?
