### ISSUE TITLE
Cannot drag boxes on iOS devices

### ISSUE THREAD

**Issue by dboth** [namespace-ee/react-calendar-timeline#223]
Tested on iPad: As soon as an item is chosen and the drag starts there is an error in the console:

> [Error] TypeError: null is not an object (evaluating 'this.target._element')
> 	pointerDown
> 	(anonymous function)

After this the whole timeline is unresponsive.

**Comment by mcMickJuice** [comment]
Do you have a codesandbox example of this occurring?  Does this occur when working with the demos?

**Comment by jabidof** [comment]
I could test latest version on iPad A4 without any issue. Both dragging/resizing worked fine.

**Comment by mcMickJuice** [comment]
Closing due to lack of replication. Please reopen (or request to reopen) if you have a link to codesandbox where this error is occurring.
