### ISSUE TITLE
Rework how styling is handled in this library

### ISSUE THREAD

**Issue by mcMickJuice** [namespace-ee/react-calendar-timeline#224]
There are complications with build steps and including stylesheets and appropriate loaders when using this library.  I think that replacing the current css solution with a CSS in JS solution removes a lot of friction related to style.  I think we should strive for the following characteristics:

- completely remove css/sass in build
- provide default theme (same as current theme)
- allow extensibility through "themes".  This would supplant users providing their own css sheet targeting internal classes.
- have deprecation step so that users utilizing css overrides have time to transition over...or not?
- expose js in css api when using groupRenderer, item renderer etc (similar to material-ui)

**Comment by mcMickJuice** [comment]
I'd be looking at JSS as the library to use here: https://github.com/cssinjs/jss

**Comment by educastellano** [comment]
I think the CSS should be imported outside the component (already transpiled from SCSS to CSS), so the user can import it in whatever bundler is using:

```js
import Timeline from 'react-calendar-timeline'
import 'react-calendar-timeline/lib/Timeline.css'

ReactDOM.render(
  <Timeline />,
  document.getElementById('root')
);

```

**Comment by narmadham** [comment]
@mcMickJuice. That would be great. This will ease theme customization. When is v1.0 planned to be released?

**Comment by vasdee** [comment]
is this making it into the next release or available in the dev branch?

**Comment by mcMickJuice** [comment]
hey @vasdee i havent looked at this yet.  I can try to get it into the next release but I've lately been focusing on performance improvements.

**Comment by mcMickJuice** [comment]
Closing. Might address this once we do an API redesign.
