### ISSUE TITLE
Implement Ranges in Timeline

### ISSUE THREAD

**Issue by mcMickJuice** [namespace-ee/react-calendar-timeline#228]
Borrows from work mentioned here:

https://github.com/namespace-ee/react-calendar-timeline/issues/74#issuecomment-282667355

**Comment by florianbepunkt** [comment]
Does somebody know what's the status of the ranges feature? I read here somewhere that it should be converted into a plugin. Has this been done yet? If not is there a repo somewhere where I can jump in, maybe do a PR?

**Comment by mcMickJuice** [comment]
There's been no movement on this feature however I'm going to start on an approach soon that might replace the plugin system.  When I get around to it, I will post a roadmap issue and open things up for discussion.

**Comment by mcMickJuice** [comment]
This should be achievable via solution implemented in https://github.com/namespace-ee/react-calendar-timeline/issues/364

**Comment by mcMickJuice** [comment]
Released in 0.19.0
