### ISSUE TITLE
canvas double click fired on header

### ISSUE THREAD

**Issue by vasdee** [namespace-ee/react-calendar-timeline#236]
When you double click the header dates in the top bar, the onCanvasDoubleClick event fires and reports that the group is the first row. 

See the demo example here:
https://codesandbox.io/s/xjljp86z2q

The part (b) of this is that the docs describe the callback signature as onCanvasDoubleClick(groupId, time, e), however as seen in the example above, the groupId is actually the entire group object.

**Comment by mcMickJuice** [comment]
I just updated the readme to accurately portray what's returned.  Eventually I'll get around to updating all callbacks to receive the full object, not just the id

**Comment by mcMickJuice** [comment]
pushed in v0.15.9
