### ISSUE TITLE
items with no end_time

### ISSUE THREAD

**Issue by xiorcal** [namespace-ee/react-calendar-timeline#238]
Hello,

I'm trying to display items without end_time (ex very ponctual event like a push to git)

I get items well with setting the end_time to the start_time but items are not displayed (ie width =0), see screenshot 
![screenshot-2018-2-8_timeline](https://user-images.githubusercontent.com/2391639/35969730-19bdc996-0cc8-11e8-8321-3f84e051b5a2.png)

is it possible to specify a "default width" (to display at least the tilte of the item)

another way would be to change item end date to (start_time + a fraction of the "step" size) but it would require a change on every item evry time i zoom in or out.

**Comment by mcMickJuice** [comment]
Hmm...currently there is no way to specify default width.  The way the timeline is built is assuming an item has a duration (i.e. start date and end date) so what you're doing will, in the meantime, require you to hack around with enddate and update on zoom.

**Comment by xiorcal** [comment]
I found a ccs way to to what I want; I just have a problem with items stacking now.

now that I'm sure there is no native way to do it, i'll try hacking end_date on zoom.
thanks for answering! :)

**Comment by xiorcal** [comment]
finally came with a solution that suits my needs; i'll share for anyone interrested in:
```css
/*  enforce automatic size of items*/
.rct-item{
    width: auto !important;
    height: auto !important;
}
```

and set items end_date to a vvalue high enougth for items not stacking (I currently run with 2.5 days). Youy also need `stackItems={true}`

final render look like : 
![screenshot-2018-2-14 audience horus timeline](https://user-images.githubusercontent.com/2391639/36193264-81f6013a-1165-11e8-8150-0485d85d9d95.png)
