### ISSUE TITLE
Item gets timezone offset on dragging and resizing if timeline has dragSnap property.

### ISSUE THREAD

**Issue by xmityaz** [namespace-ee/react-calendar-timeline#24]
Reproducible link: http://codepen.io/xmityaz/pen/wGZRoq
To reproduce the issue try to slightly move one of the items (Item 2 and Item 3 are more obvious). It will start dragging process but at first will move/resize the item on timezone offset value (3 hours for Kiev) and just after on `dragSnap` value (1 day).

The issue occurs when the `dragSnap` property is set to Timeline and it isn't multiplier of timeZone offset value.
I guess the problem in `dragTimeSnap` function in Item.jsx (line 63). 
I've tried to fix it in the way bellow (changed dragTimeSnap function):
```
dragTimeSnap (dragTime) {
    if (this.props.dragSnap) {
      const offset = moment().utcOffset() * 60 * 1000;
      return Math.round(dragTime / this.props.dragSnap) * this.props.dragSnap - offset % this.props.dragSnap;
    } else {
      return dragTime
    }
  }
```

But it solves the issue just for moving an item. And introduces new issue for resizing:
For [this expamle](http://codepen.io/xmityaz/pen/wGZRoq) if you will try to resize Item 1 it will reset item time to 12 AM (instead of 6 AM in this case).

Could you please help to solve this issue if you'll have some time?
Any way, if I'll find a solution earlier I'll be back with PR :)

**Comment by mariusandra** [comment]
Thanks for the PR! I just released 0.8.2 with it!
