### ISSUE TITLE
Increase the heigh of the items

### ISSUE THREAD

**Issue by loaibassam** [namespace-ee/react-calendar-timeline#243]
How can I increase the padding / height of all rows? 

![screen shot 2018-02-11 at 21 59 05](https://user-images.githubusercontent.com/4785390/36079054-d0adb1ce-0f76-11e8-91c1-94fa75e3c713.png)

**Comment by lestgabo** [comment]
@loaibassam may I ask how you figured this out?

**Comment by loaibassam** [comment]
I don't think i have!
