### ISSUE TITLE
Support style for custom coloring

### ISSUE THREAD

**Issue by jacwright** [namespace-ee/react-calendar-timeline#244]
It would be helpful to support the `style` prop. `className` is very useful, but to allow the user to select custom colors for different events you need to be able to set style's `backgroundColor` and `borderColor`.

**Comment by mcMickJuice** [comment]
Does [itemRenderer](https://github.com/namespace-ee/react-calendar-timeline#itemrenderer) prop not support your use case?

**Comment by jacwright** [comment]
No, I don't think so. It only allows the content inside the bubble to be customized, not the bubble itself. At least, that's what it looked like in my testing. Am I wrong?

**Comment by mcMickJuice** [comment]
No, you are correct but you can achieve this through overriding the css classes and itemRenderer prop. left and right padding [is applied](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.scss#L147) to the Item, which is the container in which itemRenderer is rendered.  You'll need to play around with updating/overriding those styles and adding styling to the itemRenderer.

Styles in this library are inflexible and assume too much about use cases.  I created a placeholder story (https://github.com/namespace-ee/react-calendar-timeline/issues/224) to look at a more modern approach to handling styles but I am of the opinion that no styling related to padding or the like should be applied by default.

**Comment by jacwright** [comment]
I will try that out with css and itemRenderer.

**Comment by buddythumbs** [comment]
Hi, did this solve the issue you were having?

I don't know how to change styling in itemRenderer to apply my custom background color to entire item.
This is what I have:
![image](https://user-images.githubusercontent.com/24975408/41792231-649497fc-7658-11e8-9b04-df546153ad56.png)

My item renderer is a styled div:

```
const Item = styled.div`
  width: 100%;
  background-color: ${(props) => props.bg};
  padding-left: 0!important;
  padding-right: 0!important;
  margin-left: 0!important;
  margin-right: 0!important;
`
```
Then the item renderer function:

```
  itemRenderer = ({ item }) => {

     return  <Item bg={item.color}>
        <div >{item.title}</div>
      </Item>
  };
```

Any help here is greatly appreciated.

**Comment by mcMickJuice** [comment]
If you override `.rct-item-content` to remove padding, does that help?  Can you inspect the item element itself and identify _why_ this issue is happening?  I believe it's related to default padding applied.

**Comment by buddythumbs** [comment]
Hey,

I think I am making progress with this, I override `.rct-item-content` in the my main global.css and then just handle styles in the local renderer.

I'll report back when I feel I've got it nailed so others can see what works for me

**Comment by buddythumbs** [comment]
Hey - I just set the item that is rendered `display: block` and it fixed my issue here - thanks!
