### ISSUE TITLE
Date localization?

### ISSUE THREAD

**Issue by riflemanIm** [namespace-ee/react-calendar-timeline#245]
Hi,
Will there be a date localization in the header?
Is there a way to do it now?

**Comment by xiorcal** [comment]
I managed to do it; just import yout locale before rendering the timeline;

`import "moment/locale/fr"`

**Comment by mcMickJuice** [comment]
Closing as this seems like the solution.  Also refer to https://github.com/namespace-ee/react-calendar-timeline/issues/81 as another solution
