### ISSUE TITLE
wrong shift of items if there is external control

### ISSUE THREAD

**Issue by radziksh** [namespace-ee/react-calendar-timeline#25]
I created simple control for change visibleTimeStart and visibleTimeEnd via "previous" and "next" buttons with step of 7 days. updateScrollCanvas fuction works as expected, but there is strange shift of items in timeline. 
first state before click "next", items in 1-9 may
![screenshot_65](https://cloud.githubusercontent.com/assets/1275228/15294238/0b338c70-1b94-11e6-8565-0e0aac97a852.png)
second state after click "next", items in 8-16 may
![screenshot_66](https://cloud.githubusercontent.com/assets/1275228/15294243/110c348a-1b94-11e6-9a36-f460e6c8dab2.png)
Can you help me figure out why does it happen?
here is reproduction of defect, I tried to remove all not related code: https://github.com/radziksh/react-calenar-timeline-items-bug
if you need run it just do: 1) npm install 2) npm start

**Comment by radziksh** [comment]
Never mind. if you have this problem then it is just incorrectly configured components.

**Comment by jslatts** [comment]
@radziksh what did you have to fix to get rid of the shifting behavior? I am seeing the same thing but I don't see anything obviously wrong with the configuration.
