### ISSUE TITLE
How to set default day scale?

### ISSUE THREAD

**Issue by AlexSenchenko** [namespace-ee/react-calendar-timeline#250]
Hi 
Can anyone tell me how to setup default scale level by days, not by hours as default.

Thanks

**Comment by mcMickJuice** [comment]
Are you asking "how can i set the timeline to show days instead of hours"?  If so, try passing in a "wider" date range (i.e. one week or one month) into defaultTime* props:

https://github.com/namespace-ee/react-calendar-timeline#defaulttimestart-and-defaulttimeend
