### ISSUE TITLE
Uncompiled version

### ISSUE THREAD

**Issue by viestat** [namespace-ee/react-calendar-timeline#255]
I believe you should ship a compiled version of your code in your `npm package` since babel or other loaders don't run on anything inside node_modules unless explicitly configured to do so.

**Comment by mcMickJuice** [comment]
we do :)

https://github.com/namespace-ee/react-calendar-timeline#im-using-babel-with-rollup-or-webpack-2-and-im-getting-strange-bugs-with-click-events
