### ISSUE TITLE
Problems with rendering

### ISSUE THREAD

**Issue by viestat** [namespace-ee/react-calendar-timeline#256]
In my app I have tried the following using your [usage](https://github.com/namespace-ee/react-calendar-timeline#usage) example:

```js
import React, { Component } from 'react';
import Timeline from 'react-calendar-timeline';
import moment from 'moment';

const groups = [
  {id: 1, title: 'group 1'},
  {id: 2, title: 'group 2'}
];
 
const items = [
  {id: 1, group: 1, title: 'item 1', start_time: moment(), end_time: moment().add(1, 'hour')},
  {id: 2, group: 2, title: 'item 2', start_time: moment().add(-0.5, 'hour'), end_time: moment().add(0.5, 'hour')},
  {id: 3, group: 1, title: 'item 3', start_time: moment().add(2, 'hour'), end_time: moment().add(3, 'hour')}
];

class TestComponent extends Component {
  //...
  render() {
    return (
      <div>
        <Timeline
          groups={groups}
          items={items}
          defaultTimeStart={moment().add(-12, 'hour')}
          defaultTimeEnd={moment().add(12, 'hour')}
        />
      </div>
    );
  }
}

export default TestComponent;

```

but the output is wrong. It looks like this:

<img width="485" alt="screen shot 2018-03-04 at 10 21 01 pm" src="https://user-images.githubusercontent.com/9158996/36950712-7779c306-1ffa-11e8-94f1-1d94fbbad2c0.png">

**Comment by mcMickJuice** [comment]
whats your dev setup like? Are you using webpack? If so, how are you handling css files?

**Comment by mcMickJuice** [comment]
This issue is related to how you are handling styles in webpack:

https://github.com/namespace-ee/react-calendar-timeline/issues/72

**Comment by lucasasalmins** [comment]
@viestat did you get this working? I'm having the same issue
