### ISSUE TITLE
Increase sidebar row to fit content

### ISSUE THREAD

**Issue by loaibassam** [namespace-ee/react-calendar-timeline#257]
Is there a way to automatically increase the hight of rows to fit its content? so we won't have cropped content as below: 

![screen shot 2018-03-07 at 11 36 35](https://user-images.githubusercontent.com/4785390/37090342-ec2024c2-21fb-11e8-87e4-91c42a27be88.png)

**Comment by mcMickJuice** [comment]
It is not possible to automatically increase row size due to how the timeline works.

Your only option is to increase the lineheight prop
