### ISSUE TITLE
Build Issue with Webpack

### ISSUE THREAD

**Issue by sjarseneault** [namespace-ee/react-calendar-timeline#258]
Hello, 

I'm running into this issue whenever I run my web pack build script: 

> ERROR in ./node_modules/react-calendar-timeline/src/lib/Timeline.js
Module parse failed: Unexpected token (83:19)
You may need an appropriate loader to handle this file type.
|
| export default class ReactCalendarTimeline extends Component {
|   static propTypes = {
|     groups: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
|     items: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
 @ ./node_modules/react-calendar-timeline/src/index.js 1:0-37
 @ multi classnames interact.js jquery lodash moment react react-bootstrap react-bootstrap-typeahead react-calendar-timeline react-datepicker react-dom react-hot-loader react-notification-system react-onclickoutside react-redux react-redux-toastr react-router react-router-bootstrap react-select react-telephone-input redux redux-actions redux-logger redux-thunk toastrv

After sifting through the prior issues it seems closely related to [134](https://github.com/namespace-ee/react-calendar-timeline/issues/134). However, I tried everything mariusandra suggested.

Here is what my .babelrc looks like:
`{
  "presets": [ "env", "react", "es2015", "stage-0" ],
  "plugins": [
    "transform-class-properties",
    "react-hot-loader/babel",
    "transform-object-rest-spread"
  ]
}
`

Here's what is in my webpack.build.js file:
`test: /\.js$/,
                exclude: /node_modules(?!\/react-calendar-timeline)/,
                loader: 'babel-loader',
                options: {
                    "presets": [
                        "env",
                        "react",
                        "es2015",
                        "stage-0"
                    ]
                },`

I tried both stage-0 and stage-2 presets. I'm running the latest version of react-calendar-timeline (0.15.9), webpack version 3.10.0, and I've updated to the latest version of react, react-dom, moment, and interact.js.

Also I've tried using this switching to the lib import statement > importTimeline from 'react-calendar-timeline/lib' but with no luck. Any ideas? 

Aside from this issue great package!

Thank you,

**Comment by mcMickJuice** [comment]
How are you handling your styles?  Look to this issue to see if it fixes it:

https://github.com/namespace-ee/react-calendar-timeline/issues/72

You might need to configure how you handle styles.   Hopefully this helps.  This is a major pain point in this library because the timeline.js imports the css in the file.  That import should be something that the user code does, not the library.

**Comment by sjarseneault** [comment]
I'm already using both the style-loader and css-loader. I went ahead and updated to the latest, but still no luck.

**Comment by mcMickJuice** [comment]
What happens when you remove the options object from the babel-loader config?  It's possible that webpack is using that options object instead of your .babelrc.

So your loader config for babel in your webpack.config.js file should be

```
{ test: /\.js$/, 
  exclude: /node_modules(?!\/react-calendar-timeline)/, 
  loader: 'babel-loader', 
}
```

**Comment by sjarseneault** [comment]
I thought that was going to be it. I tried removing the options, but the error still persists.

Here is my entire webpack.build.js file which might reveal some clues:

`'use strict';

//you may need 'npm install' and
//npm rebuild node-sass

// export a function instead of a config object so we can get env.* parameters from the command line
module.exports = function (env) {

var path = require('path');
var fs = require('fs');
var _ = require('lodash');
var chalk = require('chalk');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var StatsPlugin = require('stats-webpack-plugin');
var WebpackBuildNotifier = require('webpack-build-notifier');
var ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
var ForkTsCheckerNotifierWebpackPlugin = require('fork-ts-checker-notifier-webpack-plugin');
var failPlugin = require('webpack-fail-plugin');
var uglyPlugin = require('uglifyjs-webpack-plugin');
var root = path.resolve(__dirname, '../../');

// load package.json and grab 'dependencies' to pre-load into common
var pkg = JSON.parse(fs.readFileSync(path.resolve(root, 'package.json')));
var vendor = Object.keys(pkg.dependencies).filter(function (i) { return i[0] != '@'; })

// ReSharper disable once InconsistentNaming
var defaultWebpackTarget = 'production';

// ReSharper disable once InconsistentNaming
var target = _resolveBuildTarget(defaultWebpackTarget);

// ReSharper disable once InconsistentNaming
function _chalkBoolean(b) {
    if (b === true || b === 'true' || b === '\"true\"') {
        return chalk.reset.green(b);
    }
    return chalk.reset.red(b);
}

// ReSharper disable once InconsistentNaming
function _printBuildInfo(target, params) {
    console.log(chalk.bold.cyan('\nStarting ') + chalk.bold.green('"' + target.toUpperCase() + '"') + chalk.bold.cyan(' build'));

    console.log(chalk.bold.cyan('\tcache: ') + _chalkBoolean(params.cache));
    console.log(chalk.bold.cyan('\tminimize: ') + _chalkBoolean(_.findIndex(pluginNameTuples, plugin => plugin.name === 'UglifyJsPlugin') !== -1));
    console.log('');
}

// ReSharper disable once InconsistentNaming
var pluginNameTuples = [
    {
        name: 'ProvidePlugin',
        plugin: new webpack.ProvidePlugin({
            React: 'React',
            react: 'React',
            'window.react': 'React',
            'window.React': 'React',
            _: 'lodash',
            'window._': 'lodash'

        })
    },
    {
        name: 'UglifyJsPlugin',
        plugin: target === defaultWebpackTarget
            ? new uglyPlugin() : null
    },
    {
        name: 'DefinePlugin',
        plugin: new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify(target)
            }
        })
    },
    {
        name: 'CommonsChunkPlugin',
        plugin: new webpack.optimize.CommonsChunkPlugin({
            name: 'common',
            minChunks: 2,
            path: root + '/Scripts/app/',
            filename: '[name].bundle.js'
        })
    }, 
    {
        name: 'AggressiveMergingPlugin',
        plugin: new webpack.optimize.AggressiveMergingPlugin()
    },
    {
        name: 'ExtractTextPlugin',
        plugin: new ExtractTextPlugin('../../Content/styles/[name].css')
    },
    {
        name: 'WebpackBuildNotifier',
        plugin: target !== defaultWebpackTarget
            ? new WebpackBuildNotifier({ title: 'Fusion Client Build', suppressSuccess: "always" /* let the ts-checker watcher tell us about success */ })
            : null
    },
    {
        name: 'NoErrorsPlugin',
        plugin: new webpack.NoEmitOnErrorsPlugin()
    },
    {
        name: 'ForkTsCheckerNotifierWebpackPlugin',
        plugin: target !== defaultWebpackTarget
            ? new ForkTsCheckerNotifierWebpackPlugin({ title: 'Fusion Client Build', alwaysNotify: true })
            : null
    },
    {
        name: 'ForkTsCheckerWebpackPlugin',
        plugin: new ForkTsCheckerWebpackPlugin()
    },
];

(function () {
    var webPackDebugRemoveIf = function (array, predicate) {
        var i = array.length;
        while (i--) {
            if (predicate(array[i], i)) {
                array.splice(i, 1);
            }
        }
    }

    webPackDebugRemoveIf(pluginNameTuples,
        function (item, index) {
            if (target === 'debug' && pluginNameTuples[index].name === 'UglifyJsPlugin') {
                console.log(chalk.bold.cyan('Webpack Plugin: ') + chalk.reset.red(pluginNameTuples[index].name + " OFF"));
                return true;
            } else {
                console.log(chalk.bold.cyan('Webpack Plugin: ') + chalk.reset.green(pluginNameTuples[index].name + " ON"));
            }
        });

    delete global.webPackDevRemoveIf;
})();

// ReSharper disable once InconsistentNaming
var webpackParamsDefault = {
    cache: true,

    entry: {
        common: vendor, // pre-load our third-party references into common (saves webpack the work of figuring out that they're shared)
        campus: root + '/client/campus/index.tsx',
        dashboard: root + '/client/dashboard/index.tsx',
        profile: root + '/client/profile/index.tsx',
        notifications: root + '/client/notifications/index.tsx',
        scheduler: root + '/client/scheduler/index.tsx',
        scheduling: root + '/client/scheduling/index.tsx',
        test: root + '/client/test/index.tsx',
        timesheets: root + '/client/timesheets/index.tsx'
    },

    target: 'web',

    output: {
        path: root + '/Scripts/app/',
        filename: '[name].bundle.js'
    },

    resolve: {
        modules: [path.resolve(__dirname, "../../client"), "node_modules"],
        extensions: ['.ts', '.tsx', '.js', '.jsx']
    },

    externals: {
        'react': 'React',
        'react-dom': 'ReactDOM',
        '_': 'lodash'
    },

    module: {
        noParse: [/^react$/, /^react-dom$/, /^lodash$/, /^jquery$/, /^moment$/, /^react-redux$/, /^redux$/],
        loaders: [
            {
                test: /\.ts(x?)$/,
                exclude: /node_modules(?!\/react-calendar-timeline)/,
                include: [
                    path.resolve(root, 'client')
                ],
                use: [
                    {
                        loader: 'cache-loader'
                    }, {
                        loader: 'thread-loader',
                        options: {
                            // there should be 1 cpu for the fork-ts-checker-webpack-plugin
                            // workers: require('os').cpus().length - 1,
                            workers: require('os').cpus().length - 1 // fastest build time for devServer: 3 threads; for production: 7 threads (os cpus minus 1)
                        }
                    }, {
                        loader: 'ts-loader',
                        options: {
                            // disable type checker - we will use it in fork plugin
                            transpileOnly: true,
                            happyPackMode: true
                        }
                    }
                ]
            }, {
                test: /\.js$/,
                exclude: /node_modules(?!\/react-calendar-timeline)/,
                loader: 'babel-loader', 
            }, {
                test: /\.css$/,
                loader: 'style-loader!css-loader'
            }, {
                include: /\.json$/,
                loaders: [ 'json-loader' ]
            }
        ]
    },
    
    plugins: pluginNameTuples.map(function(value, index, array) {
        return value.plugin;
    }).filter(function(value) { return value;  }),
};

// ReSharper disable once InconsistentNaming
var webpackParamsPerTarget = {

    development: {
        cache: false,

        // generate source maps for development
        devtool: '#eval-cheap-module-source-map',

        output: {
            // add source map locations
            sourceMapFilename: '[name].bundle.map',
            pathinfo: true
        }
    },

    debug: {
        cache: false,

        // generate source maps for development
        devtool: '#eval-cheap-module-source-map',

        output: {
            // add source map locations
            sourceMapFilename: '[name].bundle.map',
            pathinfo: true
        }
    }
};

// ReSharper disable once InconsistentNaming
var params = _.merge(webpackParamsDefault, webpackParamsPerTarget[target], _mergeArraysCustomizer);

_printBuildInfo(target, params);

return params;

// ReSharper disable once InconsistentNaming
function _resolveBuildTarget(defaultTarget) {
    var target = env.BUILDTYPE;
    if (!target) {
        console.log('No build target provided, using default target instead\n\n');
        target = defaultTarget;
    }
    return target;
}

// ReSharper disable once InconsistentNaming
function _mergeArraysCustomizer(a, b) {
    if (_.isArray(a)) {
        return a.concat(b);
    }
}


};`

**Comment by mcMickJuice** [comment]
Hm, thats a complicated webpack config :)

I'm sorry but I can't look through this config to see what you're doing wrong. This seems to be a problem with your combination of webpack + babel + typescript.  What I'd suggest is starting small, create a simple app with the webpack and babel config outlined in the above mentioned issues to see if the Timeline bundles correctly.

**Comment by sjarseneault** [comment]
Just FYI for anyone reading this, I added the  
```
 alias: {
            'react-calendar-timeline': 'react-calendar-timeline/lib',
        } 
```
to my resolve block again and it worked. I could have sworn I tried this multiple times....

Closing ticket.

**Comment by mcMickJuice** [comment]
thanks for providing that tip @sjarseneault !

**Comment by timoweiss** [comment]
@sjarseneault thanks for the pointer!

**Comment by ashinga48** [comment]
@sjarseneault  thanks, 
I'm using NextJS, so i tried this and it works

`import TimelineCalendar from 'react-calendar-timeline/lib';`

Saved hours for sure.
