### ISSUE TITLE
group and item donot match.

### ISSUE THREAD

**Issue by FridaCai** [namespace-ee/react-calendar-timeline#26]
![2016-05-17 10 50 20](https://cloud.githubusercontent.com/assets/12479174/15309872/4af538fc-1c1d-11e6-9b3a-49ed5bba66af.png)

const groups = [{
  id: "0_0",
  title: "A10-MY15",
  isSub: false
},{
  id: "1_0",
  title: "C140-MY13",
  isSub: false
},{
  id: "3",
  title: "pdtmeeting2",
  isSub: true
}];
const items = [{
  id: "task_0",
  group: "0_0",
  title: "task of A10-MY15",
  start_time: 1462250677000,
  end_time: 1462250716000
},{
  id: "task_4",
  group: "1_0",
  title: "task of C140-MY13",
  start_time: 1462250677000,
  end_time: 1462250716000
},{
  id: "task_1",
  group: "3", 
  title: "task of pdtmeeting2",
  start_time: 1462250677000,
  end_time: 1462250716000
}];
ReactDOM.render(
  <div>
    Rendered by react!
    <Timeline groups={groups}
              items={items}
              defaultTimeStart={moment().add(-12, 'hour')}
              defaultTimeEnd={moment().add(12, 'hour')}
              stackItems={true}
              />
  </div>,
  document.getElementById('domContainer')
);

**Comment by FridaCai** [comment]
The problem may be caused by items.jsx/function render/sortedDimensionItems.
items will be sorted according to id. seems by design but not make sense in my sense.
anyway, good component!!! thank you so much!!!

**Comment by FridaCai** [comment]
I fix it in this way. it works for me and no new issue found so far  :)

if (force) {
    // reset top position of all items
    for (i = 0, iMax = items.length; i < iMax; i++) {
      items[i].dimensions.top = null
    }
  }

_**var sortArr = (function sortItemByGroupOrder(_groupOrders){
  //create arr. each element is obj{key:'', value:''}
  var tmpArr = [];
  
  for(var key in _groupOrders) {
    var value = _groupOrders[key];
    tmpArr.push({key: key, value: value});
  }

  tmpArr.sort(function(obj1, obj2){
    return obj1.value - obj2.value;
  })

  return tmpArr;
})(groupOrders);


for(var index = 0; index < sortArr.length; index ++ ){
    var key = sortArr[index].value;**_
    var group = groupedItems[key] || []

**Comment by JK82** [comment]
Hey, I'm having this issue also but I don't quite understand your solution. Can you elaborate a little? Thanks

**Comment by JK82** [comment]
Hi, I'm having the same issue. Can you elaborate on your code or post the rest? Thanks

**Comment by FridaCai** [comment]
Hi JK82, I add some code in timeline/lib/utils.js

if (force) {
    // reset top position of all items
    for (i = 0, iMax = items.length; i < iMax; i++) {
      items[i].dimensions.top = null
    }
  }

var sortArr = (function sortItemByGroupOrder(_groupOrders){
  //create arr. each element is obj{key:'', value:''}
  var tmpArr = [];

  for(var key in _groupOrders) {
    var value = _groupOrders[key];
    tmpArr.push({key: key, value: value});
  }

  tmpArr.sort(function(obj1, obj2){
    return obj1.value - obj2.value;
  })

  return tmpArr;
})(groupOrders);


for(var index = 0; index < sortArr.length; index ++ ){
    var key = sortArr[index].value;
    var group = groupedItems[key] || []
