### ISSUE TITLE
item vertical align issue.

### ISSUE THREAD

**Issue by FridaCai** [namespace-ee/react-calendar-timeline#27]
please refer to the image.
when set stackItems=true,and times collide, item vertical issue appears. some are middle align while others are bottom align.

![2016-05-17 10 54 34](https://cloud.githubusercontent.com/assets/12479174/15309929/e3326cc0-1c1d-11e6-9d02-b474ae27d3b0.png)

**Comment by mariusandra** [comment]
Hey, very weird. Could you show some code for this case?
It's easiest to fork this codepen: http://codepen.io/mariusandra/pen/ONrQaX

**Comment by mariusandra** [comment]
I tried and couldn't replicate, plus this issue has been inactive for months. Closing. Please reopen if needed.
