### ISSUE TITLE
Comment on documentation

### ISSUE THREAD

**Issue by AdamFreemer** [namespace-ee/react-calendar-timeline#270]
While trying to add coloring, I was using the doc to override the indicated classes. 

```
.react-calendar-timeline .rct-items .rct-item.analysis {
  backgroundColor: #68efad;
}
```

I'm new to react, but my solution ended up adding the override to a component css file where the standard css `background-color` class worked instead. 

```
.react-calendar-timeline .rct-items .rct-item.analysis {
  background-color: #68efad;
}
```

Perhaps there's a better way to override css I can learn about? That aside, thanks so much guys for this library, it's awesome++

**Comment by mcMickJuice** [comment]
Documentation updated! - https://github.com/namespace-ee/react-calendar-timeline/commit/b4d3c6f1f62a76ede89f3a28bc5d932f2bb04f29

Thanks for pointing this out.  In the documentation, there was a typo, as you figured out. In react, inline styles are objects with css properties as camelCase [react docs](https://reactjs.org/docs/dom-elements.html#style).  However, in css, these properties on kebob-cased.  Sorry for the confusion
