### ISSUE TITLE
Vertical calendar timeline?

### ISSUE THREAD

**Issue by hiddenl00p** [namespace-ee/react-calendar-timeline#28]
Great work! I need to display events on the vertical timeline. Is something similar on the roadmap?

Any plan to use [react-dnd](https://github.com/gaearon/react-dnd) for drag and drop?

**Comment by mariusandra** [comment]
Hey!
There are no plans to build a vertical timeline component at this moment. However if you manage to get it working like that, feel free to submit a PR.
About react-dnd, you mean to replace interact.js? Or even to have the option to drag from one timeline component to another? In any case, the same goes here - feel free to send a PR :)

**Comment by antoshigas** [comment]
I need this :D
