### ISSUE TITLE
Shift+Scroll doesn't scroll the timeline canvas horizontally on Mac

### ISSUE THREAD

**Issue by amakhrov** [namespace-ee/react-calendar-timeline#281]
Reproducible on the demo: https://namespace-ee.github.io/react-calendar-timeline-docs/#/main

- I have an external mouse. When I hold Shift and scroll the wheel, the Timeline doesn't scroll, simply nothing happens.
- However, when I use the touchpad, two-fingers swipe up/down while holding Shift DOES scroll the timeline horizontally.

**Comment by mcMickJuice** [comment]
released in v0.15.12.

Thanks @amakhrov !
