### ISSUE TITLE
inline ref callbacks

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#291]
Hi,

I noticed some inline ref callbacks to get references to the DOM element in the library codebase, which is causing a small performance hit. [Please refer to the react documentation about this](https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs). I thought maybe I should mention so if anyone has time can go over the project and fix it.

**Comment by mcMickJuice** [comment]
Thanks for noting this.  

At this point I don't want to do any changes regarding refs unless it can be proved that these inline refs are a performance bottleneck.  The main performance bottlenecks in this library are massive repaints (when there are a ton of items in the timeline) and repeatedly calling setState/renders when the user is interacting with the timeline (usually during scroll)
