### ISSUE TITLE
Add ability to capture Mouse Down/UP events on Canvas

### ISSUE THREAD

**Issue by morsh** [namespace-ee/react-calendar-timeline#293]
This is to enable the ability to define a time range.
Alternatively - expose a onCanvasTimerange.

This scenario is necessary if I want to enable my users to select a timerange on the canvas, then create a new activity on that time range.

If this feature is acceptable, I'd be happy to work on it.

**Comment by mcMickJuice** [comment]
hi @morsh thanks for this idea.  I believe this would interfere with canvas drag:

* mousedown + drag scrolls the canvas
* mouse up releases drag

im not sure how to allow for this and not irritate 99% of users

**Comment by morsh** [comment]
Might this be doable on drag-disabled Timelines?
That means a Timeline that's controlled by visisble time start/end.

**Comment by mcMickJuice** [comment]
I'm sorry but this seems like to specific of a use case to your specific need to introduce to this library.  Managing when and how to fire those events would complicate the codebase for something that not everyone is going to use.

I'm going to close this issue.  If you feel strongly that this should be in the library, please feel free to fork the repo and get a working example going.  If there are enough users that are behind implementing this in the library we can look at implementing it then.

**Comment by mcMickJuice** [comment]
Editing or adding items isn't too specific a use case, but doing it using a gesture of clicking and dragging on the timeline but only when the timeline is locked is pretty specific.

It's possible I don't fully understand what you want here, which means that I'll need to see it in code. Feel free to fork and submit a PR but I can't make any promises that it will be added.  The API of this library is already way too loose IMO. Introducing yet another handler will make it more so.  Maybe after a major refactor of this library's structure will allow for you to implement this in your code (without augmenting the library api).
