### ISSUE TITLE
All .rtc-header DOM elements disappear when dragging .rtc-header .rct-label really fast

### ISSUE THREAD

**Issue by dejv88** [namespace-ee/react-calendar-timeline#3]
When you drag .rtc-header .rct-label really fast, it bugs and removes all elements in .rtc-header.

I suggest to disable dragging when clicking on .rtc-header .rct-label. Not only does it triggers a drag in timeline, but it also clicks you to the subcategory.

Before fast drag over day numbers:
![image](https://cloud.githubusercontent.com/assets/4254731/13853784/ae8456ee-ec68-11e5-9c18-3e742295c34c.png)
After the fast drag:
![image](https://cloud.githubusercontent.com/assets/4254731/13853820/de359c4a-ec68-11e5-9f47-0a04cef7f460.png)

**Comment by mariusandra** [comment]
Thank you for reporting this!
Would you be willing to submit a PR with a fix?

**Comment by dejv88** [comment]
Unfortunately I'm not a React developer. I only use this widget (it is awesome btw :) ) in HTML + JS :(

**Comment by mariusandra** [comment]
OK :). Then it will take some time before I'm able to fix these bugs. I'll try to find time by Monday.

**Comment by dejv88** [comment]
Absolutely no problem. Thank you very much!

**Comment by mariusandra** [comment]
Hey, I released 0.7.3 that fixes this issue. Thanks again for reporting!
