### ISSUE TITLE
OnMove gives NAN for new starttime

### ISSUE THREAD

**Issue by forki** [namespace-ee/react-calendar-timeline#300]
If you use date as values for item starttime and item endtime, then OnItemMove will give you NaN as result for the new start time.

If you pass unix timestamps then things work.

**Comment by gachavez** [comment]
I ran into a similar issue. 

- Used a Date object for starttime and endttime. 
- onCanvasClick was returning a Nan. 

Solved with using unix timestamps in milliseconds for starttime and endttime

**Comment by mcMickJuice** [comment]
I feel like this timeline should only support unix timestamps in ms as the input.  marshaling between strings, Date object, Moment and milliseconds is a pain.

**Comment by jabidof** [comment]
Simplify, simplify and simplify!
Fully agree.

**Comment by mcMickJuice** [comment]
Fixed in 0.17.0
