### ISSUE TITLE
cut extra renders for performance

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#303]
Hi, 

I ran a react optimization tool called [why-did-you-update](https://github.com/garbles/why-did-you-update) to find reasons why items render on every little interaction when they shouldn't. This tool runs deep equality for the changing props and state to figure out where props or state differ in reference but not in content. I discovered hundreds of extra render and cutting them is not very hard to fix. Fixes mostly are just changing some components to pure components or prevent `next state` with deep equality to set the upper-level component's state which causes the whole component to rerender.

![pref](https://user-images.githubusercontent.com/10817089/39687568-b301d788-51d7-11e8-90e9-ea60342ee861.gif)

**Comment by mcMickJuice** [comment]
hi @Ilaiwi ill try to review this stuff this week or next. I'm really slammed at work 😄
