### ISSUE TITLE
dynamically changing the groups cases an error with drag and drop items

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#305]
Hi, 

I had a bug where when I change the groups dynamically using some filter and chose groups that do not have sequential order cause a drag and drop fail. It also causes an error when trying to move another item from the dropped to group. 

I guess the problem is with the item [`group order`](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L1100) where it needs to be recalculated when changing groups

[**Sandbox**](https://codesandbox.io/s/q38p62m399)

![bug](https://user-images.githubusercontent.com/10817089/39694085-b78a49e0-51ee-11e8-9d83-dd308fa36f6e.gif)

**Comment by Ilaiwi** [comment]
My bad. I investigated the code and problem was with my code. I should've selected the dropped group from filtered groups and not from groups.

**Comment by mcMickJuice** [comment]
Phew! I wasn't looking forward to fixing this bug :)

**Comment by Ilaiwi** [comment]
false alarm 😅
