### ISSUE TITLE
onCanvasClick does not match cursor line

### ISSUE THREAD

**Issue by hotyhuang** [namespace-ee/react-calendar-timeline#306]
Hi guys,

This should be a performance issue. So basically I want to work with both `showCursorLine` and `onCanvasClick`, leave `dragSnap` as default which is 15 min. I suppose the click event will pass me the 15 min time slot, where the cursorLine is at. But it loses some accuracy here.

Left Click:
![22:45](https://cdn1.imggmi.com/uploads/2018/5/8/d16cd68fa28803919c320e2a651d6eb2-full.png)

Right Click:
![23:00](https://cdn1.imggmi.com/uploads/2018/5/8/65c06525e56c1e105b83a023d2281a3a-full.png)

Notice in both images, cursor line is in same position, but clicks differ.
You can refer to the Sandbox here: https://codesandbox.io/s/lx1l98xpl9
The issue will be more apparent when run in local server. Let me know if you need one to test, I just don't have time to create one repo right now...

**Comment by mcMickJuice** [comment]
Hi @hotyhuang so you expect the time reported with the canvas click to match the cursor line. Or more explicitly, you expect the time reported on canvas click to respect dragSnap?

**Comment by hotyhuang** [comment]
Hi @mcMickJuice I expect it to match the cursor line. Otherwise people who use it may get confused, he thought he is clicking at the cursor line, but we are catching a different time.

**Comment by mcMickJuice** [comment]
I'm not sure that we would want to do this:

* the cursor line is not on by default, you need to opt in
* im assuming cursor line is determine by dragSnap.  If it is, there will be scenarios where some users expect the canvas time reported to be as accurate as possible (exactly where you click) and some who expect it to work like you're describing
* I think that users can account for this by rounding down or up based on drag snap

I guess my point is, it's hard to appease everyone with this change so I think we should keep it as specific as possible.  Thoughts?

**Comment by hotyhuang** [comment]
Hi @mcMickJuice I get it that people may expect differently at this point, but I still prefer if cursor line can match drag snap.
So if it is not something you are going to implement, right now I am creating a `CustomTimeline` component to extend react-calendar-timeline, overwriting some functions to meet my needs. Where is the best place to make this change (onCanvasClick return cursor line position)?

**Comment by mcMickJuice** [comment]
I take "Performance" to mean rendering performance such as frame rate, cpu usage etc, not how the timeline functions

You can start by looking at https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L800

That's where cursorPosition is determined.  Canvas time is determined here: https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L646

Looking at how CursorLine and TodayLine are implemented, I think I want to factor those out so that their existence doesn't cause a re-render of the entire timeline on hover.  What if the cursor line didn't respect dragSnap and ALWAYS matched where your mouse cursor is?  What are the arguments for the CursorLine respecting drag snap?

**Comment by andy-dorman** [comment]
It sounds to me like canvasClck position and cursorLine position are distinctly different things but it would be useful to be able to know where the cursor is or be able to set/store it’s position.

I’m quickly getting to the point of wanting to work with time regions and left and right locators - audio app style. It sounds like CursorLine and TodayLine could take some abstraction and we could implement LeftLocator and RightLocator usually similar components and logic? Possibly you could the. pass a locator position object with some of the click/move/resize events in a similar way to the edge object?

Sorry for hijacking this issue - it’s become less related the more I type!!! I’ll put something together during the week and see what you think.

Great component by the way, it’s really giving me a huge head start with some work I’m currently doing.

**Comment by mcMickJuice** [comment]
@hotyhuang I'm going to close this issue as I don't want to align time in canvas click with cursor line.  Moreover, the user can accomplish this in the onCanvasClick function by rounding based on dragSnap.

@andy-dorman I'd be interested in what you're thinking.

**Comment by andy-dorman** [comment]
@mcMickJuice Basically there are a couple of things I'd like to be able to do.

1. To be able to drop "markers" on to the timeline which would render as a "timeline marker", pretty much like the "Today line" marker works at the moment. I'd be more than happy to handle these outside of the component itself, but if I could build an array of "markers" with corresponding time properties I could do things like set up "ctrl-[NUMBER]" key commands to jump directly to points in the timeline. I suggesting you essentially abstract out the "Today line" marker that gets set when the component initialises so you can create such markers programatically, suing them pretty much like bookmarks. So for example, I've already set it up so double clicking on the canvas creates a new item at that point in time, I'd like to be able to create a new "marker" in the same way. Ideally you'd be able to bypass the snapping configuration in many of the use-cases for this stuff, but sometimes you wouldn't, so passing both the rounded values and the actual values would be good.

2. What I **really** want to be able to do is to click and drag on the canvas to highlight a region of time. onCanvasClick could expose, and probably does already - I forget to be honest, which you could use to drop a marker at that point. If on release or stopDrag or whatever exposed the time that related to the mouse position at that point I could probably hack together some kind of region highlighting interface. I'm really taking this in the direction of audio or video editing applications, which is possibly outside of what you originally intended, but it's **so** close it would be a shame not to add the functionality. Obviously (?!) you'd also want (might want?) any items in the now defined region to become selected but to be honest as long as you've got some kind of reference to the left and right boundaries of the region you've just dragged across there's no real need for any of that to be any concern of this component at all.

The kind of functionality I'm looking for is...

1. Select a region of the timeline
2. Have any items in that region be selected
3. Be able to set the left or right boundaries of any selected items to the left or right boundary of the region.

I've already managed to select multiple items and set the left or right boundaries of all the selected items to the left-most or right-most value in the selected set, this is really just a continuation of that.

I hope you understand what I'm getting at!!! It's a lot easier to visualise than to explain...

On a totally unrelated note, I'd also really like to be able to change the time format into something like SMPTE format so I could use this as an interface to arrange closed captioning entries against a piece of video that I would display on the same page. Moving back and forth in the video would move the timeline back and forth at the same time - but that really is a different conversation.

Ultimately the use cases I have are really for something that requires a straight up "time based" view of data, however it is you choose to define or divide up the time you're interested in - it would be great to be able to handle months and years as easily as seconds and vide frames. But anyway, one step at a time!!!

**Comment by vasdee** [comment]
@andy-dorman I am actually after the same things, canvas select region is definitely a high priority for me. The marker drop I didn't even realise I needed until you mentioned it. Definitely worth creating some seperate feature request issues for these.

**Comment by mcMickJuice** [comment]
Agree. @andy-dorman would you mind creating issues for each of these things?  Feel free to just copy and paste.

**Comment by andy-dorman** [comment]
Ok I’ve created three issues, I managed to fudge the title of the first from my phone, @mcMickJuice you can delete and recreate if you’d like!!
