### ISSUE TITLE
Item Drag is off after Drag

### ISSUE THREAD

**Issue by LitvinaviciusM** [namespace-ee/react-calendar-timeline#310]
![dnd-bug](https://user-images.githubusercontent.com/29225557/39909244-a53692c6-54fa-11e8-85b8-595a944e73e3.gif)
Hey guys, 
thanks for great timeline.
I faced the problem and I don't really know where it is...
Any suggestions?
Here is my render method of timeline

`  render() {
    const { items, groups } = this.state;

    return (
      <ReactCalendarTimeline
        { ...defaultSettings }
        headerRef={this.handleHeaderRef}
        items={items}
        groups={groups}
        defaultTimeStart={moment().add(-12, 'hour')}
        defaultTimeEnd={moment().add(12, 'hour')}
        groupRenderer={GroupRenderer}
        itemRenderer={EventRenderer}
        ref={(timeline) => {
          this.timeline = timeline;
        }}
        onItemMove={this.openDialogOnMove.bind(this)}
        onItemResize={this.openDialogOnResize.bind(this)}
        onItemDoubleClick={this.onItemDoubleClick.bind(this)}
        {...this.props}
        itemTouchSendsClick={false}
      />
    )
  }`

Default settings:

`const defaultSettings = {
  sidebarWidth: 180,
  lineHeight: 54,
  headerLabelGroupHeight: 32,
  headerLabelHeight: 28,
    itemHeightRatio: 0.75,
    timeSteps: {
      hour: 1,
      day: 1,
      month: 1,
      year: 1
    },
    keys: {
      groupIdKey: 'id',
      groupTitleKey: 'name',
      groupRightTitleKey: 'rightTitle',
      itemIdKey: 'id',
      itemTitleKey: 'title',
      itemDivTitleKey: 'title',
      itemGroupKey: 'instructor',
      itemTimeStartKey: 'timeFrom',
      itemTimeEndKey: 'timeTo'
    },
    defaultHeaderLabelFormats: {
      ...defaultHeaderLabelFormat,
      hourLong: 'dddd, HH:00',
      dayLong: 'dddd, DD MMM',
      monthLong: 'MMMM YYYY',
      yearLong: 'YYYY'
    },
    defaultSubHeaderLabelFormats,
  };`

Item renderer:

`const EventRenderer = ({ item }) => {
  return (
    <div  id={item.id}>
      { item.eventType === 'individual' &&
        <IndividualEvent
          event={item}
        />
      }
      { item.eventType === 'group' &&
        <GroupEvent
          onOpen={item.onOpen}
          event={item}
        />
      }
      { item.eventType === 'availability' &&
        <AvailabilityEvent
          event={item}
        />
      }
    </div>
  )
};`

Group renderer:

`const GroupRenderer = ({ group }) => {
  return (
    <div className="group">
      <span
        className="title"
        style={{cursor: 'pointer'}}
        onClick={() => { group.role === 'manager' && group.onClick(group.id) }}
      >
        {group.name + ` ` + group.surname}
      </span>
    </div>
  )
};`

**Comment by mcMickJuice** [comment]
Hi, can you create a minimal reproducible example of this, either using one of the examples (i.e. https://codesandbox.io/s/lyjr9p0119) or a github repo?  It's a lot easier to troubleshoot if there is working code instead of a screenshot.

BTW thats a nice look app you got there :)

**Comment by vasdee** [comment]
I've seen this happen when there is dynamic content above the timeline that pushes the canvas out of whack. 

I would suggest trying the resizeDetector first and see if that fixes it, then issuing a resize event manually eg `window.dispatchEvent(new Event('resize'));`

The second one is a dodgy workaround but sometimes works for me. I'll probably look at a more sustainable fix once I get a bit more familiar with the internals
