### ISSUE TITLE
.rct-header has a bounce effect

### ISSUE THREAD

**Issue by florianbepunkt** [namespace-ee/react-calendar-timeline#311]
Thanks for creating an issue! Please fill out the sections below so that we can accommodate your request:

**What kind of issue are you experiencing?**

* [x] Bug

**Actual Behavior**:
When I used 0.15.5 the header scrolled along the timeline. Now with version 0.16.1 there is this bounce effect know from apple/safari/iphone, which produces some bad UX. 

**Steps to reproduce the issue**:

limit scroll of timeline to a fixed range, for example from today 0:00 untill tomorrow 0:00 . zoom into timeline and scroll to start or end (I'm using a touchpad on macbook). the timeline events scroll normally, but the header (rct-header) "overshoots" the end and bounces back (see screenshot attached)

**Versions**:

0.15.5

**Additional Information**:

Chrome,  66.0.3359.139, OS X

![ezgif-4-e2b42d1334](https://user-images.githubusercontent.com/8314202/39957122-9835dc28-55ed-11e8-984e-84a25eb08828.gif)

**EDIT: Simple Repro to see the effect is here: https://codesandbox.io/s/lx52v97507
I just added a scroll limiting method to onTimeChange**

**Comment by florianbepunkt** [comment]
Sure… I can give it a try

**Comment by Ilaiwi** [comment]
Hi @mcMickJuice this is blocking me at the moment. Could you please give me some pointers on how to solve this?

**Comment by florianbepunkt** [comment]
@mcMickJuice Also interested…

**Comment by mcMickJuice** [comment]
Related issue - https://github.com/namespace-ee/react-calendar-timeline/issues/357

**Comment by Ilaiwi** [comment]
@mcMickJuice I havent found any workaround for this yet so I think I am going to tackle it later this week

**Comment by Ilaiwi** [comment]
Hi, I was trying to solve this bug and I found out that the problem in my app was from a timeline plugin I wrote. Sorry, but I am not going to continue with this bug since the problem doesn't affect me anymore. For anyone who is interested in the future, I solved it by applying `oveflow: auto` on my plugin divs.

**Comment by florianbepunkt** [comment]
@Ilaiwi Interesting, I also had a timeline plugin activated. However even when I disabled all timeline plugins completely the bug still occurs as well as when applying css overflow property as you suggested.

**Comment by Ilaiwi** [comment]
@florianbepunkt in my application the plugin was responsible for some customized drag and drop behavior. This bug appeared for me when I was dragging the item close to the edges so after researching that the solution was for me is to do `overflow: auto`. This was a very specific case. I also have mouse dragging disabled on the timeline so it is very rare for this bug to appear for me.

**Comment by Ilaiwi** [comment]
I think I can solve this after finishing #349. For now, my new headers bounce because of `canvasTimeStart` and `canvasTimeEnd` change where they shouldn't, because of the limit enforced by `onTimeChange`

**Comment by Ilaiwi** [comment]
this is solved in 0.20.0
