### ISSUE TITLE
add react-calendar-timeline.d.ts in npm package.

### ISSUE THREAD

**Issue by radziksh** [namespace-ee/react-calendar-timeline#32]
Hi, I created definitions for react-calendar-timeline https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react-calendar-timeline but  there are changes in typescript compiler. Now the compiler automatically resolves definitions by "typings" field in package.json.
it's explained in https://github.com/DefinitelyTyped/tsd/issues/269  and in  http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html.
Main idea: Typescript user doesn't need to install tsd or typings for use react-calendar-timeline's definitions. He can just type: "npm install react-calendar-timeline" and immediately start to use it in typescript. I would like to do PR for it. There will be just react-calendar-timeline.d.ts file whenever you want and "typings" field in package.json. But before I start I want to ask the question: will my PR be accepted?

**Comment by mariusandra** [comment]
Hey!

If you submit a PR and I will accept it!

However, how can we keep the definitions in sync when something changes with the component? For example, [many functions](https://github.com/namespace-ee/react-calendar-timeline/commit/e47afa2106ec76af05f496139a4ef60cd4042bf9) recently changed their arguments.

I don't use TypeScript myself, but the format seems easy enough to be updated. Anything special to know with it?

**Comment by radziksh** [comment]
ok, then I'll do PR for the updated timeline. 

> I don't use TypeScript myself, but the format seems easy enough to be updated. Anything special to know with it?

No, there is really nothing special. In fact typescript is not even a single language. It's just ECMA6 javascript + static types checking (in console or in IDE). It can be compiled to ECMA5 (or still can be ECMA6). It works well with React and Webpack. When the project grows to a large size it saves a lot of time. And you can write a much smaller amount of tests because static type checking partially replaces some tests. Recommend to try it :)

here some info about definition for TS: http://definitelytyped.org/guides/best-practices.html
