### ISSUE TITLE
Enable alternative time formats

### ISSUE THREAD

**Issue by andy-dorman** [namespace-ee/react-calendar-timeline#329]
I would like to be able to change the time format into SMPTE for instance so I could use this as an interface to arrange closed captioning entries against a piece of video that I would display on the same page.

Fortunately things like this exist:

https://www.npmjs.com/package/smpte-timecode

So I don’t think this necessarily has to be hugely complicated.

**Comment by mcMickJuice** [comment]
This can't be accomplished via this config - https://github.com/namespace-ee/react-calendar-timeline#headerlabelformats-and-subheaderlabelformats

Probably wanna change this config to a function that the user provides.

**Comment by mcMickJuice** [comment]
@andy-dorman have you tried to achieve this using the header/subheader formats?

**Comment by andy-dorman** [comment]
I haven’t, let me try this afternoon and you can close this off.

**Comment by andy-dorman** [comment]
I’ve still not had a proper look at this but I can’t immediately see how those label configurations will help? I need to specify a unit smaller than seconds, frames, and I don’t think specifying a unit of ‘FF’ will be understood by the intervals of the package which I think uses moment?

Fundamentally, it would be nice to be able to specify a date/time library other than moment and have all time values handled by that instead. So new time positions returned by item drags for example would specify a frame value in the returned time.

**Comment by mcMickJuice** [comment]
OK. Just wondering if this could be accomplished by existing code.

Regarding your second point, there's [this issue](https://github.com/namespace-ee/react-calendar-timeline/issues/320) for looking into other date libraries. Also, [this issue](https://github.com/namespace-ee/react-calendar-timeline/issues/321) for the library accepting and returning unix timestamps.

Your specific issue is separate from those but related.

**Comment by yftachman** [comment]
Hey guys, in my opinion this library should let the user have full control of each element it renders.
Just like itemRenderer or GroupRenderer, a headerLabelRenderer and a headerLabelGroupRenderer would be super useful for those of us who want to fully customize the way our timeline looks.

In regards to the original post, this will enable you to basically do whatever you want, including passing it to a separate library and displaying it as you wish.

**Comment by mcMickJuice** [comment]
That's the main goal of future development on this project :smile:

**Comment by Ilaiwi** [comment]
this will be possible after #391

**Comment by Ilaiwi** [comment]
This will be possible via the `formatLabel` prop in `DateHeader`

**Comment by Ilaiwi** [comment]
p

**Comment by Ilaiwi** [comment]
released in 0.25.0
