### ISSUE TITLE
Switch timeline to a new time frame

### ISSUE THREAD

**Issue by flyalex** [namespace-ee/react-calendar-timeline#33]
Hi!

Have date-picker near timeline and want to be able to switch timeline visible frame to a new time when new date is picked by user.

How can I make this feature?

Thanks for the great timeline again!)
Alex

**Comment by xmityaz** [comment]
I guess you can specify [visibleTimeStart and visibleTimeEnd](https://github.com/namespace-ee/react-calendar-timeline#visibletimestart-and-visibletimeend) properties. And on date-picker change you can just overwrite visibleTime* values.
But in case you using visibleTime* properties, you would also need to specify [onTimeChange](https://github.com/namespace-ee/react-calendar-timeline#ontimechangevisibletimestart-visibletimeend) method for them

**Comment by ekvalheim** [comment]
Hi

I also want to use a date-picker. But when updating visibleTimeStart and visibleTimeEnd, I get the following error: "Unable to get property 'dimensions' of undefined or null reference" if the new date contains any items. Is this because the  sortedDimensionItems is not updated if the items list and the groups list are unchanged?

Espen

**Comment by xmityaz** [comment]
Hi, @ekvalheim 
Possible reason of this error could be mutating of timeline items array. It should be immutable value. If you're changing the items array directly, try to create new array which contains old and new items (possibly with .concat method)

**Comment by ekvalheim** [comment]
Creating new items array works. Thanks.

**Comment by mariusandra** [comment]
Looks like this is fixed? Thank you @xmityaz for responding! :)

**Comment by t-hughes** [comment]
@ekvalheim would you be able to post some example code of how you implemented this?

**Comment by ekvalheim** [comment]
@t-hughes 
**jsx:**
```
<Timeline
   groups={groups}
   items={items}
   calendarDate={calendarDate}
   visibleTimeStart = {moment(calendarDate)
     .startOf('day')
     .hour(8).valueOf()}
   visibleTimeEnd={moment(calendarDate)
     .startOf('day')
     .hour(20).valueOf()}
/>

<DateTimePicker
  value={calendarDate}
  onChange={dateChange}
/>
```

In the **dateChange** function, the calendarDate property is updated, and the items array is populated with new data received from web api.

```
items: action.meetings.map((object) => ({
   id: object.Id,
   group: object.GroupId,
   start_time: moment(object.Start),
   end_time: moment(object.End),
   canMove: false,
   canResize: false,
   className: object.FreeBusyStatus === 0 ? 'free' : 'standard',
   title: object.Subject,
}))
```

**Comment by t-hughes** [comment]
Thanks @ekvalheim !
