### ISSUE TITLE
Navigate programatically

### ISSUE THREAD

**Issue by FabriceReynolds** [namespace-ee/react-calendar-timeline#336]
How can I programatically navigate the timeline to a specified date/time or to a specific zoom level? 

For example I would like like to have a button/calendar  that I can click on to go to a specific date at a specific zoom level

Just want to add that this is a really great implementation of a timeline component, thanks.

**Comment by mcMickJuice** [comment]
You should be able to achieve this by using the `visibleTimeStart` and `visibleTimeEnd` props:

https://github.com/namespace-ee/react-calendar-timeline#visibletimestart-and-visibletimeend

Whatever you pass in via these props will move the timeline to those dates.  Does this help you achieve what you want to achieve?

**Comment by FabriceReynolds** [comment]
This does work correctly thanks. I was running into issues in my implementation which caused values to be overridden.
