### ISSUE TITLE
handle swipe browser back interactions

### ISSUE THREAD

**Issue by mattgi** [namespace-ee/react-calendar-timeline#34]
I found that I was constantly causing the browser to navigate forward/back as I swiped my trackpad.

Looking at some JS solutions but it seems like it is solved by just adding some styles to `.rct-scroll`

```
-ms-touch-action : none;
touch-action     : none;
```

**Comment by mariusandra** [comment]
Hey, before I put it in by default, could you explain a bit more how and why this happened? I.e. what's your setup, where must you swipe to get this effect, etc.

I have a macbook with a trackpad, where swiping left/right does go forward/back, but couldn't fully reproduce the effect. Only once and accidentally over the header, but then never again.

**Comment by mariusandra** [comment]
Hey, I just released 0.8.6 that contains those two extra CSS lines.
