### ISSUE TITLE
Support prop `style` for Item

### ISSUE THREAD

**Issue by morulus** [namespace-ee/react-calendar-timeline#347]
Support prop `style` for an Item component, that allows you to specify the inline-style of a particular item. 
In can be used to specify some dynamic styles, which can't be described in CSS classes. For example, set backgroundColor received from the server for each element. Or the item color is formed by some user configuration. Random color at least.

```js
items.map(item => {
   ...item,
   style: {
       backgroundColor: someHowGetRandomColor()
    }
});
```

Why className is not suitable? Because className can contain the only static set of styling, that cannot be formed dynamically (of course you can access Stylesheet object or use styled-components, but it is excessive complexity). At that time, the feature may take only one line of code.

**Comment by mcMickJuice** [comment]
Pending release in 0.17.2
