### ISSUE TITLE
onItemDeselected function is not documented

### ISSUE THREAD

**Issue by yftachman** [namespace-ee/react-calendar-timeline#350]
**Describe the bug**
Hey, I've found a function on the props that is not documented and works. Also makes sense to have this function (it was just what I needed).

Weird part is it has a comment on it saying this isn't in the docs...

**Comment by mcMickJuice** [comment]
Seems like a quick doc fix. Mind submitting a PR?

**Comment by Ilaiwi** [comment]
released in 0.26.3
