### ISSUE TITLE
PeerDependency version of interactjs doesn't work with browserify

### ISSUE THREAD

**Issue by yftachman** [namespace-ee/react-calendar-timeline#352]
**Describe the bug**
Hey, since moving interactjs as peer dependency I can't run my project unless I delete the dist folder of interact js. 
Obviously this is their bug however this post: https://github.com/taye/interact.js/issues/593
has a solution that might help as a workaround in the mean time.
   
**To Reproduce**
1. npm install react-calendar-timeline
2. WARN have peer dependency interactjs
3.  npm install interactjs
4. project can't run because  
"Error: Cannot find module './src/utils/window' from '/Users/.../git/app/node_modules/interactjs/dist'"

Not sure what to do as making all of my team mates  delete the dist folder of a some random library sounds pretty ridiculous.

**Comment by mcMickJuice** [comment]
@yftachman thanks for opening this. Would you mind submitting a small PR to fix this? interactjs is in Item.js file

**Comment by mcMickJuice** [comment]
I'm going to close this as this is an issue with interactjs library, not this one.
