### ISSUE TITLE
Implement time slot select for new item

### ISSUE THREAD

**Issue by AlexSenchenko** [namespace-ee/react-calendar-timeline#358]
I want to implement behavior when on mouse click on canvas 
will create newItem with  `timeStart`
second click - will be item `timeEnd`, and then - new item dialog will be showed with 
predefined dates:  start, end.
Between first and second click will be selection showed. 

Is it possible with current control api?

**Comment by Ilaiwi** [comment]
what do you mean by "Between first and second click will be selection showed."?

**Comment by AlexSenchenko** [comment]
I mean, like you select in daterange control start and end dates, like in Expedia.

**Comment by Ilaiwi** [comment]
With the current implementation, this is possible with (plugins)[oncanvasclickgroupid](https://github.com/namespace-ee/react-calendar-timeline#oncanvasclickgroupid-time-e] but is not very straightforward. First, you need to listen to the onCanvasClick to get startDate, endDate and group when clicking. For the plugin, you need it to get the mouse hover date and group. To do so you need to have a div that covers the whole canvas that listens to onHover event and turn it to group and date (you can check the onCanvasClick to understand how to calculate these) and left the state up. As for the selection UI you need to implement it as a temp item for `Timeline` or implement a custom UI with the plugin for hover.

**Comment by mcMickJuice** [comment]
@AlexSenchenko this can be achieved either using [onCanvasClick](https://github.com/namespace-ee/react-calendar-timeline#oncanvasclickgroupid-time-e) which returns time. You would have to manage the first and second click though.  Or you can do what @Ilaiwi suggests.
