### ISSUE TITLE
Single Row Header has wrong Height

### ISSUE THREAD

**Issue by dkarnutsch** [namespace-ee/react-calendar-timeline#359]
**Describe the bug**
When using a very large maxZoom (e.g. 15 years) to have a single row header, the row height is wrong. 

**To Reproduce**
https://codesandbox.io/s/pjl9ln5mom

**Expected behavior**
The top row should have zero size

**Screenshots**
<img width="2211" alt="screen shot 2018-07-09 at 14 58 29" src="https://user-images.githubusercontent.com/10632685/42453236-64d0986a-838c-11e8-9793-63018a335c00.png">

**Library Version**
0.17.2

**Desktop (please complete the following information):**

* OS: iOS
* Browser Chrome
* Version 67

**Comment by mcMickJuice** [comment]
Fixed in 0.17.3
