### ISSUE TITLE
change headerLabelFormats and subHeaderLabelFormats doesn't reflect change in headers

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#362]
**Describe the bug**
changing the props `change headerLabelFormats` and `subHeaderLabelFormats` dynamically doesn't change the labels on header and subheader and change only reflect if you zoom in and out again
**To Reproduce**
change headerLabelFormats or subHeaderLabelFormats  dynamically
https://codesandbox.io/s/7m0yn3x4z1

**Screenshots**

**Library Version**
`0.17.3`
**Desktop (please complete the following information):**

* OS: Windows
* Browser chrome

**Comment by mcMickJuice** [comment]
Released in 0.18.0
