### ISSUE TITLE
Custom styles for vertical lines (dates)

### ISSUE THREAD

**Issue by dkarnutsch** [namespace-ee/react-calendar-timeline#364]
**Is your feature request related to a problem? Please describe.**
I want to have special styling for certain dates. Use cases would be e.g. public holidays or opening hours.  Partly described in #331. 

**Describe the solution you'd like**
I would want to add custom classes to the vertical lines depending on the time and unit. 

**Describe alternatives you've considered**
I haven't found any other practical way to do this. 

**Additional context**
I will open a PR.

**Comment by mcMickJuice** [comment]
Released in 0.19.0
