### ISSUE TITLE
Change the locale of the calendar.

### ISSUE THREAD

**Issue by Grigosha40** [namespace-ee/react-calendar-timeline#366]
Hi,
This timeline calendar is very cool! It is so helpful!!! 

But I have one problem. It doesn't change the language even when I try to change the moment locale!

Can you help me, pls:)))

**Comment by dkarnutsch** [comment]
How did you try to change the locale?

For me using `moment().locale("de");` in the constructor of `App.js` works fine. You can also change the way how the dates are displayed with `headerLabelFormats` and ?`subHeaderLabelFormats`.

**Comment by Grigosha40** [comment]
Thank you for the quick reply. I am trying the same thing, but the calendar doesn't pay any attention to this!
