### ISSUE TITLE
Custom styles for horizontal lines (groups)

### ISSUE THREAD

**Issue by dkarnutsch** [namespace-ee/react-calendar-timeline#367]
**Is your feature request related to a problem? Please describe.**
Especially when using the tree groups example it is frustrating that I can't style the headers of the groups different than the groups itself. Also I would like to overwrite the calculated height with a custom height.

**Describe the solution you'd like**
For the height: If the height is specified in the group, the lib should use this as the height and not the calculated height.

For the custom style: Every time the horizontal line is rendered, I would like to have a callback where I can supply custom styles. 

**Describe alternatives you've considered**
I've seen that there was/is a plugin approach which makes it possible to make something of this happen, but it seems that there is no documentation and the link to the example is dead. Alternatively we could support categories natively. 

**Additional context**
I will submit an PR.

**Comment by mcMickJuice** [comment]
Released in 0.19.0
