### ISSUE TITLE
An easy way to disable scroll and zoom

### ISSUE THREAD

**Issue by Dr-Satan** [namespace-ee/react-calendar-timeline#369]
Hello and thank you very much for this component !
Is there an easy way to disable scroll and zoom ?

**Comment by Ilaiwi** [comment]
yes, you can. You can do that by providing `visibleTimeStart` and `visibleTimeEnd`, and implement `handleOnTimeChange` to only call `updateScrollCanvas` with your `visibleTimeStart` and `visibleTimeEnd`

**Comment by Ilaiwi** [comment]
this might be easier when #357 gets implemented maybe

**Comment by Dr-Satan** [comment]
Okay, I found it. I did as you said but fixing visibleTimeStart and visibleTimeEnd to keep it still

`
handleTimeChange = (visibleTimeStart, visibleTimeEnd,updateScrollCanvas) => {
        updateScrollCanvas(moment(this.state.defaultTimeStart).valueOf(),  moment(this.state.defaultTimeEnd).valueOf());
 }`

**Comment by Dr-Satan** [comment]
Thanks !
