### ISSUE TITLE
Cannot resolve module

### ISSUE THREAD

**Issue by gregorystoos** [namespace-ee/react-calendar-timeline#37]
Hi, I installed and try to run the exemple in my React app and got this error 

Module not found: Error: Cannot resolve module 'react-calendar-timeline'

**Comment by mariusandra** [comment]
Hey, I might have screwed something up with the last builds. Try if the just released 0.8.4 works.

**Comment by gregorystoos** [comment]
*ERROR in ./~/react-calendar-timeline/modules/lib/Timeline.js*

*Module not found: Error: Cannot resolve 'file' or 'directory'
./Timeline.scss*

*...*

*@ ./~/react-calendar-timeline/modules/lib/Timeline.js 19:0-26*

**Comment by mariusandra** [comment]
Please try again with 0.8.5

**Comment by gregorystoos** [comment]
Working now !!! Thanks a lot !
