### ISSUE TITLE
Static propTypes error

### ISSUE THREAD

**Issue by tymochko** [namespace-ee/react-calendar-timeline#371]
Hi,
I installed "react-calendar-timeline" but constantly getting an error about: 
```
ERROR in .../node_modules/react-calendar-timeline/src/lib/Timeline.js 36:19
Module parse failed: Unexpected token (36:19)
You may need an appropriate loader to handle this file type.
|
| export default class ReactCalendarTimeline extends Component {
>   static propTypes = {
|     groups: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
|     items: PropTypes.oneOfType([PropTypes.array, PropTypes.object]).isRequired,
```
Although my .babelrc looks like this (I assume I did everything right, stage-2 includes "transform-class-properties", even thou I tried stage-1 and stage-0)
```
{
  "presets": [
    "env",
    "react",
    "stage-2",
    "flow"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ],
  "comments": false
}
```
somehow "react-calendar-timeline" get into webpack running process with the uncompiled code.
Part of webpack.config.js which shows that node_modules are not going to be bundled.
```
{
        test: /\.js$/,
        exclude: /node_modules/,
        use: 'babel-loader'
    }
```
Please help to solve this problem.

**Comment by Ilaiwi** [comment]
try `react-calendar-timeline/lib`

**Comment by Ilaiwi** [comment]
yes it is a peer dependanciy
