### ISSUE TITLE
ScrollRef to programmatically scroll

### ISSUE THREAD

**Issue by dkarnutsch** [namespace-ee/react-calendar-timeline#372]
**Is your feature request related to a problem? Please describe.**
In order to programmatically scroll (not just setting the visible range, but animating) I would like to have a DOM reference to the scroll element.

**Describe the solution you'd like**
Same solution as for the header reference.

**Describe alternatives you've considered**
-

**Additional context**
I will submit a PR.

**Comment by mcMickJuice** [comment]
Released in 0.19.0

**Comment by Khyzz** [comment]
Hello,

Any documentation on scrollref? I can't understand how to use it... Thanks.

**Comment by Ilaiwi** [comment]
They are non for now. Controlled scrolling is not an easy task for now. 
On the other hand, ou can pass `visiableTimeStart` and `visableTimeEnd` for now to control scrolling

**Comment by dkarnutsch** [comment]
We are using it currently in the following way:
```
<Timeline
    scrollRef={(el) => this.scrollRef = el} />
```

and to scroll
```
animateScroll = (invert) => {
    const width = (invert ? -1 : 1) * parseFloat(this.scrollRef.style.width); // cos curve in both directions
    const duration = 2000;

    const startTime = performance.now();
    let lastWidth = 0;
    const animate = () => {
        let normalizedTime = (performance.now() - startTime) / duration;
        if (normalizedTime > 1) { // not overanimate
            normalizedTime = 1;
        }

        // http://www.wolframalpha.com/input/?i=plot+0.5+(1%2Bcos(%CF%80+(x-1)))*1000+from+0+to+1 --> 1000 is the simulated width
        const calculatedWidth = Math.floor(width*0.5*(1+Math.cos(Math.PI*(normalizedTime-1))));
        this.scrollRef.scrollLeft += calculatedWidth - lastWidth;
        lastWidth = calculatedWidth;

        if (normalizedTime < 1) {
            requestAnimationFrame(animate);
        }
    };
    requestAnimationFrame(animate);
};
```
Hope this helps!

**Comment by Ilaiwi** [comment]
Hi @dkarnutsch. Thank you for the example 👍 
if you could please do a codesandbox with this snippet and make a PR to add it to examples I would really appreciate it

**Comment by Khyzz** [comment]
Yes thanks @dkarnutsch.
@Ilaiwi I tried to use visibleTimeStart/End but for some reason I have an error while trying to use it : it doesn't want to take a moment("...") in any format
