### ISSUE TITLE
onCanvasClick not wirking

### ISSUE THREAD

**Issue by florianbepunkt** [namespace-ee/react-calendar-timeline#374]
**Describe the bug**
onCanvasClick method does not get called

**To Reproduce**
`<Timeline onCanvasClick={() => console.log("FOO")} />`

**Expected behavior**
`<Timeline onCanvasClick={() => console.log("FOO")} />` should log FOO, but logs nothing.

**Library Version**
0.17.3

**Comment by florianbepunkt** [comment]
Sure. https://codesandbox.io/s/52r0rxp8px

**Comment by mcMickJuice** [comment]
In that sandbox, you weren't passing `onCanvasClick` to the library's `Timeline` component. Here's the fixed sandbox which is logging out FOO:

https://codesandbox.io/s/kkjmy3x9qv

Please let me know if this problem persists and I'll reopen.

**Comment by florianbepunkt** [comment]
My bad, sorry. The problem on my side still persists… I also found the culprit. I'm using a timeline ranges plugin like this

```
<Timeline ...props>
<TimelineRanges />
</Timeline>
```

But this prevents the underlying canva from being accessible/clickable. That is why the clicks were never logged in my case.

**Comment by mcMickJuice** [comment]
Hmm, I'm not sure the best solution for you.  You can try to add the click handler to whatever components you're rendering in the TimelineRanges plugin.  I'm not too familiar with how plugins work with this library so I'm sorry I can't be of more help.
