### ISSUE TITLE
Vertical scroll issue

### ISSUE THREAD

**Issue by tymochko** [namespace-ee/react-calendar-timeline#376]
Hi,
I faced an issue with vertical scrolling when there are many rows available.
It is especially noticeable when "timeline" is used in popover.

Please see demo attached: (https://codesandbox.io/s/o9y6w366w6)

I would expect when mouse pointer is above "timeline" and I am using mouse scroll - timeline rows should scroll and when mouse pointer is above outer content and I use mouse scroll - outer content is scrolling.

Actual result: mouse pointer is above "timeline" and I use mouse scroll but outer content is scrolling instead of "timeline" rows.

**Comment by mcMickJuice** [comment]
This looks like a duplicate of https://github.com/namespace-ee/react-calendar-timeline/issues/332 , at least the symptoms are the same.
