### ISSUE TITLE
groupRenderer doesnt work for right sidebar

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#377]
**Describe the bug**
Timeline's right sidebar doesn't content doesn't render the `groupRenderer` passed to the timeline

**To Reproduce**
1. provide `rightSidebarWidth` prop to timeline
2. provide `groupRenderer` prop to timeline

**Expected behavior**
right sidebar content should be rendered through `groupRenderer` if provided

**Library Version**
0.18

**Desktop (please complete the following information):**

* OS: macOS
* Browser Chrome

**Additional context**
fixing this is easy just pass `groupRenderer` to the right sidebar 
[code](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L920)

**Comment by mcMickJuice** [comment]
Fixed in 0.18.1
