### ISSUE TITLE
cursor marker disappear while hovering over item 

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#378]
**Describe the bug**
The cursor marker disappears while hovering over an item

**To Reproduce**
hover over item
https://codesandbox.io/s/n920olmyxj

**Expected behavior**
the cursor should be shown by default even though the cursor is over an item

**Library Version**
0.18
**Desktop (please complete the following information):**

* OS: macOS
* Browser Chrome

**Additional context**
This problem occurs because the `MarkerCanvas` has no z-index value whereas the item z-index is 80. I think the `MarkerCanvas` should get the highest z-index of all layers. This will make items though undraggable (Not sure how to go with this to be honest)

**Comment by Ilaiwi** [comment]
What do you think about maybe track the mouse over event on the root canvas div?

**Comment by mcMickJuice** [comment]
@Ilaiwi  I'll try this, or have the MarkerCanvas accept children, or something 😄
