### ISSUE TITLE
Date passed to CursorMarker child is wrong

### ISSUE THREAD

**Issue by Ilaiwi** [namespace-ee/react-calendar-timeline#379]
**Describe the bug**
the date bassed to `CursorMarker` render prop is wrong
**To Reproduce**
look at the console of 
https://codesandbox.io/s/n920olmyxj

**Expected behavior**
print the correct hover date

**Library Version**
0.18
**Desktop (please complete the following information):**

* OS: macOS
* Browser chrome

**Comment by mcMickJuice** [comment]
Fixed in 0.18.1
