### ISSUE TITLE
Stackable items

### ISSUE THREAD

**Issue by LitvinaviciusM** [namespace-ee/react-calendar-timeline#384]
Hey guys, 

Not sure if it is a feature request yet.
Is there any way to stack items only for a specific group ? 

Thanks for a great lib! Any advice is welcome!

**Comment by mcMickJuice** [comment]
I don't believe this is currently possible, although someone else might want to chime in if they were able to achieve this.

**Comment by Ilaiwi** [comment]
This would be very helpful for me as well!

**Comment by Ilaiwi** [comment]
released in 0.23.0
