### ISSUE TITLE
Uncaught Error: A valid React element (or null) must be returned

### ISSUE THREAD

**Issue by pranshu1992** [namespace-ee/react-calendar-timeline#396]
**Getting this error when I run the basic example**
Uncaught Error: Consumer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object

```
import React from 'react';
import Timeline from 'react-calendar-timeline'
// make sure you include the timeline stylesheet or the timeline will not be styled
import 'react-calendar-timeline/lib/Timeline.css'
import moment from 'moment'

const groups = [{ id: 1, title: 'group 1' }, { id: 2, title: 'group 2' }]

const items = [
  {
    id: 1,
    group: 1,
    title: 'item 1',
    start_time: moment(),
    end_time: moment().add(1, 'hour')
  },
  {
    id: 2,
    group: 2,
    title: 'item 2',
    start_time: moment().add(-0.5, 'hour'),
    end_time: moment().add(0.5, 'hour')
  },
  {
    id: 3,
    group: 1,
    title: 'item 3',
    start_time: moment().add(2, 'hour'),
    end_time: moment().add(3, 'hour')
  }
]
import './App.css';

const App = () => (
  <div>
    Rendered by react!
    <Timeline
      groups={groups}
      items={items}
      defaultTimeStart={moment().add(-12, 'hour')}
      defaultTimeEnd={moment().add(12, 'hour')}
    />
  </div>
);

export default App;
```

![image](https://user-images.githubusercontent.com/9313077/43565936-843ac9de-95e1-11e8-9e1a-1bb7fa02de52.png)

Here are all the dependencies in my package.json for this test.
        "interactjs": "^1.3.4",
        "moment": "^2.22.2",
        "react": "^15.6.1",
        "react-calendar-timeline": "^0.18.2",
        "react-dom": "^15.6.1",
        "react-redux": "^5.0.6",
        "redux": "^3.7.2"

**Comment by Ilaiwi** [comment]
I copied your code in https://codesandbox.io/s/428qqz86j0 and it worked. could you use codesandbox and reproduce the issue please?

**Comment by mcMickJuice** [comment]
This library supports > react 16. You have React 15.6.1 installed.

You should see a peer dependency warning when you run npm install.

Solution: upgrade to React 16+

**Comment by pranshu1992** [comment]
Yes I was able to get it to work with react v16. Is there any plan to make this backward compatible ?

**Comment by mcMickJuice** [comment]
No there is not.
