### ISSUE TITLE
DOM elements inside .rct-header overlapping when not in fullscreen

### ISSUE THREAD

**Issue by kastanekdavid** [namespace-ee/react-calendar-timeline#4]
![image](https://cloud.githubusercontent.com/assets/4254731/13853740/68b80a20-ec68-11e5-98f1-5bc3a8337ebd.png)

**Comment by mariusandra** [comment]
Thank you for reporting this as well. Same question as with #3, could you submit a PR with a fix as well?

**Comment by mariusandra** [comment]
Hey,

Would it be enough if you set the prop `fixedHeader='none'`?

In that case the header will not be fixed on the screen when you scroll up/down, but on the other hand won't go over the boundary of the component, like this:

![screen shot 2016-03-22 at 18 21 56](https://cloud.githubusercontent.com/assets/53387/13961006/fd4d6e78-f05a-11e5-9c00-d3308aa6653b.png)

If that's not possible, then in the current iteration you'll need to surround the component with some `<div style='position:fixed; top: ..., with: ...' />` elements, that visually block the `position:fixed` header.
