### ISSUE TITLE
[Question] Printing / export as PDF

### ISSUE THREAD

**Issue by maxaggedon** [namespace-ee/react-calendar-timeline#400]
I need to export my timeline as image or pdf. I wondered if anyone encountered such a use case or have ideas how to do it?

**Comment by mcMickJuice** [comment]
This library doesn't support print media queries but you can provide your own.  Just look at the source code to see where classes are added.

This question is out of scope for this repo from a feature/support perspective.

**Comment by Jesperpaulsen** [comment]
@maxaggedon, did you find any solution on how to do this?
