### ISSUE TITLE
Scroll left/right causes item move/edit to be at incorrect time

### ISSUE THREAD

**Issue by acemac** [namespace-ee/react-calendar-timeline#401]
**Describe the bug**
When moving or resizing a booking while scrolling with shift+mousewheel, the position of the action is wrong

**To Reproduce**
1. Go to https://codesandbox.io/s/6vo2jkov23
2. Click on any booking and move it left/right with the mouse
3. Hold shift+mousewheel
4. Booking position will no longer be under mouse

**Expected behavior**
Booking should move with the scroll, bookings can then be moved past the screen/canvas by scrolling

**Library Version**
19.0

**Desktop (please complete the following information):**

* OS: Win10
* Browser Chrome
* Version 67

**Comment by Ilaiwi** [comment]
released in 0.22.0
