### ISSUE TITLE
Example for resize in itemRenderer

### ISSUE THREAD

**Issue by florianbepunkt** [namespace-ee/react-calendar-timeline#402]
**Is your feature request related to a problem? Please describe.**
Since 0.19.0 came with a complete refactored itemRenderer prop it would be nice to see in the docs a more complete example(s) that shows how to reproduce the old functionality. I have elements that can be resized. this worked out of the box with a custom item renderer component before. now when I use an itemRenderer function from the example I can only move the element but not resize it.

**Describe the solution you'd like**
Add example to itemRenderer docs that more completely reproduces the functionality it had before 0.19.0

**Comment by florianbepunkt** [comment]
okay, nevermind… I figured it out. not sure why but in the existing example of the itemRenderer method  all conditionals include a check for `itemContext.showInnerContentsRender` which I have not set. therefore all the resize elements never render.

**Comment by Ilaiwi** [comment]
my bad! will fix the readme
