### ISSUE TITLE
Help Please. I use create-react-app and I get error Module not found: Can't resolve 'interactjs' 

### ISSUE THREAD

**Issue by riflemanIm** [namespace-ee/react-calendar-timeline#403]
Failed to compile.

./node_modules/react-calendar-timeline/lib/lib/items/Item.js
Module not found: Can't resolve 'interactjs' in '/home/oleg/sandbox/my-app/node_modules/react-calendar-timeline/lib/lib/items'

**Comment by dkarnutsch** [comment]
`interactjs` is listed as a peer dependency. So please add it to your webpack config.

**Comment by rohitgupta3** [comment]
Does this require ejecting then?

**Comment by mcMickJuice** [comment]
No. You can just npm install it.
