### ISSUE TITLE
Conditional to check if the user has zoomed into day view

### ISSUE THREAD

**Issue by tot98git** [namespace-ee/react-calendar-timeline#405]
Hi all,
I do apologise in advance if such issue has been submitted before.
I am using react-calendar-timeline on an employee management system.
Currently, I am implementing a feature in which when the user is scrolled into month view, it is going to show the shift types (morning / afternoon shifts), but when the user scrolls into day view it is going to give a detailed interval about the employee's presence. 
So far what I could do is create a conditional using **visibleTimeStart / visibleTimeEnd** and check if the returned value has round hours (00:00 / 24:00). That practically works if the user zooms by clicking in the fields however not when the user literally **zooms** through the timeline.
Can somebody help me or suggest an approach to implementing that feature?
Also, the **minZoom** feature is not working for some reason. I provided it with the milliseconds equivalent of a day.

Thank you.

edit: scrolls -> **zooms** (Not the best choice of words)

**Comment by Ilaiwi** [comment]
have you checked `onTimeChange`? it should be called on every zoom event (click and mouse scroll)

**Comment by tot98git** [comment]
@Ilaiwi Yeah but my problem is not the zoom event not being fired. It's just how to check if the view is day-view. Thank you for your input!

**Comment by Ilaiwi** [comment]
so `visibleTimeStart ` and `visibleTimeEnd ` are in milliseconds. If you subtract them you should get a duration of the day in milliseconds which is `8.64e+7` or you can use moment to get the moment diff between the two values

**Comment by tot98git** [comment]
OK! Taking @Ilaiwi advice, I solved my issue. Thank you so much!
To reiterate, my issue was to create an event that checks if the user has scrolled into day view and if they did, the view state would switch to 1. In the context of my project, _view 1_ was employees check in / out intervals and _view 2_ were shift types.
  For anyone who might find this useful in the future, the approach I took towards achieving that was to get the date difference (as suggested by @Ilaiwi ) and if that difference divided by 24 equaled less than 4 (meaning 4 days are visible which is suitable for the context of view 1) it would switch to _view 1_ and if it didn't it would switch to _view 2_.
I attached this function to the onZoom event. Haven't seen any performance issues yet and hope I won't. 😄 
````
onZoom = (timelineContext) => {
       let date1 = moment(timelineContext.visibleTimeStart).format("YYYY-MM-DD HH:mm:ss");
       let date2 = moment(timelineContext.visibleTimeEnd).format("YYYY-MM-DD HH:mm:ss");
       var e = moment(date1, "YYYY-MM-DD HH:mm:ss").diff(date2, "YYYY-MM:DD HH:mm:ss")
       var d = moment.duration(e);
       var s = Math.floor(d.asHours()) + moment.utc(e).format(":mm:ss");
       console.log("D: ", Math.abs(d.asHours()), "calc: ", (Math.abs(d.asHours()) / 24) < 3);
       this.setState({ selectedView: Math.abs(d.asHours()) / 24 < 3 ? 1 : 2 })
   }
