### ISSUE TITLE
onCanvasClick on canvas not work

### ISSUE THREAD

**Issue by ronnyfly2** [namespace-ee/react-calendar-timeline#407]
Hello, the onCanvasClick event does not work on ipad, tablets and mobile devices
How do I make it work?
`import React, { Component } from 'react';
import {Router, Route, Link, RouteHandler} from 'react-router';
import Timeline from 'react-calendar-timeline/lib';
import DatePicker from 'react-datepicker';
import Stickyfill from 'stickyfilljs';
//import momentTimezone from 'moment-timezone';
import 'react-calendar-timeline/lib/Timeline.css'
import {AuthValidate} from '../../../Utils/AuthValidate';
import HeaderSection from './../../Home/Header/HeaderSection';
import ReservationApi from '../../../Api/Reservations/ReservationApi';
import ReactModal from 'react-modal';
import Spinner from '../../../Utils/Spinners/Spinner';
import 'react-datepicker/dist/react-datepicker.css';
import moment from 'moment';
import 'moment/locale/es';
import 'moment-timezone';
import './TimeLine.css';
import HomeApi from '../../../Api/Home/HomeApi';
moment.locale('es');
//momentTimezone.tz.setDefault('UTC');
var $ = window.jQuery;
const statusIcons = {
	'confirmada': 'libro',
	'cancelada': 'cancelada',
	'Pendiente': 'libro',
	'reservada': 'sentados',
	'noshow': 'noshow',
};
var keys={
		groupIdKey: 'id',
		groupTitleKey: 'title',
		groupRightTitleKey: 'rightTitle',
		itemIdKey: 'reservation_id',
		itemTitleKey: 'title',    // key for item div content
		itemDivTitleKey: 'title', // key for item div title (<div title="text"/>)
		itemGroupKey: 'group',
		itemTimeStartKey: 'start_time',
		itemTimeEndKey: 'end_time'
}
export class TimeLineIndx extends Component{
	constructor(props) {
		super(props);
		this.state = {
			startDate: null,
			dateTimelineStart: null,
			dateTimelineEnd:null,
			dateTimelineStartDynamic:null,
			dateTimelineEndDynamic:null,
			groups:null,
			items: null,
			reservations:null,
			zonesArray:[],
			zoneList:[],
			currentZone: 0,
			showChangeState:false,
			loadingModal:false,
			combinedTables:[],
			selectTableOpen:null,
			itemSelect:null,
			buttonDisabled:true,
		};
		this.apiReservation = new ReservationApi();
		this.getReservationsForTimeline = this.getReservationsForTimeline.bind(this);
		this.getZonesList = this.getZonesList.bind(this);
		this.onChangeZone = this.onChangeZone.bind(this);
		this.renderZoneList = this.renderZoneList.bind(this);
		this.clickItem = this.clickItem.bind(this);
		this.onScroll = this.onScroll.bind(this);
		this.handleChange = this.handleChange.bind(this);
		this.getBeforeDay = this.getBeforeDay.bind(this);
		this.getAfterDay = this.getAfterDay.bind(this);
		this.getToday = this.getToday.bind(this);
		this.remderTimeLine = this.remderTimeLine.bind(this);
		this.itemRenderer = this.itemRenderer.bind(this);
		this.groupRederer = this.groupRederer.bind(this);
		this.cursorAct = this.cursorAct.bind(this);

		this.clickCanvasRow = this.clickCanvasRow.bind(this);
		this.handleCloseModal = this.handleCloseModal.bind(this);
		this.scroolTopStiky = this.scroolTopStiky.bind(this);
		this.onChangeCombined = this.onChangeCombined.bind(this);
		this.clickSelect = this.clickSelect.bind(this);
		this.createIntervals = this.createIntervals.bind(this);
	}
	//componentWillMount
	componentDidMount() {
		this.getZonesList()
		this.props.handleVisibility(false);

		this.setState({currentZone:parseInt(localStorage.IdZone, 10)});
		this.setState({
			startDate:moment(localStorage.dateTurnDay),
			dateTimelineStart:moment(localStorage.dateTurnDay).add(0, 'hour'),
			dateTimelineEnd:moment(localStorage.dateTurnDay).add(4, 'hour')
		});
		this.getReservationsForTimeline(localStorage.dateTurnDay,localStorage.IdZone);
	}
	createIntervals(){
		$('.rct-vl').map((idx, elem)=>{
			$(elem).html('<div class="intervals"></div><div class="intervals"></div><div class="intervals"></div><div class="intervals"></div>');
		});
	}
	getReservationsForTimeline(dateReservations,idZones){
		this.setState({groups:null})
		let tablesArray = [];
		let dateReservation = dateReservations;
		let idZone = idZones;
		localStorage.dateTurnDay = dateReservation;
		localStorage.IdZone = idZone;
		this.apiReservation.getReservationTimeLine(
			(data)=>{
				if(data.data.success){
					this.state.reservations = data.data.data.reservations;
					let tables = data.data.data.tables;
					data.data.data.tables.map((elem,idx)=>{
						if(elem.zone == tables[idx].zone){
							tablesArray.push(elem.title)
						}
						this.state.zonesArray.push(elem.zone);
					})
					//this.state.zonesArray.unique();
					//let uniqueZone = this.eliminateDuplicates(this.state.zonesArray);
					data.data.data.reservations.map((elem,idx)=>{
						//console.log('----')
						//console.log('title',data.data.data.reservations[idx].title)
						//console.log('----')
						//console.log('init',moment(elem.start_time).format('HH:mm'))
						//console.log('end',moment(elem.end_time).format('HH:mm'))
						//console.log('live',moment(elem.end_time))
						//console.log('----')
						if(moment.tz.guess()!='America/Lima'){
							this.state.reservations[idx].start_time = moment.utc(moment.utc(elem.start_time).format('YYYY/MM/DD HH:mm')).format('x');
							this.state.reservations[idx].end_time = moment.utc(moment.utc(elem.end_time).format('YYYY/MM/DD HH:mm')).format('x');
						}else{
							this.state.reservations[idx].start_time = moment(moment.utc(elem.start_time).format('YYYY/MM/DD HH:mm')).format('x');
							this.state.reservations[idx].end_time = moment(moment.utc(elem.end_time).format('YYYY/MM/DD HH:mm')).format('x');
						}
					})
					this.setState({
						groups:data.data.data.tables,
						items:this.state.reservations
					});
					this.props.handleVisibility(false);
				}
			},
			{date:dateReservation, zone_id:idZone},
			(erno)=>{
				console.log('salio un error', erno)
				this.apiReservation.functionMessage('Algo salió mal, intentelo mas tarde', 'error-visible')
			}
		)
	}
	getZonesList(){
		(new HomeApi()).getAmbients((dataJSon)=>{
			this.setState({zoneList:dataJSon.data.zones});
		})
	}
	onChangeZone(e){
		this.setState({currentZone: parseInt(e.target.value, 10)});
		this.getReservationsForTimeline(localStorage.dateTurnDay,parseInt(e.target.value, 10));
	}
	clickSelect(e){
		this.state.itemSelect.timeline = true;
		this.setState({buttonDisabled:true});
		$('.select_option_assign ul button').removeClass('actived');
		let infoTurns = [];
		if(e!='walk-in'){
			(new ReservationApi()).getReservationHours((res)=>{
				if(res.data.data.hours.length > 0){
					res.data.data.hours.map((elem, idx)=>{
						if(elem.Seleccionado){
							this.state.itemSelect.nameTurn = elem.Titulo;
							this.state.itemSelect.idTurn = elem.TurnoId;
							this.state.itemSelect.idx = idx;
							infoTurns.push(idx);
						}else{
							infoTurns.push();
						}
					})
					if(infoTurns.length > 0){
						this.state.itemSelect.hours =res.data.data.hours;
						this.props.history.push('/reservations/create');
					}else{
						console.log('no tienes horarios o turnos para esta hora');
						this.setState({buttonDisabled:false});
						$('.select_option_assign ul button').addClass('actived');
					}
				}
			},{date: this.state.itemSelect.date,"table_id":this.state.itemSelect.id,hour:this.state.itemSelect.hour,"by":'US'})
		}else{
			this.props.history.push('/waitlists/create');
		}
		this.props.infoTableEmpty(this.state.itemSelect);
	}
	renderZoneList(){
		let zones = this.state.zoneList;
		let currentZone = this.state.currentZone;
		return (
			<div className="row">
				<div className="col-sm-3">
					<div className="form-group">
						<div className="select-arrow">
							<select value={currentZone} onChange={this.onChangeZone} className="form-control">
								<option value={0}>Elija una zona</option>
								{
									zones.map((ele,idx)=>{
										return <option key={idx} value={ele.Id}>{ele.Descripcion}</option>
									})
								}
							</select>
						</div>
					</div>
				</div>
				<div className="col-sm-3">
					<div className="form-group">
						<DatePicker
							selected={this.state.startDate}
							onChange={this.handleChange}
						/>
					</div>
				</div>
			</div>
		)
	}
	handleHeaderRef(el){
		// polyfill dom element with stickyfill
		if(el!=null){
			Stickyfill.addOne(el)
		}
	}
	scroolTopStiky(){
		if(document.querySelector( ".type_hour" )){
			document.querySelector( ".type_hour" ).style.top = document.querySelector( ".ctn_timeline" ).scrollTop+10 +"px";
		}
	}
	clickItem(itemId, time, dayHour){
		console.log("click", itemId, moment(time).format('YYYY/MM/DD, HH:mm:ss'), dayHour);
		this.apiReservation.getReservationInfo((res)=>{
			console.log('item resquest',res)
		},itemId)
	}
	clickCanvasRow(tableId, time, edge){
		console.log('hola pedu',tableId, time, edge.target)
		this.setState({showChangeState:true});
		this.setState({combinedTables:[],selectTableOpen:null,itemSelect:null});
		[].forEach.call(this.state.groups,(elem,idx)=>{
			if(elem.id === $(edge.target).data('id')){
				this.setState({
					selectTableOpen:{id:elem.id,title:elem.title,maxPax:elem.maxPax,minPax:elem.minPax,date:moment(time).format('YYYY-MM-DD'), hour: moment(time).format('HH:mm')},
					itemSelect:{id:elem.id,title:elem.title,maxPax:elem.maxPax,minPax:elem.minPax,date:moment(time).format('YYYY-MM-DD'), hour: moment(time).format('HH:mm')}
				})
				if(elem.used_in.length>0){
					this.setState({combinedTables:elem.used_in})
				}
			}
		})
		//console.log('log',moment(time).format('HH:mm'),moment(time).format('YYYY-MM-DD'));
	}
	onChangeCombined(e){
		//selectTableOpen:{id:elem.id,title:elem.title,maxPax:elem.maxPax,minPax:elem.minPax,date:moment(time).format('YYYY-MM-DD'), hour: moment(time).format('HH:mm')}
		if(e.target.value !== ''){
			$('.select_option_assign ul button').addClass('actived');
			this.setState({statebuttonDisabled:false});
			this.state.itemSelect.id=e.target.value;
			this.state.itemSelect.title=e.target.options[e.target.selectedIndex].dataset.name;
		}else{
			this.setState({statebuttonDisabled:true});
			$('.select_option_assign ul button').removeClass('actived');
		}

	}
	onScroll(dateInit,dateEnd,scrollFunction){
		//$('.rct-today').html('')
		//$('.rct-today').html('<div class="type_hour">'+moment().format('HH:mm:ss')+'</div>')
		//$('.rct-cursor-line').html('')
		//$('.rct-cursor-line').html('<div class="type_hour">'+moment().format('HH:mm:ss')+'</div>')
		if(moment(dateInit).format()>moment(this.state.dateTimelineStart).format()){
			//console.log('first1',moment(moment(dateInit).format('DD/MM/YYYY HH:mm')).format('x'),moment(moment(this.state.dateTimelineStart).format('DD/MM/YYYY HH:mm:ss')).format('x'))
			if(moment(dateEnd).format()<moment(this.state.dateTimelineEnd).add(20, 'hour').format()){
				//console.log('second2',moment(moment(dateInit).format('DD/MM/YYYY HH:mm')).format('x'),moment(moment(this.state.dateTimelineStart).format('DD/MM/YYYY HH:mm:ss')).format('x'));
				let dateInit = dateInit;
				let dateEnd = dateEnd;
			}else{
				//console.log('denied',moment(moment(dateInit).format('DD/MM/YYYY HH:mm')).format('x'),moment(moment(this.state.dateTimelineStart).format('DD/MM/YYYY HH:mm:ss')).format('x'))
				dateInit = moment(this.state.dateTimelineStart).add(20, 'hour');
				dateEnd = moment(this.state.dateTimelineEnd).add(20, 'hour');
			}
		}else{
			//console.log('thirds3',moment(moment(dateInit).format('DD/MM/YYYY HH:mm')).format('x'),moment(moment(this.state.dateTimelineStart).format('DD/MM/YYYY HH:mm:ss')).format('x'));
			dateInit = this.state.dateTimelineStart;
			dateEnd = this.state.dateTimelineEnd;
		}
		//console.log('passedd',moment(moment(dateInit).format('DD/MM/YYYY HH:mm')).format('x'),moment(moment(this.state.dateTimelineStart).format('DD/MM/YYYY HH:mm:ss')).format('x'));
		scrollFunction(dateInit,dateEnd);
		this.createIntervals()
	}
	handleChange(date){
		//console.log('este es',moment(1532455513*1000).format('YYYY-MM-DD HH:mm'))
		this.setState({
			startDate: date,
			dateTimelineStart:moment(moment(date).format('MM/DD/YYYY')).hours(0).minute(0),
			dateTimelineEnd:moment(moment(date).format('MM/DD/YYYY')).hours(4).minute(0),
			dateTimelineStartDynamic:moment(moment(date).format('MM/DD/YYYY')).hours(0).minute(0).valueOf(),
			dateTimelineEndDynamic:moment(moment(date).format('MM/DD/YYYY')).hours(4).minute(0).valueOf()
		});
		localStorage.dateTurnDay = date.format('YYYY-MM-DD');
		setTimeout(
			function(){
				$('.react-datepicker-wrapper input').parent().parent().parent().next().focus();
			},800
		),
		this.getReservationsForTimeline(localStorage.dateTurnDay,localStorage.IdZone);
	}
	getToday(){
		this.setState({
			startDate: moment(),
			dateTimelineStart:moment().hours(0).minute(0),
			dateTimelineEnd:moment().hours(4).minute(0),
			dateTimelineStartDynamic:moment().hours(0).minute(0).valueOf(),
			dateTimelineEndDynamic:moment().hours(4).minute(0).valueOf()
		});
		localStorage.dateTurnDay = moment().format('YYYY-MM-DD');
		this.getReservationsForTimeline(localStorage.dateTurnDay,localStorage.IdZone);
	}
	getBeforeDay(){
		let beforeDay = moment(this.state.startDate).add(-1,'day');
		this.setState({
			startDate: moment(beforeDay),
			dateTimelineStart:moment(moment(beforeDay).format('MM/DD/YYYY')).hours(0).minute(0),
			dateTimelineEnd:moment(moment(beforeDay).format('MM/DD/YYYY')).hours(4).minute(0),
			dateTimelineStartDynamic:moment(moment(beforeDay).format('MM/DD/YYYY')).hours(0).minute(0).valueOf(),
			dateTimelineEndDynamic:moment(moment(beforeDay).format('MM/DD/YYYY')).hours(4).minute(0).valueOf()
		});
		localStorage.dateTurnDay = beforeDay.format('YYYY-MM-DD');
		this.getReservationsForTimeline(localStorage.dateTurnDay,localStorage.IdZone);
	}
	getAfterDay(){
		let afterDay = moment(this.state.startDate).add(1,'day');
		this.setState({
			startDate:afterDay,
			dateTimelineStart:moment(moment(afterDay).format('MM/DD/YYYY')).hours(0).minute(0),
			dateTimelineEnd:moment(moment(afterDay).format('MM/DD/YYYY')).hours(4).minute(0),
			dateTimelineStartDynamic:moment(moment(afterDay).format('MM/DD/YYYY')).hours(0).minute(0).valueOf(),
			dateTimelineEndDynamic:moment(moment(afterDay).format('MM/DD/YYYY')).hours(4).minute(0).valueOf()
		});
		localStorage.dateTurnDay = afterDay.format('YYYY-MM-DD');
		this.getReservationsForTimeline(localStorage.dateTurnDay,localStorage.IdZone);
	}
	itemRenderer({item}){
		console.log('item',item)
		return (
			<div style={{ background: item.esee }} className="reservationBox">
				<i className={item.advance_state == '' ? 'icon-'+statusIcons[item.state] : 'icon-'+item.advance_state.toLowerCase()}></i>
				<span style={{ fontWeight: 600 }}></span>
				<span style={{ textDecoration: "none" }}>{item.title}</span>
				<span style={{ textDecoration: "none", float:"right" }}><i className="icon-usuario" aria-hidden="true"></i>{item.paxs}</span>
			</div>
		);
	}
	groupRederer({group}){
		return (
			<div className="custom-group" data-table={group.id} onClick={()=>this.clickTable(group.id)}>
				<div className="row">
					<span className="title col-md-6">{group.title} </span>
					<span className="tip col-md-6">{group.maxPax}</span>
				</div>
			</div>
		)
	}
	clickTable(idTable){
		console.log('table',idTable)
	}
	cursorAct(group,time,param2){
		console.log('Canvas context menu',group.target, moment(group).format('DD-MM-YYYY HH:mm'), moment(time).format('DD-MM-YYYY HH:mm'),param2)
	}
	moveResizeValidator(action, item, time){
		console.log('touch parte')
    if (time < new Date().getTime()) {
      var newTime =
        Math.ceil(new Date().getTime() / (15 * 60 * 1000)) * (15 * 60 * 1000)
      return newTime
    }
    return time
  }
	remderTimeLine(){
		let {
			dateTimelineStart,
			dateTimelineEnd,
			dateTimelineStartDynamic,
			dateTimelineEndDynamic,
			groups,
			items
		} = this.state;
		return(
			<Timeline
				sidebarWidth={148}
				sidebarContent={<div className="reservation__label"><div className="row"><div className="col-md-6">Mesa</div><div className="col-md-6">Max</div></div></div>}
				//headerRef={this.handleHeaderRef}
				keys={keys}
				groups={groups}
				groupRenderer={this.groupRederer}
				items={items}
				itemRenderer={this.itemRenderer}
				itemHeightRatio={0.98}
				dragSnap={30 * 60 * 1000}
				lineHeight={35}
				canMove={false}
				canResize={false}
				itemTouchSendsClick={false}
				canvasTouchSendsClick={false}
				minZoom={60 * 60 * 1000 * 4}
				maxZoom={60 * 60 * 1000 * 4}
				onTimeChange={this.onScroll}
				defaultTimeStart={dateTimelineStart}
				defaultTimeEnd={dateTimelineEnd}
				visibleTimeStart={dateTimelineStartDynamic}
				visibleTimeEnd={dateTimelineEndDynamic}
				onItemSelect={this.clickItem}
				onCanvasClick={this.clickCanvasRow}
				>
			</Timeline>
		)
	}
	handleCloseModal(){
		this.setState({showChangeState:false});
	}
	renderModalReservationTable(){
		const combinedTables = this.state.combinedTables;
		let childs = $('.rct-horizontal-lines').children();
		let childsParent = $('.rct-sidebar > div').children()
		childsParent.map((idx,elem)=>{
			let test = childs[idx]
			$(test).attr('data-id',$(elem).children()[0].dataset.table)
		})
		return (
			<ReactModal isOpen={this.state.showChangeState} className="Modal Modal_select modal_timeline_box" contentLabel="modal-select" overlayClassName="Overlay">
				<div className="modal-header">
					<div className="modal-title">¿Qué desea hacer?</div>
					<button className="modal-close" onClick={this.handleCloseModal}>
						<span className="icon-cancel"></span>
					</button>
				</div>
				{this.state.loadingModal ? <Spinner/> :
					<div className="select_option_assign modal_timeline">
							{this.state.selectTableOpen ? <h6>{this.state.selectTableOpen.date} - {this.state.selectTableOpen.hour}</h6>:''}
							<div className="form-group">
								<div className="select-arrow">
									<select className="form-control" onChange={this.onChangeCombined}>
										<option value={''}>Mesas disponibles, selecciona una:</option>
									{this.state.selectTableOpen ?
										(
										<option data-name={this.state.selectTableOpen.title} value={this.state.selectTableOpen.id}>{this.state.selectTableOpen.title} (Min {this.state.selectTableOpen.minPax} - Max {this.state.selectTableOpen.maxPax})</option>
										):''}
									{combinedTables.map((elem,idx)=>{
										return(
											<option key={idx} data-name={elem.title} value={elem.id}>{elem.title} (Min {elem.minPax}- Max {elem.maxPax})</option>
										)
									})}
									</select>
								</div>
							</div>
						<ul>
							<li>
								<button type="button" disabled={this.statebuttonDisabled} onClick={()=>this.clickSelect('walk-in')} className="btn btn-default">
									Walk-in{/*this.state.infoTableEmpty.Descripcion*/}
								</button>
							</li>
							<li>
								<button type="button" disabled={this.statebuttonDisabled} onClick={()=>this.clickSelect('reserva')} className="btn btn-default">
									Reservar{/*this.state.infoTableEmpty.Descripcion*/}
								</button>
							</li>
						</ul>
					</div>
				}
			</ReactModal>
		)
	}
	render(){
		let groupsLets = this.state.groups;
		this.createIntervals()
		return(
			<div className="new_time_line">
				<AuthValidate/>
				<HeaderSection history={this.props.history} getToday={this.getToday} getBeforeDay={this.getBeforeDay} getAfterDay={this.getAfterDay} title={this.props.local.Nombre} handleNavigation={this.props.handleNavigation}/>
				<div className="container_timeline">
					<div className="title_timeline">
						{this.renderZoneList()}
					</div>
					<div className="container_timeline_box">
						{groupsLets ? <div className="ctn_timeline">{this.remderTimeLine()}</div>: <Spinner/>}
					</div>
				</div>
				{this.renderModalReservationTable()}
			</div>
		)
	}
}
`

**Comment by Ilaiwi** [comment]
could you please add your code to a sandbox? 
this would be a good starting point
https://codesandbox.io/s/zr5r289rm4

**Comment by Ilaiwi** [comment]
no sandbox was provided

**Comment by BottlecapDave** [comment]
Hello. Sorry to resurect an old bug, but I too am exeriencing this issue with both `onCanvasClick` and `onCanvasDoubleClick`.

Here is a sandbox, which when the timeline is double clicked an alert dialog will appear on desktop, but not ipad.

https://codesandbox.io/embed/n3847vqpx0
