### ISSUE TITLE
 How can I change calendar data from a picker?

### ISSUE THREAD

**Issue by danielmorine** [namespace-ee/react-calendar-timeline#413]
Hello! 
For example, I have a selector and it is controlled by my state this.state.selectDay. I looked in the documentation and in the examples, however, I did not find any component that I could program and put this date control in my calendar. I'm looking for something like: <Timeline
..
**defaultTimeStart** = {moment (). add (-12, 'hour')}
**defaultTimeEnd** = {moment (). add (12, 'hour')}
**date** = {this.state.selectDay}/>

**Comment by Ilaiwi** [comment]
you can do that via visibletimestart and visibletimeend
https://github.com/namespace-ee/react-calendar-timeline#visibletimestart-and-visibletimeend

**Comment by danielmorine** [comment]
It worked, but there is a bug happening, the calendar always brings the information from the previous day. I created two constants and put my state formatted with the momentjs. Debugging through the Google console, the date is right. This is my code:

`        const defaultTimeStart = moment(this.state.selectedDay).startOf('day').toDate();`
      `  const defaultTimeEnd = moment(this.state.selectedDay).startOf('day').add(1, 'day').toDate();`


                    <Timeline
                       stickyHeader={true}
                        itemRenderer={this.itemRenderer}
                        sidebarContent={<div><br></br><div align="center">Status</div></div>}`
                        groups={this.state.groups}
                        canMove={false}
                        canResize={false}
                        items={this.state.eventsFiltereds}
                        onItemClick={(events) => this.openModal(events)}
                        onItemSelect={(events) => this.openModal(events)}
                        visibleTimeStart={defaultTimeStart}
                        visibleTimeEnd={defaultTimeEnd}>  

Do you know what could be happening? 

[https://ibb.co/c1y5QK](url)

**Comment by Ilaiwi** [comment]
Please provide a codesandbox example of your problem.
this is a good starting point https://codesandbox.io/s/zr5r289rm4

**Comment by danielmorine** [comment]
Now it's working. This problem was happening because the Timeline items object was empty. The solution was very simple, I created a fake item and a condition to verify whether it has information or not, if in case it will display my data, if not, it will render my fake data but without displaying it.

Below is an example with a datepicker:
https://codesandbox.io/s/zn07w79z3l

**Comment by Ilaiwi** [comment]
Oh yes! this is related to this #393. Glad you found the solution
