### ISSUE TITLE
Is there anyway to prevent onCanvasClick event when dragging the timeline?

### ISSUE THREAD

**Issue by beeant** [namespace-ee/react-calendar-timeline#42]
I'm using `onCanvasClick` to add and `item` however the `onCanvasClick` is always triggered even when dragging the timeline to move the bounds.
Is there anyway to prevent this?

Thank you in advance!

**Comment by mariusandra** [comment]
Now in v0.9.0 it's possible. There's a new prop `clickTolerance` that sets how many pixels of dragging still counts as a click
