### ISSUE TITLE
Additional information showing on hover

### ISSUE THREAD

**Issue by renatas7** [namespace-ee/react-calendar-timeline#423]
**Is your feature request related to a problem? Please describe.**
Would it be possible to show additional information on bar hover?

**Describe the solution you'd like**
It would be nice to see for example start time and end time just by hovering the bar in the tooltip.

**Comment by Ilaiwi** [comment]
Hi @renatas7, This is not possible in the current API, however, this is a very useful feature that could be added to the API. If you have the time please feel free to submit a PR adding this.
I would suggest using renderProps to implement some prop called `infoLabelRenderer` or whatever you deem appropriate

**Comment by acemac** [comment]
I believe this can be achieved using the itemRenderer.

By rendering the item as something that responds to hover you can get this information out and display it how you see fit.

[You could use something like React Semantic Popup](https://react.semantic-ui.com/modules/popup/#usage-nested)

**Comment by ArunChockalingam** [comment]
I got this to work and here is the skeleton of what is needed. For this to work correctly , have the below code in a separate component and return this component in the item renderer method

In the item Renderer:
` 
<div
        {...getItemProps({
          style: {
            background,             
            color,
            borderColor,
            boxShadow,
            borderStyle: "solid",
            borderWidth: 1,
            borderRadius: 4,
            borderLeftWidth: itemContext.selected ? 3 : 1,
            borderRightWidth: itemContext.selected ? 3 : 1
          }          
        })}
        onMouseEnter={() =>{
          this.setState({ showModal: true })
        }}
        onMouseLeave={() =>{
          this.setState({ showModal: false })
        }}
        onClick={() =>{
          this.setState({ showModal: false })
        }}        
      >   
        <div
          style={{
            height: itemContext.dimensions.height,
            overflow: "hidden",
            marginLeft: '10px',
            paddingLeft: 3,
            textOverflow: "ellipsis",
            lineHeight: '20px',
            marginTop: '15px'
          }}
        >
          {itemContext.title}                                     
        </div>

        {this.state.showModal &&
          <div className="itemModal" style={{
            left: left,
            right: right
          }}>
            **modal content goes here**                     
          </div>
        }  
      </div> `

Style:

`.itemModal{
  background-color: #fefefe;  
  padding: 0px 20px 0px 20px;
  border: 1px solid #ccc;  
  border-radius: 8px;
  color: rgb(62, 62, 60);
  max-width: 400px;
  min-width: 250px;
  line-height: 40px;  
  position: absolute;
  z-index: 100;
  box-shadow: 5px 5px #E2E2E3;
}`

**Comment by Ilaiwi** [comment]
maybe I didn't get what the issue was referring I understood it to be about the hover bar that appears when you move or resize an item. 
@renatas7 could you please provide more context

**Comment by renatas7** [comment]
I mean just showing some additional content, for example bars start time and end time, on  hover. Not on action(move or resize). Now it's just appears standart browsers tooltip with bars title.

**Comment by Ilaiwi** [comment]
@renatas7 then the example @ArunChockalingam should do the trick. ItemRendere is the solution
