### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by WebspressoCo** [namespace-ee/react-calendar-timeline#425]
**Describe the bug**
One of the CodeSandbox examples returns an error. The example is listed here: https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples#custom-item-rendering-using-timelinecontext---conditionally-render-components

**To Reproduce**
Codesandbox example link: https://codesandbox.io/s/r74qoxw94p

I haven't looked into the issue, as I'm just trying to select a library so far.

**Comment by Ilaiwi** [comment]
the problem is that you are passing a class react component as a prop to `itemRenderer` where you should pass a function as explained [here](https://github.com/namespace-ee/react-calendar-timeline#itemrenderer)

**Comment by WebspressoCo** [comment]
Thank you for checking this out,

I ended up selecting a different library but I wanted to help you improve your docs/examples.

**Comment by Ilaiwi** [comment]
thanks
