### ISSUE TITLE
Support right-to-left timeline

### ISSUE THREAD

**Issue by yotamberk** [namespace-ee/react-calendar-timeline#428]
It would be awesome if right-to-left support was enabled.

Maybe simply by adding `dir='rtl'` to the html tag or with an `isRtl` option

This would be useful for languages that are right to left like Hebrew and Arabic

**Comment by mcMickJuice** [comment]
I'm sorry but this is too specific of a use case for us to take this in.  If you'd like to implement and create a PR and that PR gains enough interest, we can look at it.

**Comment by rwaidaAlmehanni** [comment]
When add the dir=rtl or using the moment the style of the time line has an issue and things not working fine

**Comment by omrikapara1** [comment]
Hi, is there any progress on the rtl timeline?
I think it's a great feature and necessary one....

**Comment by MrPoint1400** [comment]
+1
