### ISSUE TITLE
Can You load builded css instead of scss file (Timeline.scss)?

### ISSUE THREAD

**Issue by jerryslaw** [namespace-ee/react-calendar-timeline#43]
`ERROR in ./~/react-calendar-timeline/modules/lib/Timeline.scss
    Module parse failed: /home/jarek/workspace/itv-cms-renderer/node_modules/react-calendar-timeline/modules/lib/Timeline.scss Line 1: Unexpected token :
    You may need an appropriate loader to handle this file type.
    | $item-color: white;
    | $item-background: #2196F3;
    | $item-border: 1px solid #1A6FB3;
     @ ./~/react-calendar-timeline/modules/lib/Timeline.js 19:0-26`

This case was discussed once, but I want to bring it up once more. 
In my project there are no scss files, I'm using stylus. I don't want unnecessary sass loaders. Please tell me why not to load builded css file?

**Comment by eamonpenland** [comment]
I'm having the same issue. Any thoughts?

**Comment by nikkiczx** [comment]
I'm facing something similar...

Uncaught Error: Cannot find module './Timeline.scss'

**Comment by mariusandra** [comment]
Hey, feel free to submit a PR that compiles the scss into a css for the modules folder

**Comment by mariusandra** [comment]
The build modules now contain a .css file.
