### ISSUE TITLE
Dragging item out of current view

### ISSUE THREAD

**Issue by ArunChockalingam** [namespace-ee/react-calendar-timeline#435]
Is there a way to drag an item out of the current view ? For example, in code sandbox, https://codesandbox.io/s/6vo2jkov23

1. Zoom in a little bit, so the entire timeline is about 8 hours or so at a time.
2. Now drag any item to the end of the day or to tomorrow.

as the item gets close to the end of the current view, you are able to scroll the timeline with the trackpad while still dragging the item, but it becomes very hard after the first time.

It does not seem possible to me to drag an item to the next day in this view without dropping and dragging multiple times.

Things i tried:

1. I tried using the scrollRef inside the MoveResizeValidator to try to scroll the timeline automatically after the item has been dragged more than 2 hours or multiples of 2 hours, but the behavior does not seem very friendly.

2. I also tried the onBoundsChange prop, but this seems to fire only after dropping the currently dragged item and not while dragging.

Any suggestions or alternatives to achieve this would be greatly appreciated! Thanks!

**Comment by acemac** [comment]
@ArunChockalingam I believe this is a bug I have tried to address with #427

**Comment by ArunChockalingam** [comment]
@acemac thank you! 
@Ilaiwi will this get into the next version?

**Comment by Ilaiwi** [comment]
@ArunChockalingam I will try to do so. I just need to resolve something first that has to do with releases

**Comment by Ilaiwi** [comment]
@ArunChockalingam released with `0.22.0`

**Comment by ArunChockalingam** [comment]
@Ilaiwi Thanks a lot! will try it out

**Comment by janakact** [comment]
@ArunChockalingam, It would be great if you can share us how did you manage to do this? 

I tried with onDrag event, and managing `visibleTimeStar` and `visibleTimeEnd`, but didn't work as expected. 

Thanks in advance.
