### ISSUE TITLE
Uncaught Error: Consumer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

### ISSUE THREAD

**Issue by mousumi-dualcube** [namespace-ee/react-calendar-timeline#438]
Getting bellow error -

> Uncaught Error: Consumer.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

I am getting this error when I am starting the npm by "npm start". Please follow the below file. And suggest me the issue. It seems timeline component returning null.

**Index file -**
import React from 'react'
import ReactDOM from 'react-dom'
import Timeline from 'react-calendar-timeline'
// make sure you include the timeline stylesheet or the timeline will not be styled
import 'react-calendar-timeline/lib/Timeline.css'
import moment from 'moment'

const groups = [{ id: 1, title: 'group 1' }, { id: 2, title: 'group 2' }]

const items = [
  {
    id: 1,
    group: 1,
    title: 'item 1',
    start_time: moment(),
    end_time: moment().add(1, 'hour')
  },
  {
    id: 2,
    group: 2,
    title: 'item 2',
    start_time: moment().add(-0.5, 'hour'),
    end_time: moment().add(0.5, 'hour')
  },
  {
    id: 3,
    group: 1,
    title: 'item 3',
    start_time: moment().add(2, 'hour'),
    end_time: moment().add(3, 'hour')
  }
]

ReactDOM.render(
  <div>
    Rendered by react!
    <Timeline
      groups={groups}
      items={items}
      defaultTimeStart={moment().add(-12, 'hour')}
      defaultTimeEnd={moment().add(12, 'hour')}
    />
  </div>,
  document.getElementById('app')
)

**webpack file -**
var HtmlWebpackPlugin = require('html-webpack-plugin');
var HtmlWebpackPluginConfig = new HtmlWebpackPlugin({
  template: __dirname + '/app/index.html',
  filename: 'index.html',
  inject: 'body'
})

module.exports = {
  entry : [
    './app/index.js'
  ],
  output : {
    path: __dirname + '/dist',
    filename: "index_bundle.js"
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy'],
        }
      },
      { 
        test: /\.css$/, 
        loader: "style-loader!css-loader" 
      }, 
    ]
  },
  resolve: {
    extensions: ['.js', '.jsx', '.css'],
    modules: [
      'node_modules'
    ]        
  },
  plugins: [HtmlWebpackPluginConfig]
}

**package.json-**

{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server",
    "prod": "webpack -p"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-plugin-react-html-attrs": "^2.1.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-react": "^6.23.0",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.26.4",
    "html-webpack-plugin": "^2.28.0",
    "interactjs": "^1.3.4",
    "moment": "^2.22.2",
    "react-calendar-timeline": "^0.19.0",
    "react-html-attributes": "^1.4.3",
    "style-loader": "^0.23.0",
    "webpack": "^2.2.1",
    "webpack-dev-server": "^2.4.1"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  }
}

**babelrc -** 

{
  "presets": [
    "react",
    "babel-preset-es2015"
  ]
}

**Comment by ArunChockalingam** [comment]
@mousumi-dualcube i do not think this this is a react calendar timeline issue as you are not using the timeline component anywhere except for importing it.

I was able to load your index file fine without any issues, had to wrap your "Rendered by React!" string in quotes. So your issue must be in some other file?

**Comment by mousumi-dualcube** [comment]
Sorry. My bad. I am facing the issue with following code -

**Index.js** 

import React from 'react'
import ReactDOM from 'react-dom'
import Timeline from 'react-calendar-timeline/lib'
// make sure you include the timeline stylesheet or the timeline will not be styled
import 'react-calendar-timeline/lib/Timeline.css'
import moment from 'moment'

const groups = [{ id: 1, title: 'group 1' }, { id: 2, title: 'group 2' }]

const items = [
  {
    id: 1,
    group: 1,
    title: 'item 1',
    start_time: moment(),
    end_time: moment().add(1, 'hour')
  },
  {
    id: 2,
    group: 2,
    title: 'item 2',
    start_time: moment().add(-0.5, 'hour'),
    end_time: moment().add(0.5, 'hour')
  },
  {
    id: 3,
    group: 1,
    title: 'item 3',
    start_time: moment().add(2, 'hour'),
    end_time: moment().add(3, 'hour')
  }
]

ReactDOM.render(
  <div>
    Rendered by react!
    <Timeline
      groups={groups}
      items={items}
      defaultTimeStart={moment().add(-12, 'hour')}
      defaultTimeEnd={moment().add(12, 'hour')}
    />
  </div>,
  document.getElementById('app')
)

**Comment by mousumi-dualcube** [comment]
Hi,
This issue get resolved with 0.17.0 version of react-calendar-timeline. I think current version is not supporting with react version. But I need another help. On first click, we select the item and onitemClick event fire on second click. So can we skip the select event and fire click event on first click ?
Please help.

**Comment by dkarnutsch** [comment]
@mousumi-dualcube 
There is a property called [itemTouchSendsClick](https://github.com/namespace-ee/react-calendar-timeline#itemtouchsendsclick) for that.

**Comment by mousumi-dualcube** [comment]
Sorry, I have tried with below code. But again it is not working. First item select get called after that item click is called.

`<Timeline
          groups={groups}
          items={items}
          keys={keys}
          itemRenderer={this.itemRenderer}
          groupRenderer={this.groupRenderer}
          sidebarWidth={0}
          sidebarContent={<div style={{textAlign: 'center'}}>Survey</div>}
          itemsSorted
          itemTouchSendsClick={true}
          stackItems
          itemHeightRatio={.8}
          showCursorLine
          canMove={false}
          canResize={false}
          defaultTimeStart={defaultTimeStart}
          defaultTimeEnd={defaultTimeEnd}
          onItemClick={this.onItemClick}
        >
        </Timeline>`

**Comment by dkarnutsch** [comment]
@mousumi-dualcube 
Please create a minimal code sandbox showing the problem.

**Comment by Ilaiwi** [comment]
@mousumi-dualcube itemRendere will solve your issue using `propGetter`
this example has your requirement https://codesandbox.io/s/1p8m477w7
if you have other questions please open another issue
