### ISSUE TITLE
InfoLabel shows [object Object] in tree group when dragging items

### ISSUE THREAD

**Issue by thiagosatoshi** [namespace-ee/react-calendar-timeline#442]
**Describe the bug**

An InfoLabel is displayed when an item is being dragged. When using tree groups, the InfoLabel shows [object Object].

The reason is because the Sidebar and the InfoLabel both use the groupTitleKey to render themselves, but the groupTitleKey can point to a React element for the Sidebar. This is used in the tree group functionality, to simulate collapsing/expanding of the group in the side bar.

**To Reproduce**

Run the demos in the project.
Go to the tree groups demo (https://codesandbox.io/s/k9qyx9zp2o)
Move one of the items.
Observe that the tooltip in the bottom left corner ends in [object Object]

**Expected behavior**

The tooltip should show a suitable text string, for example the title of the group.

**Screenshots**

![timeline bug](https://user-images.githubusercontent.com/2606961/46619323-bb316e80-cb19-11e8-950e-01f0295ec384.png)

**Library Version**

0.20.0

**Desktop (please complete the following information):**

* OS: Windows 10
* Browser: Chrome
* Version: 69.0.3497.100

**Additional context**

The fix involves introducing a new key in the Timeline keys object called `groupLabelKey`, which is defaulted to `title`. This will preserve existing functionality. When the `groupLabelKey` is specified to point to a string attribute of the group object, that is used to render the text in the InfoLabel.

This allows the developer to split what is used to render the Sidebar with what is used to render the InfoLabel.

**Comment by Ilaiwi** [comment]
released in 0.22.0
