### ISSUE TITLE
Warning: You are manually calling a React.PropTypes

### ISSUE THREAD

**Issue by gunosk129** [namespace-ee/react-calendar-timeline#45]
I use react v 0.14.8 and I got these error. but when I use react v^15.0.0 it work fine, but I got `peerDependencies` errors. Do you have Any ideas to solve it?
![screen shot 2559-08-19 at 2 13 37 pm](https://cloud.githubusercontent.com/assets/13390655/17801976/8cf1d000-6617-11e6-8d9b-e2d5aaef187c.png)

**Comment by mariusandra** [comment]
Hi, no clue :). It works for me with v15. Perhaps PR #53 fixed it?
