### ISSUE TITLE
Items are not dragged. And the layout of the timeline is a bit broken.

### ISSUE THREAD

**Issue by tony-show** [namespace-ee/react-calendar-timeline#451]
Hello!
I used to start create-react-app, but after insstall and start project, i look for this problems:
1 - Items are not dragged and resizing. 
2 - And the layout of the timeline is a bit broken.

This is gif screencast for a problem - https://svoywebsayt.ru/gif.gif

Anybody know what this happenes? Thank, you lot!

**Comment by Ilaiwi** [comment]
@tony-show could you please follow the issue template and provide a codesandbox for your issue

**Comment by Reixko** [comment]
Hello, @acemac I have the same issue when resizing items, but I'm handling callbacks. Do you think that can be a bug ? Also, there is that exact issue in the Demo about Moving and resizing on the front page.

**Comment by acemac** [comment]
Thank you @Reixko 

RCT now depends on React 16.3 or greater. In the example it is using React 16.0.

After upgrading the [example ](https://codesandbox.io/s/lx91k4wpz) to 16.3 it is working a bit better.

**Comment by Ilaiwi** [comment]
peer dependency added
