### ISSUE TITLE
import * will not work

### ISSUE THREAD

**Issue by maxlibin** [namespace-ee/react-calendar-timeline#453]
```
import * as Timeline from 'react-calendar-timeline';
```
I am binding this to reasonml, and with es6 module, it imports * as default way, but this will not work?

**Comment by Ilaiwi** [comment]
this will not work because we use the default export to export the timeline and we use named exports to export marker's components. 
not sure how to deal with default exports in reasonml but please if you figured it out share the solution with us herer

**Comment by maxlibin** [comment]
ok I can import default from reason side:

```
[@bs.module "react-calendar-timeline"]
external reactClass: ReasonReact.reactClass = "default";
```
