### ISSUE TITLE
Today Marker Styling

### ISSUE THREAD

**Issue by ifordesmith** [namespace-ee/react-calendar-timeline#454]
How can you set the style of the Today Marker Line - I've tried setting in line styles on <TodayMarker> but it still defaults to Black ?

I can see in your implementation the colour is set to Black but I'd like to control this.

**Comment by jarnovanrhijn** [comment]
Try adding the following within <Timeline> component

https://codesandbox.io/s/lxlnjz36wm

> 
              <TodayMarker>
                {({ styles }) => (
                  <div style={{ ...styles, backgroundColor: 'green' }} />
                )}
              </TodayMarker>
