### ISSUE TITLE
 [Possible] Disable the click on the header?

### ISSUE THREAD

**Issue by danielmorine** [namespace-ee/react-calendar-timeline#464]
Hello!

I have a question: can I disable the click on the header to not change the time and date? I have a mini calendar that makes date change and I want to remove this click on the timeline header. 
I looked at the documentation but could not find a solution.

Thanks for the help!

**Comment by Ilaiwi** [comment]
@danielmorine this will officially drop when #349 finishes but for now, you can do that using `onTimeChange` since it is called when you click the header and you can block the change from there

**Comment by danielmorine** [comment]
Perfect, it's working the way I want it to. Thanks for your help one more time!
