### ISSUE TITLE
Scrolling in real time.

### ISSUE THREAD

**Issue by JaredDiCioccio** [namespace-ee/react-calendar-timeline#466]
I know you can scroll programatically with `scrollRef.scrollLeft`, but is there any built in way to scroll in real time? essentially so regardless of zoom level "Now" would always be in the center of the viewport? Essentially making a real time animated timeline.

**Comment by acemac** [comment]
You could scroll in real time quite easily.

[Take a look at this](https://codesandbox.io/s/1y7no02j2l)

I've had a go with the example you provided in your other question. I had to upgrade React to 16.3. When you click the button it should start 'scrolling'. You could put this code in componentDidMount. You should also keep the reference to the interval and clean it up if the component unmounts.

**Comment by Ilaiwi** [comment]
@acemac thanks for helping
