### ISSUE TITLE
prevent stack elements from crossing and overlapping?

### ISSUE THREAD

**Issue by tony-show** [namespace-ee/react-calendar-timeline#467]
Hello everybody!
Is there any way to prevent stack elements from crossing and overlapping???

Thanks for answers!

**Comment by acemac** [comment]
If the items already overlap they will be rendered as such.

If you want to stop the user from dragging or resizing an item to overlap you could use [moveResizeValidator](https://github.com/namespace-ee/react-calendar-timeline#moveresizevalidatoraction-itemid-time-resizeedge)

**Comment by Ilaiwi** [comment]
@tony-show Please follow the issue template and provide more description on what you are asking

**Comment by tony-show** [comment]
@Ilaiwi
When i try drag item to date-time another item, making crossings items or draging item jump to new line. 

How i can prevent crossings or overlappings items in one zone date-time, to make the dragged item jump to the intersected item before or after it?

Looking this problem in gif video (!calendar modify view): https://svoywebsayt.ru/corssing_items.gif

**Comment by Ilaiwi** [comment]
by using [moveresizevalidatoraction](https://github.com/namespace-ee/react-calendar-timeline#moveresizevalidatoraction-itemid-time-resizeedge)

you this callback will fire on every move/resize. the return value will determine if the item should be moved to its new dragging position or not

**Comment by tony-show** [comment]
@Ilaiwi Thank you!
