### ISSUE TITLE
StackElements does not work with Date Objects

### ISSUE THREAD

**Issue by sm1ddy** [namespace-ee/react-calendar-timeline#473]
I've noticed that StackItems does not work when trying to use Date Objects on items. On the other hand, using moment seems to work.

**Comment by Ilaiwi** [comment]
you can either use moment or UNIX milliseconds only we dont support native date

**Comment by tyson-kubota** [comment]
I also ran into this issue; it should be mentioned in the documentation for clarity. I'll open a PR.
