### ISSUE TITLE
How to re-render the component when changing locale?

### ISSUE THREAD

**Issue by brightMarco** [namespace-ee/react-calendar-timeline#475]
I'm having some trouble with changing locales. I have the Timeline running with default english but when I change language the component doesn't update the labels to the new language until I scroll a bit to make it re-render or until I refresh the page. I've searched the documentation but found no way to make the component re-render when I change the locale on componentDidUpdate(). Any way to deal with this?

**Comment by Ilaiwi** [comment]
you can pass new items kist or group when changing the local that will definitely help

**Comment by diegocasmo** [comment]
I'm having the same issue. The secondary header (which uses a unit of "week") isn't correctly updated when moment's first day of the week is updated according to locale. 

As suggested, I tried changing the items/groups when this event happens, but it didn't work. Manually resizing the timeline (by changing the browser's window size) does make it correctly re-render.

What other possible solutions could you suggest? @Ilaiwi

**Comment by bitshadow** [comment]
Couldn't find better solution for this. So I decided to force render the view for time being.
```
componentDidUpdate(prevProps, prevState) {
    const { locale: prevLocale } = prevProps
    const { locale } = this.props
    if (!isEqual(prevLocale, locale)) {
      this.setState({ refreshing: true })
      const self = this;
      setTimeout(() => {
        self.setState({ refreshing: false })
      }, 0)
    }
  }
  ```
  ```
   return (
      <>
         { !this.state.refreshing && <Timeline ... /> }
      </>
   )
  ```
