### ISSUE TITLE
The sidebar re-render's even when group heights do not change

### ISSUE THREAD

**Issue by SDupZ** [namespace-ee/react-calendar-timeline#478]
**Describe the bug**
The sidebar will re-render even when the groupHeights prop passed into the sidebar component has the same values inside the array.
This causes an unnecessary re-render of the sidebar when zooming in or out.

**To Reproduce**

1. On master, add the following snippet to `lib/layout/Sidebar.js`
```
componentDidUpdate(prevProps) {
    Object.keys(this.props).forEach((key) => {
      if (this.props[key] !== prevProps[key]) {
        console.log(key, 'changed from', prevProps[key], 'to', this.props[key]);
      }
    });
  }
```

2. Zoom out to the top-level zoom. Zoom one level in.
3. The values in the groupHeights array in the console will be equal yet the sidebar component will re-render.

**Expected behavior**
Sidebar does not re-render

**Library Version**
Latest master (commit 9c56a25c3ab598ee2f0d441622bc5c1ac1e06c59)

**Desktop (please complete the following information):**

* OS: iOS 10.14
* Browser: Chrome 70.0.3538.110

**Additional context**
I will create a PR to address this. 👍

**Comment by Ilaiwi** [comment]
released in 0.23.0
