### ISSUE TITLE
Vertical column for time.

### ISSUE THREAD

**Issue by stasrdv** [namespace-ee/react-calendar-timeline#481]
**Is your feature request related to a problem? Please describe.**
Is there any option rotate the calendar so the hours would be on the left and the column of the 'groups' on top ?

**Describe the solution you'd like**
Both vertical and horizontal view.

**Comment by dkarnutsch** [comment]
Until July it was not planned. See: https://github.com/namespace-ee/react-calendar-timeline/issues/370

**Comment by Ilaiwi** [comment]
as @dkarnutsch said there is no current plan to implement this. If you want to start with it and add it as a feature please feel free to open a PR to do so.
