### ISSUE TITLE
Change infobox that appers when moving an item

### ISSUE THREAD

**Issue by florianbepunkt** [namespace-ee/react-calendar-timeline#482]
**Is your feature request related to a problem? Please describe.**
When dragging an item, an info box appears on the bottom left corner of the screen. I would like to format the content. In my case the day in the date is irrelevant, so therefore I would like to only show the time in HH:mm format. Also I would like to add/change content based on the group.

**Describe the solution you'd like**
Provide a function to timeline that accepts the data displayed as input and expects an React element to be returned.

**Comment by trevdor** [comment]
This predates #517, but since that issue looks like it may be resolved in code soon, can this one be closed as duplicate?

**Comment by Ilaiwi** [comment]
you can do this now via the new `onItemDrag` prop in 0.26.0 and this example https://codesandbox.io/s/timeline-demo-info-label-neec9 
let me know if you have other questions about usability
@florianbepunkt 
@trevdor yes it should be thanks
