### ISSUE TITLE
Is there any way to change the color of the sidebar and top bar?

### ISSUE THREAD

**Issue by JaredDiCioccio** [namespace-ee/react-calendar-timeline#483]
I cannot find a way to change the red color below to anything else. Is there any way, hacked together or not, to change this color?

![baerwgp](https://user-images.githubusercontent.com/633075/49888884-1af41080-fe0e-11e8-8a26-466b7bcda7eb.png)

**Comment by Ilaiwi** [comment]
you need to override there css rules

**Comment by JaredDiCioccio** [comment]
Thanks for the reply. This is my first big web-dev project so was a little unclear on how to find the correct css selectors.

For anyone else... this was my solution:
```
    <style>
    .react-calendar-timeline .rct-sidebar-header{
      background: #3f51b5
    }
    .react-calendar-timeline .rct-header .rct-label-group{
      background: #3f51b5
    }
    </style>
```
![image](https://user-images.githubusercontent.com/633075/49954937-a2558880-fecf-11e8-9a3a-d3bd7d226269.png)
