### ISSUE TITLE
Calendar lines misaligned with header

### ISSUE THREAD

**Issue by everaldo** [namespace-ee/react-calendar-timeline#487]
**Describe the bug**
Calendar lines are not aligned with header.

Version: 0.22.0

**To Reproduce**

Create a simple calendar without any custom options

**Expected behavior**

Calendar lines should be aligned with header (dates) lines.

**Screenshots**

![issuereactcalendartimeline](https://user-images.githubusercontent.com/892012/50524553-818b5680-0abd-11e9-9cd2-6ed98ccfeb0a.png)

**Library Version**

0.22.0

**Desktop (please complete the following information):**

* OS: Ubuntu 17.10
* Browser Google Chrome
* Version  63.0.3239.132

**Comment by everaldo** [comment]
I was able to fix it when added the props sideBarContent, as showed in the example's page:

https://codesandbox.io/s/w6xvqzno4w

![fixedwhensidebarcontentwasadded](https://user-images.githubusercontent.com/892012/50561842-ddd8bb00-0cf5-11e9-9102-e2b18364bf0f.png)

**Comment by Cyanures** [comment]
Thank it fixed my problem :)
