### ISSUE TITLE
Entire timeline re-renders when you move or resize of item

### ISSUE THREAD

**Issue by uffou** [namespace-ee/react-calendar-timeline#491]
**Describe the bug**
Entire timeline renders when you move or resize an item. I believe this to be the main reason for poor performance during this action.

**To Reproduce**

1. Turn on react render highlights in chrome dev tools
![image](https://user-images.githubusercontent.com/2581788/50896104-b3cb7b00-1410-11e9-95d8-0d9b823e58f7.png)

2. Drag to move or resize an item

**Expected behavior**
I expect only the item being dragged and items that collide with this item to be re-rendered, in some cases the timeline when you get out of bounds and new time needs to be added.

**Screenshots**
![drag](https://user-images.githubusercontent.com/2581788/50896312-571c9000-1411-11e9-8937-d44a7092e8e0.gif)

**Library Version**
all

**Comment by Ilaiwi** [comment]
We are aware of the issue please take a look at #338.
This is how the library work more not just simple optimization problems
