### ISSUE TITLE
Omit hours from the timeline

### ISSUE THREAD

**Issue by dziugas-liaudinskas** [namespace-ee/react-calendar-timeline#493]
I need to implement timeline but it shouldn't show all hours from 00 to 23. For example, I set hours to be shown from 08 to 17 and each day shows only these hours. I searched for examples and looked to the props but couldn't find a solution for that. I found this quite old issue which is related to mine ( #73 ) and there is said that it is not possible, but maybe something changed and this feature is now available?
Thanks

**Comment by Ilaiwi** [comment]
We dont have any plans to do this in the feature. Thank you for the suggestion though
