### ISSUE TITLE
Cant get onTimeChange to work

### ISSUE THREAD

**Issue by ahsnap** [namespace-ee/react-calendar-timeline#50]
I'm wanting to prevent the date range that is visible to the user.  I've set the two attributes for visible start and end dates.  However when trying to set the onTimeChange function using the example with updateScrollCanvas method i don't have access to it.  Since i'm importing Timeline, how would i go about calling that function from within my component?

**Comment by mariusandra** [comment]
Hi, from v0.9.0 on, `onTimeChange` now gets `updateScrollCanvas` as the third argument
