### ISSUE TITLE
Sidebar header with over 60px of height breaks layout

### ISSUE THREAD

**Issue by oskari** [namespace-ee/react-calendar-timeline#501]
**Describe the bug**
Inserting content to sidebar header so that it exceeds 60px of height breaks the timeline header layout

**To Reproduce**
https://codesandbox.io/s/2o6jnpyvqy

**Expected behavior**
Timeline header to align on the bottom of the container, not top of the container

**Screenshots**
![Screenshot of the problem](https://i.imgur.com/3LXu3hs.png)

**Library Version**
0.23.0

**Comment by Ilaiwi** [comment]
@oskari this is now supported with custom headers
https://github.com/namespace-ee/react-calendar-timeline#dateheader
