### ISSUE TITLE
Page scrollbar appearing causing break of calendar layout

### ISSUE THREAD

**Issue by lukasirsak** [namespace-ee/react-calendar-timeline#506]
**Describe the bug**
I've got timeline in responsive layout (width of parent element is set to 100% of page). Timeline have sidebar which have clickable categories which will expand creating new lines, when users clicks on them. When I am expanding categories and I reach point where page scrollbar should appears the timeline break's it's layout. Sidebar stays where it should be, but grid is pushed to new line bellow sidebar. 

**To Reproduce**
I was only able to reproduce this behaviour on Windows 10 machine running Chrome, Opera or Firefox. Everything works fine on MacOS machines.

Here is a gif:
![timeline](https://user-images.githubusercontent.com/30669262/52128227-ae8ad600-2634-11e9-81f3-2b5af83c7519.gif)

Reoad page, opening categories, reaching point where scrollbar appears and grid goes down, open element inspector and everything is fine again.

**Expected behavior**
There should be some kind of re-render function fired up when sidebar changes. Like when element inspector is opened (everything returns to normal, like in gif). 

**Library Version**
react-calendar-timeline@^0.22.0:
  version "0.22.0"
  resolved "https://registry.yarnpkg.com/react-calendar-timeline/-/react-calendar-timeline-0.22.0.tgz#4c832398ebdae0ed1d19a320f7b58c7f26b7158e"
  integrity sha512-jF+jB6+/SWxtvRA0fWkheQz6StqV244wUX6gKtvOkOGNdZl1ACw7Fy+cY9aT4D858JIheu2WsjPKzwySrxqHLQ==
  dependencies:
    create-react-context "^0.2.2"
    element-resize-detector "^1.1.12"
    lodash.isequal "^4.5.0"

**Desktop:**

* OS: Windows 10
* Browser: Chrome, Opera, Firefox

**Additional context**
When I set parent element's width to for example 1000px, everything is ok when sidebar appears. 

Quick workaround is to just add `min-height: 101vh` to parent element, which is what I did to quickfix this.

**Comment by Ilaiwi** [comment]
could you please provide codesandbox example?

**Comment by Ilaiwi** [comment]
@lukasirsak

**Comment by lukasirsak** [comment]
@Ilaiwi I will make you codepen ASAP (tomorrow).

**Comment by lukasirsak** [comment]
@Ilaiwi I was able to reproduce this bug [here](https://codesandbox.io/s/l95n09oywl ).

In Chrome on Mac everything is OK.
In Chrome on Windows 10 layouts breaks (like in gif above).

**Comment by acemac** [comment]
Does #441 fix this?
In your example gif, the sidebar changes width and causes the break.

**Comment by lukasirsak** [comment]
@acemac i will take look on this later. 

Sidebar width isn't changing in my case. It's stay the same, only header labels get's deformed so it seems like width of sidebar is changing. But it stay the same.

**Comment by lukasirsak** [comment]
Upgrade to 0.23, no changes. 

Importing resize detector fixed this issue for me. [Resize detector](https://github.com/namespace-ee/react-calendar-timeline#resizedetector ) 

Now when scrollbar appears on windows windows resize is detected and everything is fine.
