### ISSUE TITLE
Hiding the timeline

### ISSUE THREAD

**Issue by bwgjoseph** [namespace-ee/react-calendar-timeline#515]
Hi,

Is there any way to hide the `timeline`? Currently, there is `sidebarWidth` which allows to set 0, hence, only showing the `Timeline`.
See <a href="https://codesandbox.io/s/ypwo34m21">this sample</a>

Is there anyway to do like `timelineWidth={0}` so that only the `sideBar` will be shown, and the `timeline` is hidden.

Thanks.

**Comment by Ilaiwi** [comment]
@bwgjoseph there is no way currently to do that. I would suggest forking the library  and applying the changes you are suggesting.
