### ISSUE TITLE
Allowing to override sidebar height

### ISSUE THREAD

**Issue by ksrawat** [namespace-ee/react-calendar-timeline#527]
**Is your feature request related to a problem? Please describe.**
I want to keep the sidebar height to window innerheight. right now sidebar takes the height as per the content. Is there a way to over-ride sidebar height.

**Describe the solution you'd like**
If height is an attribute on <timeline> component which detects user want to over-ride sidebar height.

You can see the unused height marked in red border.
![image](https://user-images.githubusercontent.com/16201677/53587088-5618fc80-3b3e-11e9-816f-ab372516912e.png)

**Comment by Ilaiwi** [comment]
@ksrawat I don't think I understand what you are meaning to do. Please provide more information

**Comment by Ilaiwi** [comment]
I will reopen this when this gets more details
