### ISSUE TITLE
Dependency links

### ISSUE THREAD

**Issue by oazabir** [namespace-ee/react-calendar-timeline#529]
This is an absolutely awesome component! 

Would it be possible to add a feature to link tasks, so that we can show which task depends on which one?

**Comment by Ilaiwi** [comment]
we dont provide this functionality although [this library](https://github.com/guiqui/react-timeline-gantt) does

**Comment by gerich-home** [comment]
See https://github.com/namespace-ee/react-calendar-timeline/issues/806#issuecomment-808728166 as an alternative
