### ISSUE TITLE
Refreshing calendar when i try to render a new json file

### ISSUE THREAD

**Issue by Cyanures** [namespace-ee/react-calendar-timeline#530]
Hi everyone, 

Is any ways to refresh the calendar when i try to render a new json file ?

For example i load a json file and i render it on the calendar, i make a modification on my groups, i delete one group, how can i re-render the calendar without refreshing the page ?

**Comment by Ilaiwi** [comment]
you need to provide a new instance of groups.
 
> NB! All props need to be immutable. For example, this means if you wish to change the title of one of your items, please pass in a whole new items array instead of changing the title in the old array. [Here's more info](http://reactkungfu.com/2015/08/pros-and-cons-of-using-immutability-with-react-js/).

you can find an example of this [here](https://codesandbox.io/s/r1mxzj581m). every time you open a node you will get new groups instance

**Comment by Cyanures** [comment]
I can't make it work :(

there is my code : consider this like the GenerateFakeData function :


```
        let newGroups = []
        for (var i = 0; i < selectedOption.length; i++) {
            newGroups.push({id: selectedOption[i].value, title: selectedOption[i].label})
        }

        groups = newGroups
```

when i do groups = newGroups there is no refreshing of group hapenning
