### ISSUE TITLE
header label foramt local language

### ISSUE THREAD

**Issue by SuperWallaby** [namespace-ee/react-calendar-timeline#531]
Hello ~ i am korean 
and i want to use dateFormat for my country language
the problem is 

Day of the week 

UTC format does not give my language 
I want to change
mon .. tue .. wen ... => 월..화..수

```javascript

const krSubHeaderLabelFormats = Object.assign({}, defaultSubHeaderLabelFormats, {
  monthLong: 'MM 월', 
  hourLong: 'M월 D일 ddd',  // i want format ddd...

<Timeline 
subHeaderLabelFormats={krSubHeaderLabelFormats}
/>
});
```
month and day is ok because it is number
there is no method change  'Day of the week'

Is there a good way??

**Comment by Cyanures** [comment]
use 
`import "moment/locale/ko"`
should do the job

tell me if that solved your problem

**Comment by SuperWallaby** [comment]
i solved it!~~
moment.lang('kr'); 

it was moment format method! 
thanks!!

**Comment by Ilaiwi** [comment]
@Cyanures thanks for helping out
