### ISSUE TITLE
InfoLabel time format

### ISSUE THREAD

**Issue by Najarana** [namespace-ee/react-calendar-timeline#543]
**Is your feature request related to a problem? Please describe.**
InfoLabel shows time in LLL format

**Describe the solution you'd like**
Either add prop for formatting of infolabel or user the same format as headerLabelFormat.

**Comment by bettymakes** [comment]
+1 ☝️

**Comment by trevdor** [comment]
Seems like #517 is getting close to creating this feature. Can this be closed as duplicate?

**Comment by bettymakes** [comment]
+1 @trevdor's note. This will be resolved by #612 when it's merged.

**Comment by Ilaiwi** [comment]
released in 0.26.0
