### ISSUE TITLE
Recieving errors when using Jest/Enzyme

### ISSUE THREAD

**Issue by jamiedust** [namespace-ee/react-calendar-timeline#551]
**Describe the bug**
When I run unit tests (Jest and Enzyme). I receive errors as such:

```
Warning: An update to Timeline inside a test was not wrapped in act(...).
When testing, code that causes React state updates should be wrapped into act(...):
```

My tests still pass, so it is not a big deal, but I try to avoid errors in my output.

The act() error seems to be a new thing (I had not come across it until my latest project). Details of the error can be found here: https://reactjs.org/docs/test-utils.html#act Fixing these errors in a test is generally easy (wrap it in act), but this is coming from your component itself, not my tests (I am simply rendering a parent component with Enzymes mount). It seems to suggest that you are updating state without calling setState, possibly assigning to this.state directly, or interacting with a DOM node? I am not sure.

**To Reproduce**

Run a unit test on a component which renders a Timeline using the latest React, Jest and Enzyme. Render the component with Enzymes mount.

**Expected behavior**
Tests run without errors.

**Library Version**

react-calendar-timeline@0.23.1
react@16.8.4
enzyme@3.9.0
jest@23.6.0

**Additional context**
I used create-react-app to generate the project. I notice now that the version of jest is not the latest, so it may be that, but I won't be the only one using CRA.

I have tried using reactDOMs render instead of Enzyme, I have also tried using the latest version of Enzymes React 16 adapter which wraps mount calls in act, neither of these work.

I am more than happy to supply a PR for this, but thought I would raise the issue first and see if anyone had an idea where this error originates from.

Thank you for your time and for a great package 👍

**Comment by Ilaiwi** [comment]
yes there is a state direct assigning in `Item.js`.It is not hard to fix though. I would appreciate some help doing that

**Comment by jamiedust** [comment]
Apologies after further investigation I see this was an unrelated issue with setting state asynchronously in useEffect, not as I thought, anything to do with react-calendar-timeline.

Keep up the good work!
