### ISSUE TITLE
daylight savings time

### ISSUE THREAD

**Issue by signalwerk** [namespace-ee/react-calendar-timeline#56]
If I wanna snap to the grid every 4h (14400000sec → 4 * 60 * 60 * 1000) I do something like that:
```
<Timeline
    groups={groups}
    items={items}
    ...
    dragSnap={14400000} 
/>
```
The Problem is now that if I'm in daylight savings times and move an item out of it I get: 01:00, 05:00 instead of 00:00, 4:00. (or vice versa)

See the change at the 30th of october where it switches (in Switzerland at least...):
![daylightsaving](https://cloud.githubusercontent.com/assets/992878/19887321/0600e522-a028-11e6-8fd1-59c47fdd2855.gif)

Is that a bug or a feature? For me it's a bug since I would like to have only certain steps for planing (0:00, 4:00, 8:00, ...).

**Comment by mariusandra** [comment]
Hey, I played with it and got it to work: https://www.youtube.com/watch?v=SyrmNQaYx6E&feature=youtu.be

However I had to remove [some code](https://github.com/namespace-ee/react-calendar-timeline/compare/daylight-savings?expand=1#diff-33ad0e215adda683024d596a4cceb257L67) which @xmityaz added that's connected to timezones. @xmityaz, will the [new snap calculation code](https://github.com/namespace-ee/react-calendar-timeline/compare/daylight-savings?expand=1#diff-fb54f78b07de422efaa3d2d82bb82db3R357) work with the usecase you solved with your initial `considerOffset` fix?

**Comment by madisvain** [comment]
@mariusandra @xmityaz  should this issue be closed?

**Comment by xmityaz** [comment]
@mariusandra @madisvain 
Hi. Sorry for the late response.
Yes, the new code works great. I've checked the initial usecase with `considerOffset` it is not reproducible
So the issue can be closed

**Comment by madisvain** [comment]
@xmityaz sounds good!
