### ISSUE TITLE
Custom periods in the new DateHeaders

### ISSUE THREAD

**Issue by maartenpeels** [namespace-ee/react-calendar-timeline#561]
I'm trying to migrate my project to the newest version(because of the custom headers). And I can't figure out how to use custom periods. Maybe I missed something but otherwise, this would be a great addition in my opinion.

The thing I'm trying to do is have the primary header show every hour(working) and have the subheader show every 15mins(0, 15, 30, 45). 

Below a screenshot of the old version, which I'm trying to replicate.

![Desired Result](https://user-images.githubusercontent.com/5376764/56416854-6cb41800-6292-11e9-92a0-0e9bea07e1f8.png)

**Comment by maartenpeels** [comment]
Sorry, was under the impression that timeSteps would not work anymore since the headers are separated now. Appears it does, issue resolved.

**Comment by Ilaiwi** [comment]
@maartenpeels ok that is great. I hope you are enjoying the Custom Headers spent too much time to do them lol

**Comment by maartenpeels** [comment]
I've been waiting for it to add some needed functionalities, so in my case, time well spent! Thanks for making this library.
