### ISSUE TITLE
v0.25.0 timeline className rct-header-root undefined

### ISSUE THREAD

**Issue by stahlmanDesign** [namespace-ee/react-calendar-timeline#566]
In v0.25.0 I noticed the className `rct-header` is slightly different from pervious versions (my css override stopped working). It is now `rct-header-root`, but also contains the word `undefined` which might be a bug

`rct-header-root undefined`

![Capture d’écran, le 2019-05-02 à 16 38 38](https://user-images.githubusercontent.com/972804/57105661-5d54b600-6cf9-11e9-8102-5bb12bd4fd6d.png)

**Comment by tobiasbueschel** [comment]
Thanks for raising this @stahlmanDesign!

You are right, `.rct-header-root` was a change introduced by this commit https://github.com/namespace-ee/react-calendar-timeline/pull/391/files#diff-3660012d22840def1644776e270bea15R162 and then release in v0.25.0

As for the `undefined`, could you share a CodeSandbox? That will make it easier to troubleshoot.

Alternatively, feel free to raise a PR to fix this :)

**Comment by web2wire** [comment]
I'm also getting this and 'undefined' also appears as a class on rct-calendar-header.

**Comment by joey-ua** [comment]
> https://github.com/namespace-ee/react-calendar-timeline/pull/391/files#diff-3660012d22840def1644776e270bea15R162

Hello! Even demo posted on Github has same issue: https://codesandbox.io/s/w6xvqzno4w

![image](https://user-images.githubusercontent.com/6209978/57524542-c7d8a800-7330-11e9-9bbd-ec91ace4b77f.png)

Personally I has serious issues while trying to use custom headers (duplicated headers):
![image](https://user-images.githubusercontent.com/6209978/57524656-1dad5000-7331-11e9-9925-2ca3987c5580.png)
![image](https://user-images.githubusercontent.com/6209978/57524658-200faa00-7331-11e9-9468-0aafc8325d35.png)

I'm just trying to reproduce the example in the link while getting this, v0.25.1

**Comment by trevdor** [comment]
Here's what I'm seeing:

`TimelineHeaders` has two props that correspond to the two `undefined` strings reported in this issue. 
1. The `className` prop value is placed next to `rct-header-root` 
2. The `calendarHeaderClassName` prop value is placed next to `rct-calendar-header`

So this usage would define both of them:
```jsx
<TimelineHeaders className="sticky" calendarHeaderClassName="defined">
```

[This PR](https://github.com/namespace-ee/react-calendar-timeline/pull/586) fixes both of these, making sure `undefined` never gets sent to the DOM.
