### ISSUE TITLE
[QUESTION] how can i disable the topbar time ?

### ISSUE THREAD

**Issue by TITAN9389** [namespace-ee/react-calendar-timeline#568]
I just want to see the Date no need for 2nd line Time bar , how can i disable that ?

![image](https://user-images.githubusercontent.com/27279495/57201390-75526100-6fa9-11e9-81b7-2897ec2ed3cc.png)

**Comment by Ilaiwi** [comment]
By using Custom Headers.

you can find an example here of what you are trying to achieve

https://codesandbox.io/s/kwqplllrmo
