### ISSUE TITLE
How is maxZoom supposed to work?

### ISSUE THREAD

**Issue by SBUtltmedia** [namespace-ee/react-calendar-timeline#57]
I'm trying to set the maximum zoom but it seems to have no effect. I might be doing something wrong.

```
      <Timeline groups={groups}
          items={items}
          defaultTimeStart={moment().add(-12, 'hour')}
          defaultTimeEnd={moment().add(12, 'hour')}
          minZoom={1000 * 60 * 60}
          maxZoom={1000 * 60 * 60 * 24 * 7}
      />
```

Here's my project: https://github.com/SBUtltmedia/react-calendar-timeline-test

Thank you.

**Comment by mariusandra** [comment]
Hey, just looking at your code it should work. It works on my computer and also when I tried in this codepen with the latest version: https://codepen.io/mariusandra/pen/ONrQaX

Is the bug still there?
