### ISSUE TITLE
Question Is it possible to display certain time slots ?

### ISSUE THREAD

**Issue by masbouj** [namespace-ee/react-calendar-timeline#570]
Hello,

Is it possible to display only from 9am to 5pm? Or remove every sunday ?

Thanks.

**Comment by maartenpeels** [comment]
Hi,

You can use the visibleTimeStart and visibleTimeEnd props for this.
Documentation [here](https://github.com/namespace-ee/react-calendar-timeline#defaulttimestart-and-defaulttimeend). Not sure about removing specific days though.

**Comment by Ilaiwi** [comment]
you cant remove a specific day
@maartenpeels thanks for answering
