### ISSUE TITLE
Moving the timeline after double click with mouse in webkit bug

### ISSUE THREAD

**Issue by jmmontero1** [namespace-ee/react-calendar-timeline#578]
**Describe the bug**
On webkit browsers, after double clicking on the timeline, when moving the timeline by dragging it, it scrolls in the opposite direction when the mouse (this is important, trackpad works fine) is close to the edges.

**To Reproduce**

1. Go to https://codesandbox.io/s/w6xvqzno4w with a webkit browser
2. Double click anywhere in the timeline
3. Now, click again and drag to move the timeline
4. When getting close to the edges, the timeline will scroll in the opposite direction

**Expected behavior**
The timeline shouldn't scroll in the opposite direction

**Library Version**
V 0.25.0 and previous

**Desktop (please complete the following information):**
* OS: Mac OS 10.13.6
* Browser: Chrome, Safari

**Additional context**
This problem occurs because the browser is scrolling the timeline since it's overflow css property is set to scroll. To solve it, we can set the property to hidden when there is a dragging going on. This can be done in the file ScrollElement.js by adding 
` overflowX: isDragging ? 'hidden' : 'scroll' `
to the style of the timeline.

I can gladly provide a PR for this fix

**Comment by jmmontero1** [comment]
This seems to be fixed in 0.26.4

**Comment by Ilaiwi** [comment]
@jmmontero1 great to hear! I didn't know how to solve this tbh haha
