### ISSUE TITLE
Can you display a scroll bar to scroll horizontally?

### ISSUE THREAD

**Issue by jlsorak** [namespace-ee/react-calendar-timeline#579]
I would like to have a scroll bar to scroll the timeline horizontally. I have tried applying `overflow: scroll` to the `rct-scroll` element but it doesn't work. Has anyone done this before/know how this would be possible?

Thanks in advance.

**Comment by Ilaiwi** [comment]
@jlsorak this is not possible due to the horizontal bar being controlled by the library.
