### ISSUE TITLE
items collapse upon themselves in timeline

### ISSUE THREAD

**Issue by eamonpenland** [namespace-ee/react-calendar-timeline#59]
I am dynamically adding data to the timeline component using a multi-select picker and api call. When I add new data to the timeline component, it causes the old data on the timeline to collapse upon itself. Any idea what is happening?

**Comment by mariusandra** [comment]
Hi, any chance you're mutating the data? When adding a new item, you should pass in a completely new array and not add the new item to the end of an existing array.

I added a comment about this here: https://github.com/namespace-ee/react-calendar-timeline#api

**Comment by eamonpenland** [comment]
fixed...this was a data mutation issue. Thanks!
