### ISSUE TITLE
Question: programmatically selecting which vertical lines to render

### ISSUE THREAD

**Issue by hellooperatorpatchmethrough** [namespace-ee/react-calendar-timeline#591]
Now that CustomHeaders and week unit intervals are available, I am wondering how to show veritcal lines indicating week intervals. Is this even possible ? If I set  `timeSteps:{{... day: 7 ...}` vertical lines are rendered indicating 1 week length intervals but they start on Sunday and this approach is not suitable for us as we should display weeks starting on Monday and this approach does not respond to moment.locale().

Some tips for where to look at in source code are welcome as well. Might raise a pull request in some time

update:
I've discovered this line in calendar.js : https://github.com/namespace-ee/react-calendar-timeline/blob/ab02bae279b0a1224e45de8ed4d28184997d4d5b/src/lib/utility/calendar.js#L79
Any status on this ?
feature/weeks-view branch seems to be dead

**Comment by trevdor** [comment]
Maybe it's not an approach you want to use, @hellooperatorpatchmethrough, but I've styled vertical lines with CSS overrides before. 

For example:
https://codesandbox.io/s/timeline-vertical-lines-next-to-mondays-3cp0q
*(timeline items removed to keep the emphasis on the vertical lines)*

**Comment by Ilaiwi** [comment]
@hellooperatorpatchmethrough the week unit support is currently only limited to the headers and not the calendar part.
@trevdor thank you for answering this and providing a codesandbox example.
