### ISSUE TITLE
Issue with date placement inside the header

### ISSUE THREAD

**Issue by uijaswanthi** [namespace-ee/react-calendar-timeline#597]
i am having an issue with date placement inside the header. Sometimes the date stamp is not visible as shown in the below screenshot. I have to scroll little left/left to view the date .
Is there any way to display the date stamp into the visible area always.

![image](https://user-images.githubusercontent.com/33267879/59728293-1c5c2680-91ff-11e9-9f4e-adbe2d85a4e3.png)

**Comment by Ilaiwi** [comment]
yes, use sticky

**Comment by Ilaiwi** [comment]
I guess this problem is related to #603 I would suggest this issue there please
