### ISSUE TITLE
When prefetch new data, error in console appears, but timeline works fine

### ISSUE THREAD

**Issue by ochervak** [namespace-ee/react-calendar-timeline#6]
I use timeline component in next way:
```
<Timeline groups={this.getResidents()}
                          items={this.getActivityTimeline()}
                          itemHeightRatio={1}
                          defaultTimeStart={this.props.startTime}
                          defaultTimeEnd={this.props.endTime}
                          canMove={false}
                          dragSnap={60 * 60 * 1000}
                          lineHeight={40}
                          canChangeGroup={false}
                          onBoundsChange={this.onCanvasBoundsChange}
                          visibleTimeStart={this.props.startTime.valueOf()}
                          visibleTimeStop={this.props.endTime.valueOf()} />
```

Inside `this.onCanvasBoundsChange` i use ajax call to server, and new items from `this.getActivityTimeline()` pushed to your beautiful component.

However in Chrome debugger i expect `es6.promise.js:119 Unhandled promise rejection TypeError: Cannot read property 'dimensions' of undefined(…)`

And it refs to transpiled line `dimensions: sortedDimensionItems[(0, _utils._get)(item, itemIdKey)].dimensions,` which is in `visibleItems.map(function (item) {` inside `render`.

Can you explain this error, or maybe i using your tool in some wrong way?

Thanks in advance

**Comment by mariusandra** [comment]
Hey!

Does the fix by @xmityaz, which is now in v0.7.8 solve the issue for you?

**Comment by ochervak** [comment]
yes, it solved! thanks

**Comment by jerryslaw** [comment]
Guys I still have this problem, same case. My component is re-rendering every time, when new context will come (setting new state from context, parsing data for items, and passing items from new state to Timeline).
