### ISSUE TITLE
Invalid group height calculation with unsorted IDs

### ISSUE THREAD

**Issue by johnnyomair** [namespace-ee/react-calendar-timeline#602]
**Describe the bug**
I want different group heights for different type of groups (for instance sections and normal groups). When setting the `height` param for some groups and the `lineHeight` property for the Timeline component, the different heights are applied to the wrong groups.

**To Reproduce**

Create a simple Timeline with the following groups:

```typescript
const groups = [
  { id: 1, title: "group 1", height: 30 },
  { id: 5, title: "group 5" },
  { id: 4, title: "group 4" },
  { id: 2, title: "group 2", height: 30 },
  { id: 7, title: "group 7" },
  { id: 8, title: "group 8" },
  { id: 9, title: "group 9" },
  { id: 3, title: "group 3", height: 30 },
  { id: 6, title: "group 6" }
];

const items = [];

ReactDOM.render(
  <div>
    Rendered by react!
    <Timeline
      groups={groups}
      items={items}
      defaultTimeStart={moment().add(-12, "hour")}
      defaultTimeEnd={moment().add(12, "hour")}
      lineHeight={60}
    />
  </div>,
  document.getElementById("root")
);
````
A full example can be seen at [this repository](https://github.com/johnnyomair/rct-height-calculation-demo).

**Expected behavior**
The groups with the IDs 1, 2 and 3 have different heights than the other groups.

**Screenshots**
![image](https://user-images.githubusercontent.com/48853629/59997999-a15f9980-965e-11e9-9913-0a77da076d00.png)

The groups with the IDs 1, 5 and 4 have the different heights. These are the groups with the indices 0, 1 and 2.

**Library Version**
0.25.3

**Desktop (please complete the following information):**

* OS: MacOS
* Browser Chrome
* Version 75

**Additional context**

 I've found that when using group IDs in a sorted order, this is not the case. As the used IDs come directly from the API, I can't guarantee that they will be sorted. The workaround I'm using at the moment is to create a mapping between the actual IDs and IDs in sorted fashion (basically the index), but I'd like to remove this workaround.

I've tried to dig in the library to find where this behavior happens, but I'm not sure where to start. Do you have any idea where this wrong calculation could happen?

**Comment by IndProgo** [comment]
It seems the bug is here
https://github.com/namespace-ee/react-calendar-timeline/blob/44bed941f395f775fb86626933d55dcbd3401fb7/src/lib/utility/calendar.js#L257
it should reference to the index saved in the groupOrder. Object.keys may be in wrong order
```groupedItems[groupOrder.index] = { ```
