### ISSUE TITLE
Multiselect and bulkedit

### ISSUE THREAD

**Issue by perfectstrong** [namespace-ee/react-calendar-timeline#604]
This is not really a bug but help wanted.

I'm trying to implement multiselect & bulkedit with simpler use case than #315. I just need to move/resize the items back and forth in time, no need to squeeze them into a group.
![image](https://user-images.githubusercontent.com/23375518/60159981-ace4c900-97f4-11e9-864c-4c9437876621.png)

With custom `selected`, `onItemSelect`, `onItemClick`, `onItemDeselect`, `onItemMove` and `onItemResize`, i manage to mass edit all selected items.

Only one thing bugging me so far is the instant visual update when dragging / resizing. I'd like to control **the position to render of item** in `itemRenderer`.
![output](https://user-images.githubusercontent.com/18690030/40408912-baad6f6c-5e9b-11e8-898a-4387a695644e.gif)

**Comment by Ilaiwi** [comment]
we don't officially support your use case in react-calendar-timeline but nice workaround!. 
so for dragging position `getRootProps` prop getter in `itemRendere` returns a style property with left,top you can control the position by overriding those  styles. I would not recommend that unless you really really need to.
