### ISSUE TITLE
Items get misaligned from their row on browser scaling

### ISSUE THREAD

**Issue by gaston-niglia** [namespace-ee/react-calendar-timeline#609]
**Describe the bug**
Items get misaligned from their rows as the timeline gets scrolled down when the browser scale is different than 100%.

**To Reproduce**
When running the main `Demo` app, increase the number of groups and items in the timeline by changing the args `groupCount` and `itemCount` default values from `generate-fake-data.js` file:

e.g: `export default function (groupCount = 3000, itemCount = 10000, daysInPast = 30) {`

This way there will be plenty of groups to scroll down. Please do that and you will see that when the browser's zoom level is **100%** it looks good. However, if you scale the browser to **80%** for instance, items get progressively misaligned as you keep scrolling down:

![misaligned-items-before](https://user-images.githubusercontent.com/27180527/60626052-a3cfa980-9e3d-11e9-8e26-5e4c66a6bef4.gif)

Here's another example of getting misaligned items on browser scaling:

![calendar-zoom-demo](https://user-images.githubusercontent.com/27180527/60628611-5572d880-9e46-11e9-95a7-25ab828809f4.gif)

This is happening because on some zoom levels, the row is `30px` height (it's default value), and for other % it gets to `29.98px`:

**Browser at 100%**
![Screen Shot 2019-07-04 at 10 26 03 AM](https://user-images.githubusercontent.com/27180527/60628731-dfbb3c80-9e46-11e9-8309-de07c7617f29.png)

**Browser at 90%**
![Screen Shot 2019-07-04 at 10 26 27 AM](https://user-images.githubusercontent.com/27180527/60628756-f6fa2a00-9e46-11e9-960e-59ebd5429090.png)

**Expected behavior**
Items should be always be aligned with their corresponding row no matter browser scaling.

**Library Version**
0.25.4

**Desktop (please complete the following information):**
* OS: macOS Mojave
* Browser chrome (75.0.3770.100)

**Additional context**
PR [here](https://github.com/namespace-ee/react-calendar-timeline/pull/615) with the fix @Ilaiwi

**Comment by Ilaiwi** [comment]
@gaston-niglia I know this took forever but thank you very much! I wish all PRs were as good as yours. I am looking forward to future collaborations from you.

released in 0.26.3
