### ISSUE TITLE
Overlapping on change of start time

### ISSUE THREAD

**Issue by DermotMcAteer** [namespace-ee/react-calendar-timeline#61]
Hi there, I am having an issue when I change the start time of an item. If I change the start time to a later start time overlap occurs, this overlap does not occur when I change the start time to an earlier one. 

I am calling a new items array each time a change is made and stackItems is set to true. 

Any insight to why this might be happening would be greatly appreciated. 

Before: Start time: 9:30am 
<img width="1024" alt="screen shot 2016-11-28 at 11 24 19" src="https://cloud.githubusercontent.com/assets/9554484/20666898/6e38812c-b55e-11e6-9665-1fcf1240cc20.png">

After: Start time: 10:30am
<img width="1022" alt="screen shot 2016-11-28 at 11 24 52" src="https://cloud.githubusercontent.com/assets/9554484/20666899/6e3904c6-b55e-11e6-8dc3-e740c90aec40.png">

**Comment by mariusandra** [comment]
Hey, hard to comment without checking your code.

However, when the `items` prop changes, all item dimensions are recalculated:
https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/Timeline.js#L367

So are you 100% certain you're passing a new `items` prop to the component after the change? Is the error there when you open the calendar with the state as in your "after" pic, or only when you change it from the "before" state?

**Comment by DermotMcAteer** [comment]
Hey thanks for the quick reply, the problem was on my end, never worry. Thanks anyway.
