### ISSUE TITLE
"Ussage: At the very minimum" don't work

### ISSUE THREAD

**Issue by tgosp** [namespace-ee/react-calendar-timeline#62]
Without `canResize` prop in `items` I'm getting `Uncaught TypeError: Cannot read property 'props' of undefined` with minimum config.

Please check:
https://github.com/namespace-ee/react-calendar-timeline/commit/87caad0630d53735268f35cd178bb92a00d64643#diff-32da143c564460e65f57c62427a0084bR7

https://github.com/namespace-ee/react-calendar-timeline/commit/47478d7ae1233ed4dfafeaeaa0731a65cee0e34c#diff-b7c68dccde932251699a245e95cd0fd0R28

**Comment by DanielRuf** [comment]
we have the same issue

**Comment by mariusandra** [comment]
0.11.1 released with the patch

**Comment by tgosp** [comment]
Thank you @mariusandra !
