### ISSUE TITLE
Question: Possibility to drag and drop items of sidebar to calendar timeline canvas

### ISSUE THREAD

**Issue by prh7** [namespace-ee/react-calendar-timeline#623]
Hi,
 Is it possible to drag and drop items from sidebar to react-timeline-canvas as in the below GIF?

[
![dragndrop](https://user-images.githubusercontent.com/10049692/61358919-a689c000-a87b-11e9-813b-dc631f4d4023.gif)
](url)

**Comment by Ilaiwi** [comment]
@prh7 this is currently not possible. I am writing up an RFC for row renderers that will enable this to happen.

**Comment by alekkowalczyk** [comment]
Any time frame on that feature? It's a crucial feature for us

**Comment by Ilaiwi** [comment]
@alekkowalczyk luckily this rowRender is sponsored so I have some resources to do it. I think it will be in some time in the beginning of septemper

**Comment by phazzzy** [comment]
Hey @Ilaiwi, is there any news?

**Comment by Ilaiwi** [comment]
@phazzzy working on it. Not ready yet. You can check [here](https://github.com/namespace-ee/react-calendar-timeline/pull/630#issuecomment-527350919) for the latest updates on the feature
