### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) 

### ISSUE THREAD

**Issue by zalambodont** [namespace-ee/react-calendar-timeline#627]
`Hi all, here is the code, actually it is the same as the "demo-main" file. It is saved as a component and been called from another component. Usual stuff.

But however, I cannot make it run. I am using create-react-app as a scratch and we have react-redux, keycloak stuff going on. 

Here is the message I get

> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `TimelineStateProvider`.

and here is the code:

[Timeline.txt](https://github.com/namespace-ee/react-calendar-timeline/files/3425612/Timeline.txt)

**Comment by Ilaiwi** [comment]
hi @zalambodont please provide a codesandbox for your example.
https://codesandbox.io/s/w6xvqzno4w

**Comment by zalambodont** [comment]
> hi @zalambodont please provide a codesandbox for your example.
> https://codesandbox.io/s/w6xvqzno4w

Hi there,

I can't reproduce my error codesandbox. It is just not running on my app. I am using the example on official repo as it is. Do you think it may be something about the Route components wrapping?

**Comment by Ilaiwi** [comment]
@zalambodont I would recommend using the codesandbox code for starter code not the one in the demo in the repo. Try it and let me know

**Comment by zalambodont** [comment]
unfortunately, no luck with the codesandbox code. 
by the way, I am using create-react-app, maybe this is the reason?

**Comment by Ilaiwi** [comment]
code sandbox uses create-react-app. I can't help you without reproduce steps

**Comment by zalambodont** [comment]
Okay, I figured out that lot more is wrong with my app. Updating react-dom and react to latest stable versions solved all problems.
