### ISSUE TITLE
DateHeader dates misaligned when toggling off and on

### ISSUE THREAD

**Issue by thejpleigh** [namespace-ee/react-calendar-timeline#635]
**Describe the bug**
When the DateHeader is toggled on and off, the dates are misaligned when toggled back on.

**To Reproduce**
1. We have a boolean that checks if a toggle switch has been activated
2. If so, the DateHeader is no longer visible, and the items in our timeline are aligned by a specific date
3. When the toggle is turned off (the boolean is now false), the DateHeader reappears, but with the incorrect years
4. The dates realign to their correct values once a user clicks to drag the timeline

**Expected behavior**
We expect the dates to be realigned to their correct values when the toggle is turned off without requiring the user to click into the timeline.

**Library Version**
0.26.0

**Desktop (please complete the following information):**
* Browser: chrome

**Comment by Ilaiwi** [comment]
@thejpleigh how do you pass your boolean? you need to pass it via `headerData` prop 
https://github.com/namespace-ee/react-calendar-timeline#props-2

if you do that then the component will react to the prop change
