### ISSUE TITLE
stackItems conflict with onCanvasClick

### ISSUE THREAD

**Issue by kations** [namespace-ee/react-calendar-timeline#64]
If i set stackItems={true} and have two Appointments stacked. The onCanvasClick Area is now(should now) double as big, but if i click in the bottom i get in the onCanvasClick event the groupId from the next User.

It seems that the onCanvasClick of one group is every time only one normal row height, so if there is a stacked row, alls rows after this has a wrong onCanvasClick groupId.

**Comment by mismailentelect** [comment]
@schwermer I found this calendar a few days ago, and it's really helped a lot. I ran into this same issue though, any update on a fix for this?

**Comment by mariusandra** [comment]
Hey, I believe this was fixed with `v0.14.8`: see issue #105 and PR #118 . If it's still an issue, please reopen this!
