### ISSUE TITLE
Unable to import TimelineHeaders, DateHeaders or SidebarHeaders

### ISSUE THREAD

**Issue by Intruder0404** [namespace-ee/react-calendar-timeline#640]
`import Timeline,  {
    TimelineGroup, TimelineItem, TimelineHeaders
} from "react-calendar-timeline";`

Tells me 'Module '"react-calendar-timeline"' has no exported member 'TimelineHeaders'. '

**Comment by Ilaiwi** [comment]
@Intruder0404  please make sure you are on the latest version of the package.

**Comment by Intruder0404** [comment]
"react": "^16.8.6",

    "typescript": "^3.5.3"

"@types/react-calendar-timeline": "^0.16.1",


    "react-calendar-timeline": "^0.26.1",

**Comment by Intruder0404** [comment]
So if my project is into typescript I have a major problem?

**Comment by Ilaiwi** [comment]
@Intruder0404  no just don't include the typescript definitions and it will take it as `any` type

**Comment by Intruder0404** [comment]
I had to put the noImpliciteAny to false in the tsconfig to have it accept
it.The imports work now. I just need to use them and see if the rest works.
 At least I get the base stuff up and working thanks.

**Comment by Ilaiwi** [comment]
@Intruder0404 good to hear. If you would like to maintain and update the types please open an issue and tag me in it and that would be a great contribution from you
