### ISSUE TITLE
Question: How to set property 'selected' in itemContext of ItemRenderer to false when we drop a task to another row?

### ISSUE THREAD

**Issue by prh7** [namespace-ee/react-calendar-timeline#641]

**Comment by Ilaiwi** [comment]
selected can be controlled but is bugged. I created at a PR to fix it. I will try to merge it during the weekend
https://github.com/namespace-ee/react-calendar-timeline/pull/499

**Comment by Ilaiwi** [comment]
@prh7 this is released in 0.26.3 forgot to close this issue
