### ISSUE TITLE
Items background color not rendering

### ISSUE THREAD

**Issue by himadriganguly** [namespace-ee/react-calendar-timeline#643]
**Describe the bug**

style: {
        backgroundColor: 'fuchsia'
},

Style backgroundColor added in items not rendering.

**To Reproduce**

_Please provide one or both of the following:_

Code (If you have a branch somewhere that shows your issue) or link to codesandbox example. [Here's a base template for this library](https://codesandbox.io/s/w6xvqzno4w):

OR

**Expected behavior**

**Screenshots**

**Library Version**
Please provide version of library in which this bug is occurring.

**Desktop (please complete the following information):**

* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Smartphone (please complete the following information):**

* Device: [e.g. iPhone6]
* OS: [e.g. iOS8.1]
* Browser [e.g. stock browser, safari]
* Version [e.g. 22]

**Additional context**

**Comment by Ilaiwi** [comment]
you need to do `background` not `backgroundColor`

**Comment by himadriganguly** [comment]
> you need to do `background` not `backgroundColor`

But in the documentation - [https://github.com/namespace-ee/react-calendar-timeline#items](https://github.com/namespace-ee/react-calendar-timeline#items) it is given that it will be **backgroundColor** within **style** tag.

**Comment by Ilaiwi** [comment]
@himadriganguly have you checked this example?
https://codesandbox.io/s/k0wn41y0o7
if it doesn't help you please provide a codesandbox an I will reopen this issue
