### ISSUE TITLE
Problem with stackItems and expandable groups.

### ISSUE THREAD

**Issue by Sylv0** [namespace-ee/react-calendar-timeline#660]
**Describe the bug**
I'm using the timeline with a solution for groups that can be expanded and closed which I found online. But the way I'm using it causes the stackItems-attribute to not work, they just end up overlapping. I've seen these things work together, but I can't figure out what the cause is in this situation.

**To Reproduce**
[Example on Codesandbox](https://codesandbox.io/s/3wnng):

**Expected behavior**
Items should stack since the attribute is given.

**Library Version**
Tested on 0.22.0 and 0.26.4

**Desktop:**

* OS: Windows 10
* Browser Chrome, Firefox
* Version 77, 69

**Comment by prh7** [comment]
@Sylv0 - You need to specify start and end dates for each item in milliseconds or moment date object. Native JS Date object isn't supported. That will solve your problem.

**Comment by Sylv0** [comment]
Thank you @prh7. I feel slightly dumb right now. Recently I've been working a lot with Native Date and date-fns and I completely forgot this package is using moment.

**Comment by Ilaiwi** [comment]
@prh7 thank you for solving this
