### ISSUE TITLE
Display date on CursorMarker

### ISSUE THREAD

**Issue by jessica-may** [namespace-ee/react-calendar-timeline#662]
Is there a way to display the month and year I'm hovering over with CursorMarker? Also is there a way to make CursorMarker's bar be displayed over the items instead of behind them?

**Comment by Ilaiwi** [comment]
yes you need to increase its z-index more than 88

**Comment by jessica-may** [comment]
I've done that in the inspect element and it seems to work but I can't get it to persist over page refresh by modifying the Timeline.css file in the library. I've edited the z-index on .rct-scroll and .rct-item:hover and neither of these seem to fix it. I've also attempted creating a separate css file and using inline css and nothing works.

Also, how would I create a tooltip on this CursorMarker to display the month/year it's currently over? I can't seem to find this in the documentation.

Any help is appreciated.

**Comment by prh7** [comment]
```
import React from 'react';
import { TimelineMarkers, CustomMarker } from 'react-calendar-timeline';

export const TimelineMarker = (props: TimelineMarkerProps) => {
    return (
        <TimelineMarkers>
            <CustomMarker date={props.date}>
                {({ styles }: { styles: CSS }) => {
                    const customStyles = {
                        ...styles,
                        backgroundColor: '#1488fe',
                        width: '2px',
                        zIndex: 85,
                        top: 0
                    };
                    return (
                        <div style={customStyles}>
                            <div className="marker__text">Now</div>
                        </div>
                    );
                }}
            </CustomMarker>
        </TimelineMarkers>
    );
};

```

Pass date as props using moment. That should show the date on the tooltip alongside CursorMarker line. The CursorMarker should persist on pageRefresh.

@jessica-may

**Comment by prh7** [comment]
@jessica-may 

`.react-calendar-timeline .rct-cursor-line {
    position: absolute;
    width: 2px;
    background: #2196f3;
    z-index: 51;
}`

You can use this CSS.

**Comment by Ilaiwi** [comment]
@prh7 thanks for helping on this.
@jessica-may please let us know if this answers your question.
I will close this for now
