### ISSUE TITLE
The style for item 

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#663]
Hi, I cannot change the style for items.
{
  id: 1,
  group: 1,
  title: 'Random title',
  start_time: 1457902922261,
  end_time: 1457902922261 + 86400000,
  canMove: true,
  canResize: false,
  canChangeGroup: false,
  className: 'weekend',
  style: {
    backgroundColor: 'fuchsia'
  },
  itemProps: {
    // these optional attributes are passed to the root <div /> of each item as <div {...itemProps} />
    'data-custom-attribute': 'Random content',
    'aria-hidden': true,
    onDoubleClick: () => { console.log('You clicked double!') }
  }
}

from the documentation I see it is possible to put string backgroundColor, but it doesn't work:(

Thank you in advance!

**Comment by Ilaiwi** [comment]
@mnob2019 could you please provide codesandbox for your case?

**Comment by mnob2019** [comment]
So basically I was trying to do this.  But apparently it cannot be done directly. Only with the  item rendering? Sorry if that is that is an easy and obvious question, but I as I said I am very new to React and front-end in many ways. 
https://codesandbox.io/s/bold-dan-z341u

**Comment by Ilaiwi** [comment]
@mnob2019 oh the documentation is wrong here sorry for that.
it should be
```
itemProps: {
  style: {
    backgroundColor: "fuchsia"
  }
}
```
like here
https://codesandbox.io/s/bold-kepler-58oom

**Comment by Ilaiwi** [comment]
fixed the docs. let me know if you have any other questions
