### ISSUE TITLE
onCanvasClick call a component 

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#664]
Hi, 
I would like to ask. It is written that onCanvasClick I can open a window to create a new event. Is it possible somehow
onCanvasClick open a  new component to create an event?

Thank you!

**Comment by mnob2019** [comment]
@Ilaiwi

**Comment by Ilaiwi** [comment]
@mnob2019 yes you can do that differently.
you need to use `onCanvasClick(groupId, time, e)` of course. On click you would open something like [Modal from material ui](https://material-ui.com/components/dialogs/#form-dialogs) and ask the user via a form to fill some info and create a new item by adding it to the `items` passed to `Timeline`

**Comment by mnob2019** [comment]
@llaiwi thank you for the response,I will look through that form:) new to React and doing quite a big front-end project. You have an amazing library here, than  you for the work!

**Comment by Ilaiwi** [comment]
youre welcome. It would be awesome if you could share a codesanbox if you got things working here.
let me know if you have any other questions but I will close this for now

**Comment by mnob2019** [comment]
I will as soon as something works!:)) Thank you!

**Comment by mnob2019** [comment]
@Ilaiwi  not sure how I can reopen the issue to continue, but I am trying to open a component form the Timeline and it returns me the following error:
https://codesandbox.io/s/wandering-sound-fkg3r

The function works I tried it, rendering a separate component, it also works inside, the Timeline  with console.log and alert, but when I pass the Form component it gets undefined. The logic is pretty the same as in material UI. I was just wondering if it can be something in the library predefined that I cannot understand?  Or I am doing something completely wrong?

**Comment by Ilaiwi** [comment]
@mnob2019  there are couple of issues with the code iteself not the library
fixed them in this fork 
https://codesandbox.io/s/brave-wescoff-i56o9

**Comment by mnob2019** [comment]
@Ilaiwi  Oi, that is amazing! thank you!! Ye....I usually assume myself being stupid, actually))))
where can I read more about this ? <></> Its like an empty component?  

In the view it looks a bit behind the bars, imprisoned)) 

https://codesandbox.io/s/jolly-leftpad-mdhnc
