### ISSUE TITLE
Set up  background color onCanvasDoubleClick after resizing or moving  the default color returns

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#667]
@Ilaiwi , and a problem  I face:) In my project the colors are important, I should be able to  set  item background color. But after resizing it returns to the default sets. Should I do it with the itemRender?

Please check the codesandbox:

https://codesandbox.io/s/wandering-sound-fkg3r

**Comment by mnob2019** [comment]
sorry for pinging:)) @Ilaiwi

**Comment by Ilaiwi** [comment]
@mnob2019 no problem feel free to mention me.
you need to use `background` instead of backgroundColor.
I understand this is a little frustrating but there is a PR that will fix this issue #659
I fixed the docs as well
