### ISSUE TITLE
The item resizing 

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#668]
@Ilaiwi  Good Morning, I have a question, it seems that the text in the item boxes doesn't resize with the items. So it is not relative. Is it possible to fix somehow, may be with css? Thank you!

**Comment by Ilaiwi** [comment]
@mnob2019 with itemRenderer there is a prop passed with [`itemContext`](https://github.com/namespace-ee/react-calendar-timeline#itemrenderer) called `width` which is the width of the item. Using that value you can change the fontsize to make it fit

**Comment by mnob2019** [comment]
@Ilaiwi  Is it possible to  make it relative, I mean how much text is seen can depend on the size of the item?

**Comment by Ilaiwi** [comment]
@mnob2019 you need to implement that using the item context. This is not supported in the library itslef

**Comment by mnob2019** [comment]
@Ilaiwi ah, okay, thank you for the reply:)
