### ISSUE TITLE
How can I repaint some items when the today line refreshes?

### ISSUE THREAD

**Issue by vickyvxr** [namespace-ee/react-calendar-timeline#672]
**Is your feature request related to a problem? Please describe.**
I need to paint the item different when the today line has passed over it:
![image](https://user-images.githubusercontent.com/33089634/67660738-c68f4c00-f95f-11e9-89b9-8625b6b43442.png)

When I render the component the first time, it is rendered ok,  but when the time passes the items are not re-rendered so the items become like this:
![image](https://user-images.githubusercontent.com/33089634/67660968-487f7500-f960-11e9-91e1-02783d45e7e6.png)

**Describe alternatives you've considered**
I tried to execute a function inside the today marker interval render:

<TodayMarker interval={10000} >
          {({styles}) => {
updateItems()
            return (<div className='todayLine' style={{...styles}} >
              <div className='todayLine_top'>
              </div>
            </div>
            );
          }
          }
        </TodayMarker>

But the component enters in an infinite loop: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate.....

How can I implement this issue?

Thank you very much in advance

**Comment by Ilaiwi** [comment]
the issue is that items are a pure component and the today line data doesn't affect the items. I would suggest passing a new ref for items. 
```
this.setState((state)=>({items: Object.assign({},state.items)}))
```
this should trigger a rerender of the items

**Comment by vickyvxr** [comment]
Using a setInterval of the same number of milliseconds than the today line ?

**Comment by Ilaiwi** [comment]
@vickyvxr not sure what do you mean

**Comment by vickyvxr** [comment]
Nothing, I have solved by myself, thanks :)
