### ISSUE TITLE
Draw vertical lines in some intervals

### ISSUE THREAD

**Issue by vickyvxr** [namespace-ee/react-calendar-timeline#675]
**Is your feature request related to a problem? Please describe.**
Is there any way to draw vertical lines in some specific intervals?
The Custom date headers are great, I have a zoom option and I can draw the headers depending on my needs thanks to this feature.
But I cannot find the way to draw vertical lines in the new positions that I need:
![image](https://user-images.githubusercontent.com/33089634/67847012-6be22580-fb02-11e9-83e5-66398144113e.png)

**Describe the solution you'd like**
I propose two solutions:
- Something similar to the DateHeaders but related to verticalLines,  with similar props, unit and interval render. 
- An verticalLineInterval prop that receives the minutes interval to draw a vertical line: 15,30,60,etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by Ilaiwi** [comment]
@vickyvxr something like in the codesandbox here?
https://codesandbox.io/s/timeline-demo-helpers-doc-example-o24h6
if yes then this should release with the row renderer feature which will soon be in beta

**Comment by Ilaiwi** [comment]
I will close this for now. If my previous answer didn't help please let me know
