### ISSUE TITLE
header doesn't horizontal scroll

### ISSUE THREAD

**Issue by aufgussmeister** [namespace-ee/react-calendar-timeline#679]
i have a problem with horizontal scrolling of header.
the body scroll well but the header is always fixed. 
i don't see css overrides, maybe someone can suggest to me what to pay attention in the scrolling chain of the header or the right class configuration

this is the component:
https://gist.github.com/aufgussmeister/e8268134468a0e01b7d99196ace936df

the packages
https://gist.github.com/aufgussmeister/fa5ecfd2ee86261a4274e48bbc925a77

thanks in advance 

<img width="673" alt="Schermata 2019-11-07 alle 22 18 11" src="https://user-images.githubusercontent.com/42536805/68428479-9429ee00-01ac-11ea-9585-61423f7bb57b.png">

**Comment by jabidof** [comment]
Same issue.
Downgraded to previous version.

**Comment by Ilaiwi** [comment]
this on a touchpad right? I think i know the issue I will release a patch tomorrow

**Comment by aufgussmeister** [comment]
> this on a touchpad right? I think i know the issue I will release a patch tomorrow

Yep with touchpad 0.26.5 ( @jabidof suggestion) works good, 0.26.6 doesn’t work with touchpad but only with mouse click. 

Thanks for your answer!

**Comment by jabidof** [comment]
Correct, with touchpad doesn’t work.
Thanks @Ilaiwi

**Comment by Ilaiwi** [comment]
released in 0.26.7 https://github.com/namespace-ee/react-calendar-timeline/releases/tag/0.26.7
