### ISSUE TITLE
Stackable items inside an item.

### ISSUE THREAD

**Issue by HichamELBSI** [namespace-ee/react-calendar-timeline#681]
Hello everyone,

First of all, thanks for this awesome repo. I have some difficulties to handle my case with react-calentar-timeline. Well, let me explain my use case. I have to display an item which have multiple items inside (something like a background item of a group of items). The group of items inside of the background item should be stacked like the picture below. 

![Capture d’écran 2019-11-12 à 16 07 33](https://user-images.githubusercontent.com/7756284/68684233-6f48c880-0568-11ea-9552-7fda47540277.png)

I tried to set the startTime/endTime of the backgroundItem with a native date to exclude it from the stackItems props effect (this allow to put it in the background). And then, i set a boolean to true in my item data if it is a background item to handle the two styles cases (zIndex, backgroundColor, etc). 

The problem is that i have a lot of sides effect like when I trigger a drag and drop or a resize event, the background item become stackable 😆.

<img width="948" alt="Capture d’écran 2019-11-12 à 16 30 31" src="https://user-images.githubusercontent.com/7756284/68685444-71138b80-056a-11ea-982f-84800fcafed9.png">

P.S. I need this background item to be a real item (Clickable, draggable, resizable) not an unavailable layer like a saw in some examples. 

Do you guys now how can I handle this case please ? Is it the right way to do this ?

**Comment by HichamELBSI** [comment]
Thanks for your reactivity ! 🤣

**Comment by joaocarlospf** [comment]
@HichamELBSI how is it possible to work with a 'background item'? I'm trying to implement one without any need to be clickable, draggable, etc, but I can't set if an individual item can be 'stackable' or not. So either I have something like your second print or all items at the same height, overlapping each other.
