### ISSUE TITLE
Allow custom className for root element

### ISSUE THREAD

**Issue by rmccue** [namespace-ee/react-calendar-timeline#682]
**Is your feature request related to a problem? Please describe.**

The root element has the `react-calendar-timeline` class name, which can't be customised. (There's also the `rct-outer` class name underneath it as well.)

**Describe the solution you'd like**

I'd like to be able to pass `className` or `additionalClassName` to the top-level `Timeline`.

**Describe alternatives you've considered**

It could be possible to override the class name and change it entirely, rather than just adding a class. I have no particular preference on this.

**Comment by Ilaiwi** [comment]
@rmccue thank you. This will be released later today.

**Comment by Ilaiwi** [comment]
released in 0.28.0
