### ISSUE TITLE
rct-vl-first isn't showing on .rct-dateHeader

### ISSUE THREAD

**Issue by loaibassam** [namespace-ee/react-calendar-timeline#684]
Any pointers on why .rct-dateHeader does not have .rct-day-0 or .rct-vl-first so i'm unable to style them.

<img width="911" alt="Screenshot 2019-11-13 at 15 13 59" src="https://user-images.githubusercontent.com/4785390/68777160-260c7d80-0629-11ea-9ecd-67b63cbd2645.png">

**Comment by Ilaiwi** [comment]
@loaibassam these were removed when Timeline Headers where introduced

**Comment by loaibassam** [comment]
Were they replaced with anything else?

**Comment by Ilaiwi** [comment]
`DateHeader` should do the trick but depends on what you are trying to do

**Comment by loaibassam** [comment]
What I'm trying to do is:
1) weekdays have a grey background colour, which I want to also show on the day in the header.
2) The border that separate months is darker, i want to also extend that to the day in the header.

<img width="748" alt="Screenshot 2019-11-13 at 16 18 43" src="https://user-images.githubusercontent.com/4785390/68782427-50facf80-0631-11ea-89ac-557fc0f083de.png">

**Comment by Ilaiwi** [comment]
you can definitely do that with `DateHeader` using [`intervalRenderer`](https://github.com/namespace-ee/react-calendar-timeline#intervalrenderer) where you can use `interval` to check the dates and accordingly apply some custom styles

**Comment by loaibassam** [comment]
Thanks a ton! :)
