### ISSUE TITLE
Custom Header disable zoom [Question]

### ISSUE THREAD

**Issue by Buba21** [namespace-ee/react-calendar-timeline#686]
HI im fairly new to react development and in my project i need to disable the zoom when we click on the header, i have been going crazy trying to figure this out but to no avail. The documentation on the Custom header is s bit confusing to me and so im stuck on this part. 
If someone could give me some pointers on how to do it i would be immensely appreciated.

Other than that amazing Api and continue with the great work.

Cumps
Diogo Moreira

**Comment by eardhquak** [comment]
Hi, i face the same issue. Were you able to disable the click zoom?

**Comment by luuhoangbac** [comment]
I'm not sure if they have a property or JS solution to solve this problem. 
But you can simply add this in order to disable the click to zoom feature:

```
.rct-dateHeader {
  pointer-events: none;
}
```
