### ISSUE TITLE
onTimeChange and CustomHeader

### ISSUE THREAD

**Issue by kevinhury** [namespace-ee/react-calendar-timeline#687]
Hi,

First of all thank you for the great library!

I'm trying to implement a timeline which can be controlled from the parent component (like a button which scrolls to "Today"), and also controlled by dragging.

From the docs:
If `visibleTimeStart` and `visibleTimeEnd` are passed in, then `onTimeChange` callback must be passed in too. In this instance, the displayed time can be validated by using `onTimeChange` and `setState` in the parent container.

My onTimeChange callback looks like this:
```javascript
handleTimeChange = (visibleTimeStart, visibleTimeEnd, updateCallback) => {
	console.log('qwert');

	this.setState({
		visibleTimeStart,
		visibleTimeEnd,
	});
}
```
but since I'm setting the state and re-renders the whole component, my custom header also re-renders and cause performance issue while scrolling:
```javascript
renderHeaders = () => {
	const intervalRenderer = ({ getIntervalProps, intervalContext }) => {
		const { startTime } = intervalContext.interval;
		const currentDay = startTime.toDate().getDay();
		const weekendClassname = currentDay === 0
			? 'custom-header-weekend-start'
			: currentDay === 6 ? 'custom-header-weekend-end' : '';

		const todayClassname = startTime.isSame(new Date(), "day")
			? 'today'
			: '';

		return <div
			{...getIntervalProps()}
			className={`custom-header-interval ${weekendClassname} ${todayClassname}`}
			onClick={null}
		>
			{intervalContext.intervalText}
		</div>
	};

	return <TimelineHeaders>
		<DateHeader
			height={40}
			intervalRenderer={intervalRenderer}
		/>
	</TimelineHeaders>;
};
```

**Comment by Ilaiwi** [comment]
take a look at these two examples
https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples#controlled-scroll
https://github.com/namespace-ee/react-calendar-timeline/tree/master/examples#programmatically-scrolling
they have what you need

**Comment by kevinhury** [comment]
@Ilaiwi Thanks for the reply. I have updated the first comment.
Btw the link is broken for the programmatically-scrolling exmaple
