### ISSUE TITLE
Manual zoom control

### ISSUE THREAD

**Issue by mdrulis-neurosys** [namespace-ee/react-calendar-timeline#69]
Is there a way to disable mouse-scroll-zooming and control it manually? I was thinking about setting defaultTimeStart and End accordingly, but had no luck with disabling scroll zoom.

**Comment by mdrulis-neurosys** [comment]
nevermind, after further reading it i got it to do exactly just that.

**Comment by Shadowman4205** [comment]
How did you succeed with manual zoom?

**Comment by mdrulis-neurosys** [comment]
I keep current visibleTimeStart and visibleTimeEnd in state and keep track of it manually, also with custom logic in onTimeChange event.

**Comment by Shadowman4205** [comment]
I think did the same, i have button zoom in with         
`<a href="#" onClick={this.handleClickZoomIn}><i className="fa fa-search-plus fa-2x" aria-hidden="true"></i></a>`
and zoom out
`<a href="#" onClick={this.handleClickZoomOut}><i className="fa fa-search-minus fa-2x" aria-hidden="true"></i></a>`
 
But i have 2 property of states for controling zoom (zoomStart ->for visibleTimeStart, zoomEnd -> for visibleTimeEnd) 

Are you using buttons like this? I want implement a slider for zoom, any suggestion?

**Comment by theopolisme** [comment]
FYI for those stumbling upon this in the future, you do not necessarily need to write any custom logic.

You can instead using the undocumented `timeline.zoomIn()` and `timeline.zoomOut()` methods on the component (and/or build custom logic that incorporates `timeline.changeZoom()`).

For example, in your component:

```js
<Timeline
  ref={r => { this.timeline = r; }}
  ...
/>
```

later...

```js
this.timeline.zoomIn();
this.timeline.zoomOut();
this.timeline.changeZoom(CUSTOM_ZOOM_FACTOR); // 1 maintains current, <1 zooms in, >1 out
```

Here is the [relevant section of `Timeline.js`](https://github.com/namespace-ee/react-calendar-timeline/blob/d2e3454ab86dd2d3f7356db615d74d11ec562701/src/lib/Timeline.js#L472-L491).

Hope this helps!

**Comment by rkiyoto** [comment]
> FYI for those stumbling upon this in the future, you do not necessarily need to write any custom logic.
> 
> You can instead using the undocumented `timeline.zoomIn()` and `timeline.zoomOut()` methods on the component (and/or build custom logic that incorporates `timeline.changeZoom()`).
> 
> For example, in your component:
> 
> ```js
> <Timeline
>   ref={r => { this.timeline = r; }}
>   ...
> />
> ```
> 
> later...
> 
> ```js
> this.timeline.zoomIn();
> this.timeline.zoomOut();
> this.timeline.changeZoom(CUSTOM_ZOOM_FACTOR); // 1 maintains current, <1 zooms in, >1 out
> ```
> 
> Here is the [relevant section of `Timeline.js`](https://github.com/namespace-ee/react-calendar-timeline/blob/d2e3454ab86dd2d3f7356db615d74d11ec562701/src/lib/Timeline.js#L472-L491).
> 
> Hope this helps!

```
this.timeline.zoomIn();
this.timeline.zoomOut(); 
```
Didin't work for me, it says it is not a function, but `this.timeline.changeZoom(CUSTOM_ZOOM_FACTOR);` works great, thanks!

**Comment by x4080** [comment]
Hi, I think the correct zoom is changeZoom(0.75) and changeZoom(1.25) like in the documentation and not between -1 and +1

**Comment by benjamin-sommer** [comment]
`this.timeline` is undefined

**Comment by 646826** [comment]
Who can give a full example?
I have a button on my site but I do not have an object to send event
