### ISSUE TITLE
Creating an item with a component called onDouble click.

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#692]
Hi, @Ilaiwi   I have a problem with rendering items. I have already tried everything spread operator and push function, and still do not get what the problem....Here is my codesandbox. If you have a moment could have a short look may be there is something behind the scene I didn't take into account...
https://codesandbox.io/s/silly-gagarin-3nsnw

Thank you!

**Comment by mnob2019** [comment]
@Ilaiwi sorry for the ping:)

**Comment by Ilaiwi** [comment]
not sure I understand the question

**Comment by mnob2019** [comment]
> not sure I understand the question

@Ilaiwi  After I push the Submit button on the separate component I wanted the items to be created, but it doesnt happen, I can see on the console that the state is updated and the items are not empty , but they do not appear on the timeline)

**Comment by mnob2019** [comment]
@Ilaiwi  Hi, I found the problem)  Now it works) The problem that in the documentation the item  is described as following:
{
  id: 1,
  group: 1,
  title: 'Random title',
  start_time: 1457902922261,
  end_time: 1457902922261 + 86400000,
  canMove: true,
  canResize: false,
  canChangeGroup: false,
  itemProps: {
    // these optional attributes are passed to the root <div /> of each item as <div {...itemProps} />
    'data-custom-attribute': 'Random content',
    'aria-hidden': true,
    onDoubleClick: () => { console.log('You clicked double!') },
    className: 'weekend',
    style: {
      background: 'fuchsia'
    }
  }
}


but it should be like this:


{
  id: 1,
  group: 1,
  title: 'Random title',
  start: 1457902922261,
  end 1457902922261 + 86400000,
  canMove: true,
  canResize: false,
  canChangeGroup: false,
  itemProps: {
    // these optional attributes are passed to the root <div /> of each item as <div {...itemProps} />
    'data-custom-attribute': 'Random content',
    'aria-hidden': true,
    onDoubleClick: () => { console.log('You clicked double!') },
    className: 'weekend',
    style: {
      background: 'fuchsia'
    }
  }
}


it should be: 
start 
end
 -------------------
 not
--------------------
start_time
end_time 



I thought it is important to say in case other people would struggle)

**Comment by Ilaiwi** [comment]
@mnob2019 this is because you are providing a keys object. By default the used keys are `start_time` and `end_time`
