### ISSUE TITLE
Drag / Move on first touch

### ISSUE THREAD

**Issue by kevinhury** [namespace-ee/react-calendar-timeline#694]
**Is your feature request related to a problem? Please describe.**
Currently in order to move/resize an rct-item you first need to click to select it, then you can move it / resize it

**Describe the solution you'd like**
Any way to resize and move the rct-item on first touch, without the need to select it first.

Thanks for the awesome component!

**Comment by diegocasmo** [comment]
@kevinhury did you manage to figure out how to do this?

**Comment by davidbejarcaceres** [comment]
> @kevinhury did you manage to figure out how to do this?

I had the same problem, just select all the items and that´s it, like:
`<TImeline selected={itemsToRender.map(item => item.id)} .../>`

Whit this solution you´ll be able to move/resize without first click them, nevertheless, you´ll probably need to change styles.

**Comment by diegocasmo** [comment]
I ended up using [this solution](https://github.com/namespace-ee/react-calendar-timeline/issues/290#issuecomment-391254489) as it's better aligned with what I wanted to do 🙂
