### ISSUE TITLE
Gradient for an item

### ISSUE THREAD

**Issue by mnob2019** [namespace-ee/react-calendar-timeline#698]
Hi, 

is it possible to add linear-gradient to the items? I cannot figure out how)

Thank you

**Comment by mnob2019** [comment]
@Ilaiwi  Hi, sorry) Is it possible to  make style {background: " linear gradient"}? only  work around with formula?

**Comment by dkarnutsch** [comment]
You can use your own ItemRenderer, add an additional `<div>` and apply custom styles to it. At least this is how we have done it.

**Comment by mnob2019** [comment]
Hi, thank you for your kind reply!

**Comment by Ilaiwi** [comment]
@mnob2019 I will assume that this is resolve. thanks @dkarnutsch
