### ISSUE TITLE
Override the top position of an item

### ISSUE THREAD

**Issue by VijayDinanath** [namespace-ee/react-calendar-timeline#699]
- I can render the items in the timeline, but when two items with same or one item less / more than other , then then items are rendered one below other.
- How can I render both the items on the same line with one below and other on the top of it, instead of below the first one in the second line.
- I tried to override the position: 'absolute' and top: 50 in getItemProps for all the items, but still the items are rendering one below the other.
- Other props in getItemProps (eg. backgroundColor) can be overriden, but top: 50 is not working.

**Comment by Ilaiwi** [comment]
@VijayDinanath by default you can't override top/left position via prop renderer.  What you can do but is not recommended is to override the result of `getItemProps ` which is basically a styles object.
I will close this since we don't support this and we won't be working on it
