### ISSUE TITLE
The library has not been transpiled from ES6 to ES5 for browser support

### ISSUE THREAD

**Issue by EugeneBugor** [namespace-ee/react-calendar-timeline#700]
**Describe the bug**
The main reason raising the issue is that common approach for such npm packages is being supportable by any browser. One of the way to reach it out is to transpile code written in ES6 to ES5 before moving it to npm repo. I know that this is a discussable question whether it should be consuming developer's or the library developer's responsibility of transpiling the library. But as easier to use your product for your customers as better for you, right?

**To Reproduce**

As the result, the outgoing error `SCRIPT1028: Expected identifier, string or number` appears using EDGE browser any version. ES6 rest operator has not been transpiled to ES5, and EDGE doesn't support rest operator unlike Chrome, Firefox etc.

Code reference: `/react-calendar-timeline/src/lib/utility/calendar.js:624`
```
const newItem = {
    ...item, //  <----  SCRIPT1028: Expected identifier, string or number
    [keys.itemTimeStartKey]: itemTimeStart,
    [keys.itemTimeEndKey]: itemTimeEnd,
    [keys.itemGroupKey]: isDragging
      ? _get(groups[newGroupOrder], keys.groupIdKey)
      : _get(item, keys.itemGroupKey)
  }
```

**Expected behavior**
The code of the library is transpiled to ES5 (on npm).

**Library Version**
any

**Desktop (please complete the following information):**
To see the example of caused issue:
* OS: Windows 10
* Browser: EDGE
* Version: any

**Comment by EugeneBugor** [comment]
As a workaround follow the solution - https://github.com/babel/babel-loader/issues/171
Summary:
1. Add 'exclude but one' rule to your webpack configuration file:
```
const rules = [
       ...,
       {
              test: /\.(js|jsx)$/,
              loader: 'babel-loader',
              exclude: /node_modules\/(?![react\-calendar\-timeline])/
       },
       ...
]
```
2. If you use `Babel 7`, you should switch `.babelrc` to `babel.config.js` (if you haven't done it before). https://babeljs.io/docs/en/configuration#babelconfigjs

**Comment by Ilaiwi** [comment]
@EugeneBugor you can use the transpiled version from `react-calendar-timeline/lib`
