### ISSUE TITLE
onCanvasDoubleClick and onCanvasContextMenu documented parameters are wrong

### ISSUE THREAD

**Issue by joncar** [namespace-ee/react-calendar-timeline#705]
**Describe the bug**
The documentation suggests onCanvasDoubleClick and onCanvasContextMenu have a group parameter as an object, which is different from all of the item events which use item ID. Fortunately the code does the right thing and it is actually the group ID.

**To Reproduce**

n/a

**Comment by Ilaiwi** [comment]
released in 0.28.0
