### ISSUE TITLE
[Question] Render complete timeline in full width

### ISSUE THREAD

**Issue by gvdlangenberg** [namespace-ee/react-calendar-timeline#708]
I'm currently synchronising multiple timeline instances with the `onTimeChange` property. This works fine on desktop, but when testing on a tablet device the performance is very weak. To work around this problem I figured I can render the timelines in full width, so that you can scroll through the timelines by horizontally scrolling the container. I've kind of got this working, but the timeline only renders partially, presumably because of the build-in performance featues built in the plugin (https://github.com/namespace-ee/react-calendar-timeline#behind-the-scenes). Is there a way to work around this and to let the timeline render in entirety?

**Comment by Ilaiwi** [comment]
@gvdlangenberg the library doesn't provide this functionality by default and we are not planing to support it soon. the `rowRendere` version currently in `beta` has huge performance optimizations that you could utilize. Try it out and lmk how things go. 
I am closing this for now and will open the issue if someone decided to pickup the feature request.
