### ISSUE TITLE
Programmatically Scrolling example 404

### ISSUE THREAD

**Issue by DmitryMishchenko** [namespace-ee/react-calendar-timeline#710]
![image](https://user-images.githubusercontent.com/16500028/72796583-3dc73a00-3c48-11ea-890a-88b02e7a2db8.png)

Programmatically Scrolling link is not working for this example.

**Comment by Ilaiwi** [comment]
@DmitryMishchenko thanks for noting this out. I fixed the link. Here is the correct one
https://codesandbox.io/s/timeline-demo-programmatic-scroll-3kq2503y8p
