### ISSUE TITLE
onTimeChange controlled scrolling has no effect

### ISSUE THREAD

**Issue by thelazydogsback** [namespace-ee/react-calendar-timeline#717]
I'm trying to use controlled scrolling, but it seems to have no effect.
In the code below, I can see the times changing, but the viewport remains static.

Maybe I'm misunderstand the operation.
thanks

```
      onTimeChange={(start, end, scrollFn) => {
        console.log(moment(start).toISOString(), moment(end).toISOString());
        scrollFn(start, end);
      }}
```

**Comment by thelazydogsback** [comment]
Ah, ok -- looks like the readme is out-of-date w/the implmentation.
So the 3rd arg (scroll fn) has been removed, and now we just deal with visStart/End times, correct?

**Comment by Ilaiwi** [comment]
@thelazydogsback `scrollFn` let's you change the next scroll values but not make the timeline scroll controlled.
to controll the scroll completely checkout `visiableTimeStart` and `visiableTimeEnd` with `onTimeChange` like in the following example
https://codesandbox.io/s/timeline-demo-controlled-visible-time-no-scroll-659jb

**Comment by owen-stellar** [comment]
So in that example, the timeline above isn't scrolling along with the data. Is that expected, because it seems wrong. I would expect the data to always scroll with the timeline information.

**Comment by Ilaiwi** [comment]
@owen-stellar we have a known bug in controlled timeline. We are working on it
