### ISSUE TITLE
Sometimes no events rendered until component is resized

### ISSUE THREAD

**Issue by thelazydogsback** [namespace-ee/react-calendar-timeline#718]
It seems like this is the case: If there is no current data when the component is first rendered and then item={events} is set subsequently, then the new items will not be rendered unless the user re-sizes the component.  Changing the visibleStart/End times will still not render the items.
Note that although the items are not rendered, you can see that "stacking space" has been reserved for the items in each group.

For example, if I'm correctly displaying events for "this week" and I change my data source to "next week" and there are zero events for that period, then I switch back to "this week" then the events that were rendered correctly before are not rendered now - I need to resize the window,

**Comment by MatthiasDh** [comment]
Same issue!

**Comment by Ilaiwi** [comment]
@thelazydogsback @MatthiasDh  could you try the beta version please and check if this happens there as well?
also a code sandbox example would be appriciated

**Comment by MatthiasDh** [comment]
@thelazydogsback found a fix! Don't render your calendar with an empty array if using async. Instead do a check to make sure your calendar doesn't render before you have items.

![image](https://user-images.githubusercontent.com/17167405/74425603-43353000-4e54-11ea-9c91-294f4d265de0.png)

**Comment by thelazydogsback** [comment]
@Ilaiwi  Can I install the beta bits or do I need to build from source?
@MatthiasDh I'll give it a try, but (a) I don't necessarily want the whole control to disappear on the user, and (b) when I try the conditional rendering I often have ref's, etc., break.

**Comment by thelazydogsback** [comment]
@Ilaiwi -- re: the beta, it looks like the last mods of src in this repo were 3 months ago -- is there another location for recent changes? thanks!

**Comment by Ilaiwi** [comment]
@thelazydogsback not `@next` try `@beta` to try out `0.27.3-beta
beta`
these is a codesanbox example with the beta that you could start from
https://codesandbox.io/s/timeline-demo-sticky-header-ylwn7

**Comment by thelazydogsback** [comment]
Thanks, @Ilaiwi  -- looks like the 0.27.3-beta solves this particular issue.

**Comment by x1mrdonut1x** [comment]
@Ilaiwi when can we expect the beta version to be released on master?

**Comment by Ilaiwi** [comment]
@x1mrdonut1x there is no official release data yet

**Comment by karanbht507** [comment]
0.27.3-beta version worked for me. Try this out

**Comment by Jetsxd16** [comment]
I have the same problem, try the beta version, but it didn't work, with the beta the calendar didn't show up. Someone had the same problem?

This is with the beta version :

![Untitled](https://user-images.githubusercontent.com/68814606/125417826-fef38d11-b4da-40d6-829e-30d3f7cc20e8.png)


And with the version 0.27.0:

![Untitle2d](https://user-images.githubusercontent.com/68814606/125418296-a2f584a8-3e91-43ad-8a94-862eec3feee2.png)
