### ISSUE TITLE
Any Idea how to change the military time to 12 hour time

### ISSUE THREAD

**Issue by latifs** [namespace-ee/react-calendar-timeline#719]
Hey guys
I'm sure it's available as an option somewhere.
Thank you!

**Comment by Ilaiwi** [comment]
@latifs via `labelFormat` in https://github.com/namespace-ee/react-calendar-timeline#dateheader
https://codesandbox.io/s/timeline-demo-sticky-header-xhsp9

**Comment by latifs** [comment]
shukraan @Ilaiwi
