### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by Shadowman4205** [namespace-ee/react-calendar-timeline#72]
Hello, i am using react starter kit, i tried to install your package like others package. But when i try run it i get his error

`....\node_modules\react-calendar-timeline\modules\lib\Timeline.css:1
(function (exports, require, module, __filename, __dirname) { .react-calendar-timeline  {
                                                              ^
SyntaxError: Unexpected token .`

**Comment by samford100** [comment]
I had the same problem and I was able to solve it by installing style-loader and css-loader and modifying my webpack.config.js file. 

`npm install css-loader --save`
`npm install style-loader --save`

and adding 

```
 { 
        test: /\.css$/, 
        loader: "style-loader!css-loader" 
 }, 
```
and 
```
resolve: {
        extensions: ['', '.js', '.jsx', '.css'],
        modulesDirectories: [
          'node_modules'
        ]        
    },
```

to webpack config like this

```
module.exports = {
  context: path.join(__dirname, "src"),
  devtool: debug ? "inline-sourcemap" : null,
  entry: ["./js/client.js",'babel-polyfill'],
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-class-properties', 'transform-decorators-legacy'],
        }
      },
      { 
        test: /\.css$/, 
        loader: "style-loader!css-loader" 
      }, 
    ]
  },
  output: {
    path: __dirname + "/build/",
    filename: "client.min.js"
  },
  resolve: {
        extensions: ['', '.js', '.jsx', '.css'],
        modulesDirectories: [
          'node_modules'
        ]        
    },
  plugins: debug ? [] : [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
  ],
};
```

Hopefully this helps!

**Comment by Shadowman4205** [comment]
I am using isomorpic-style-loader,i need use this too?

**Comment by mavo11** [comment]
Didn't work for me. Exactly the same error.

I am using a fresh cloned reactGo build.  https://github.com/reactGo/reactGo

Any other ideas to fix this problem?

**Comment by Swarna-Jain** [comment]
I am getting same error.. tried for this solution but not working for me... is there any substitute for this?

**Comment by signalwerk** [comment]
@Swarna-Jain are you having a webpack where you can import your css in JavaScript:

```js
import yourcssfile.css;
```

if you can't do that in your current webpack then you won't have any luck with this module. because we expect you to have a css loader in place

because people have different need we might externalise the .css (without import) at one point but right now it's done with an import statement and your webpack has to handle it.

**Comment by signalwerk** [comment]
I'm going to close that issue since it's not really an issue but right now a design decission. feel free to reopen if you need further assistance.
