### ISSUE TITLE
Can you add an onclick event or link to a group item on the left?

### ISSUE THREAD

**Issue by andrewjmac** [namespace-ee/react-calendar-timeline#721]
**Is your feature request related to a problem? Please describe.**
i'd like to be able to choose an item from the calendar and go to a different page for further information

**Describe the solution you'd like**
I'm not sure if this is currently possible, I haven't been able to read anything.

**Additional context**
If it is possible any guidance would be greatly appreciated!

**Comment by danielcruser** [comment]
Not sure if I'm the best person to answer this, but the docs on [groupRenderer](https://github.com/namespace-ee/react-calendar-timeline#grouprenderer) should point you in the right direction.

**Comment by andrewjmac** [comment]
Hi @danielcruser, thanks for you comment, that's exactly what I did in the end haha
