### ISSUE TITLE
Publish newest version to npm

### ISSUE THREAD

**Issue by FridgeWalaby** [namespace-ee/react-calendar-timeline#725]
A few bugs were fixed since November and merged to master but the package on npm is still old.

Could you publish the newest master to npm?

**Comment by FridgeWalaby** [comment]
@Ilaiwi

**Comment by latifs** [comment]
👍 Would like that too!

**Comment by FridgeWalaby** [comment]
Bump
@Ilaiwi  @rmccue  @danielcruser @tyson-kubota @xat @joncar

**Comment by diegocasmo** [comment]
👍 to this. I'm willing to offer my help if needed as well 🙂

**Comment by FridgeWalaby** [comment]
Newest version was pushed to npm. Thanks a lot!

**Comment by genlee025** [comment]
I have done an npm update but the package has the same bug? Is there another command I should be doing? @FridgeWalaby @Ilaiwi
