### ISSUE TITLE
Question: Is it possible to add custom className to the cell in only one row?

### ISSUE THREAD

**Issue by SergeyLys** [namespace-ee/react-calendar-timeline#731]
Is there a way to add group id as third parameter into verticalLineClassNamesForTime? I need to add custom class to only cells in the one row like unavailable dates for item, is it possible?

**Comment by yl-flyer** [comment]
@SergeyLys why you close it?

**Comment by SergeyLys** [comment]
@yl-flyer i've looked into the code and DOM and figured out that is not possible.

**Comment by yl-flyer** [comment]
ah ok
