### ISSUE TITLE
Disable TimelineHeader click

### ISSUE THREAD

**Issue by benjamin-sommer** [namespace-ee/react-calendar-timeline#734]
I have read the docs but I can't find any mention of how to disable zooming in on a subsection of the timeline when you click on a TimelineHeader.

Even though I have set the `minZoom` to a week, you can click each day's heading and it will zoom in even further.

How can I prevent this? Is this a bug?

**Comment by trevdor** [comment]
@benjamin-sommer For my use, I used a `<CustomHeader/>` and simply gave it no click handlers. Here's a demo: 

https://codesandbox.io/s/remove-zoom-on-header-click-react-calendar-timeline-4y64p

**Comment by benjamin-sommer** [comment]
@trevdor Thanks for your reply!

That demo works exactly how I wanted. Much appreciated!

**Comment by jayshepherd** [comment]
Anyone know of a way to suppress the click based on a condition? For example, if they ctrl/cmd click the header, I want to do something different and not zoom, otherwise zoom as normal.
