### ISSUE TITLE
How can I change the background color of cell?

### ISSUE THREAD

**Issue by gyarasu** [namespace-ee/react-calendar-timeline#74]
Hello.
I try to use your great component.

I have our calendar data which include milestones (e.g. our regular release days).
I want to change the background color of cells based on our calendar data.
It seems that weekend cells color are changed by default.

![figure](https://cloud.githubusercontent.com/assets/4948588/23347281/6463dd7c-fce4-11e6-989a-16eaf91a8fbb.png)

Is it possible?

Thanks!

**Comment by signalwerk** [comment]
@gyarasu there is a feature called `ranges` developed by @meengit 
with it you can mark some ranges in the background of the timeline component. right now it works but it's not 100% ready for a pull request. but you can already use it. with ranges you can do something similar what you are asking for. Here you finde the repo: https://github.com/meengit/react-calendar-timeline/tree/feature/range#ranges  (branch: feature/range)

Here you see two ranges:
![ranges](https://cloud.githubusercontent.com/assets/992878/23355474/1faf8554-fcd6-11e6-8eee-d7bf871ea8d3.png)

**Comment by gyarasu** [comment]
Thanks for your response.

I successfully installed #ranges branch into my project
and I confirmed that I can add the property.

I have a question.
How should I set a color for ranges?

I added the ranges property like below.(other properties are omitted this time)
```
<Timeline 
    ranges={{
          id: 2,
          start_time: moment().add(-1, 'day'),
          end_time: moment().add(4, 'day'),
          className: 'weekend'
     }
/>
```

Next, I prepared css.
```
.weekend {
  background-color: #99cc00
}
```

Unfortunately, I can't see it seems to be something wrong.

**Comment by signalwerk** [comment]
Hmmm... the current branch has other property names. That will be fixed before the final pull request comes. Here my Ranges definition:

```JSX
<Timeline 
    ranges={[{
          id: 2,
          start: moment().add(-1, 'day').toDate(),
          end: moment().add(4, 'day').toDate(),
          className: 'weekend'
     }]}
/>
```

result:
![demo](https://cloud.githubusercontent.com/assets/992878/23485649/a0e25fc2-fedc-11e6-96b0-ab4b1e9f3f8b.png)

**Comment by fopsdev** [comment]
Just an additional question.
I have a use case where i need to grey out the background as ranges are doing it.
But the ranges are per employee (Valid Worktime is defined differently for every employee)
Is it possible?
Thanks for any enlightment

**Comment by signalwerk** [comment]
no unfortunately not with the current implementation of ranges. hmm... maybe you should implement a horizontal-line-renderer like the [itemRenderer](https://github.com/namespace-ee/react-calendar-timeline#itemrenderer)?

**Comment by fopsdev** [comment]
ok 
thanks for pointing me to the right direction. do you know a sample of a itemRenderer?

**Comment by fopsdev** [comment]
i can't see how to achieve that.
i think it will fail because of the stacking
it looks like i really would need to access the background cell.
will dig further

**Comment by fopsdev** [comment]
Well, would be great if somebody would have another tip for me

**Comment by signalwerk** [comment]
@fopsdev sorry if my answer was not clear. the `itemRenderer` was just an example how to implement a custom renderer and then pass it to the component. But this work is not done for your case. 

You need to externalise the handling first and then implement your custom logic. probably something like: 

```
<Timeline
  groups={groups}
  items={items}
  horizontalLineRenderer={... here the reference to your function ...}
  ...
/>

```

Have a look here; [HorizontalLines.js](https://github.com/namespace-ee/react-calendar-timeline/blob/master/src/lib/lines/HorizontalLines.js)
Thats probably the part you need to work on.

**Comment by fopsdev** [comment]
@signalwerk 👍 
thanks, that got me started now :)

**Comment by mariusandra** [comment]
Hey! The *fresh out of the oven* `v0.15` contains support for [plugins](https://github.com/namespace-ee/react-calendar-timeline#children-plugins). 

@fopsdev you may look at the [plugin example](http://namespace.ee/react-calendar-timeline-docs/#/plugins) for a way to color the background in whatever way you wish. It's still a limited example (it colors the entire row, not specific days), but it's a starting point.

When @signalwerk and @meengit release the `ranges` plugin, it can serve as an additional piece of the puzzle :). Combining these two should give you what you need, if I understand correctly.

**Comment by gyarasu** [comment]
@signalwerk
Thanks for your responding.
I'm waiting for and looking forward to merge the feature!

**Comment by mcMickJuice** [comment]
Closing, created specific issue here: https://github.com/namespace-ee/react-calendar-timeline/issues/228

**Comment by tuancaraballo** [comment]
In case someone comes across the same question. I found a hacky way to accomplish the above and that also allows the onClick on the item to be disabled by setting the z index on the item to 40.

See a picture below. In this case I want to see when professors are working and who is assisting them. I want to be able to change the assistant shift, but not the professor's.

Here we have two items:
ProfessorItem:
- canMove = false
- className = 'disabledShift' 

AssistantItem: this is just a regular item.

in the css file : 
` .react-calendar-timeline .rct-items .rct-item.shiftBlock {
   background-color: #00D1BD;
   border: none ;
   z-index: 40;
 }`
![screen shot 2018-04-30 at 11 49 23 am](https://user-images.githubusercontent.com/16768578/39444474-d0790978-4c6c-11e8-8feb-ba6b47ff19b2.png)

Hope it helps.

**Comment by stahlmanDesign** [comment]
> It seems that weekend cells color are changed by default.
> 
> ![figure](https://cloud.githubusercontent.com/assets/4948588/23347281/6463dd7c-fce4-11e6-989a-16eaf91a8fbb.png)

The default css shows weekend colours as a light yellow`rgba(250, 246, 225, 0.5)`. You can override those or any other days with CSS:
```css
.rct-day-6,
.rct-day-7 {
  background: transparent!important;
}
```

**Comment by farrellp43** [comment]
> 

I have a question. How do you make two items overlap like this?

**Comment by farrellp43** [comment]
> In case someone comes across the same question. I found a hacky way to accomplish the above and that also allows the onClick on the item to be disabled by setting the **z index on the item to 40.**
> 
> See a picture below. In this case I want to see when professors are working and who is assisting them. I want to be able to change the assistant shift, but not the professor's.
> 
> Here we have two items: ProfessorItem:
> 
> * canMove = false
> * className = 'disabledShift'
> 
> AssistantItem: this is just a regular item.
> 
> in the css file : ` .react-calendar-timeline .rct-items .rct-item.shiftBlock { background-color: #00D1BD !important; border: none ; z-index: 40; }` ![screen shot 2018-04-30 at 11 49 23 am](https://user-images.githubusercontent.com/16768578/39444474-d0790978-4c6c-11e8-8feb-ba6b47ff19b2.png)
> 
> Hope it helps.

I have a question. How do you make two items overlap like that?
