### ISSUE TITLE
Controlled scroll through months

### ISSUE THREAD

**Issue by Brighter209** [namespace-ee/react-calendar-timeline#757]
**Describe the bug**

Hi thank you for the timeline component, I have an issue when I using the Controlled scroll with months, I started my timeline with the current month (June) it has 30 days, if i go to the previous month (May) which has 31 days, my timeline doesn't show May 1st. How can I update the timeline when I scroll through months ? Thank you

**To Reproduce**
https://codesandbox.io/s/bug-prev-next-month-1ohlg

**Screenshots**

![image](https://user-images.githubusercontent.com/7300656/84504741-bf356c80-acbc-11ea-9574-e0e317e73b43.png)

![image](https://user-images.githubusercontent.com/7300656/84504782-d1afa600-acbc-11ea-85d6-29f3b30870ba.png)

**Library Version**
"^0.27.0"

**Desktop (please complete the following information):**

* OS: win10
* Browser chrome
* Version 83.0.4103.97

**Comment by lestgabo** [comment]
its the code not the bug
```
  onPrevClick = () => {
    const zoom = this.state.visibleTimeEnd - this.state.visibleTimeStart;
    this.setState(state => ({
      visibleTimeStart: state.visibleTimeStart - zoom,
      visibleTimeEnd: state.visibleTimeEnd - zoom
    }));
  };

  onNextClick = () => {
    const zoom = this.state.visibleTimeEnd - this.state.visibleTimeStart;
    this.setState(state => ({
      visibleTimeStart: state.visibleTimeStart + zoom,
      visibleTimeEnd: state.visibleTimeEnd + zoom
    }));
  };
```
Needs to look at the month's number of days instead of showing number days from current month to all months.

Here's my hook code, to convert to component, just make setVisible functions into setState({})s
```
    const onPrevClick = () => {
        setVisibleTimeStart(moment(visibleTimeStart).add(-1, 'month').startOf('month').valueOf());
        setVisibleTimeEnd(moment(visibleTimeStart).add(-1, 'month').endOf('month').valueOf());
    };

    const onNextClick = () => {
        setVisibleTimeStart(moment(visibleTimeStart).add(1, 'month').startOf('month').valueOf());
        setVisibleTimeEnd(moment(visibleTimeStart).add(1, 'month').endOf('month').valueOf());
    };
```

**Comment by Brighter209** [comment]
Thank you for your help
