### ISSUE TITLE
Is it possible to link items?

### ISSUE THREAD

**Issue by gavmck** [namespace-ee/react-calendar-timeline#77]
I'd like to show several items in a group as linked. 

I have a repeating event that I'd like to be able to style to show those events are linked.

Awesome module, thanks!

**Comment by mariusandra** [comment]
Hi, when you say "linked", what do you mean? Something similar to this image?
![Linked items](https://www.mindtools.com/media/Diagrams/Gantt-Chart-Diagram-Figure-2small.jpg)

Unfortunately there's currently no way to do this, but it should be possible. What kind of use case do you have, and how do you expect the API for this to look like?

**Comment by signalwerk** [comment]
@gavmck I'm working on the component to have a multiple items dragging (will have next week time to finish it). this would help at least with the part of the interaction with a whole bunch of items. In theory you could also play with the [itemrenderer](https://github.com/namespace-ee/react-calendar-timeline#itemrenderer). This would not draw it as nice as in the screenshot of @mariusandra but you could at least visually (thickness, color, ...) group them. Would be cool if you can work on such a project with us.
