### ISSUE TITLE
Is it possible to remove weekend highlights?

### ISSUE THREAD

**Issue by DavidVeloso** [namespace-ee/react-calendar-timeline#772]
Hey There!

I'm trying to remove the weekend yellow highlights. But I couldn't find any issue/question related to it? Is it possible?

![Screen Shot 2020-08-19 at 18 36 44](https://user-images.githubusercontent.com/2433234/90692132-f428e700-e24a-11ea-82ec-6b5adf8d7e2b.png)

**Comment by diegocasmo** [comment]
@DavidVeloso

Yeah, should you be able to change their styling via the `.rct-day-6` `.rct-day-0` CSS classes.

**Comment by DavidVeloso** [comment]
Great! Thank you @diegocasmo.

I'm using material-ui and I just added on my component:

`const useStyles = makeStyles((theme) =>
    createStyles({     
        '@global .rct-day-0, .rct-day-6': {
            background: 'unset !important',
        },
    }),
);`
