### ISSUE TITLE
Timeline needs to be repainted before rendering new items 

### ISSUE THREAD

**Issue by genlee025** [namespace-ee/react-calendar-timeline#773]
Adding a new item to the state object in the timeline class does not automatically re-render the timeline and the user is forced to repaint the webpage for the new item to display. 

To demonstrate this issue I used the onCanvasClick method to add a new item to the state object at the time and group the user clicked. The item does not show up immediately I had to either refresh the page or repaint the page by adjusting the inspect window. 

I am not sure if this is the intended functionality of the calendar. If it isn't is there a more user friendly way to force the timeline to re-render without having to force the user to repaint the image. 

****To Reproduce****
I have forked a basic version of what I am describing. 
https://codesandbox.io/s/timeline-demo-sticky-header-forked-4r9vs?file=/CustomTimeline.jsx

**Expected behavior**
The new item will NOT appear immediately after the state has been updated it will only appear when the screen is repainted. 

**Library Version**
0.26.4

**Desktop (please complete the following information):**

* OS: iOS
* Browser chrome

**PLEASE READ **
I am not sure if this is the intended functionality of the calendar. If it isn't is there a more user friendly way to force the timeline to re-render without having to force the user to repaint the image.

**Comment by diegocasmo** [comment]
@genlee025

Use an immutable operation (like `concat`) when adding elements to the items array as follows:

``` javascript
onCanvasClick = (groupId, time, e) => {
  const { items } = this.state;    
  const startValue = time;
  const endValue = startValue + 3600000 * 3;
  const attrs = {
    id: `${time}`,
    group: groupId,
    title: faker.hacker.phrase(),
    start: startValue,
    end: endValue,
    itemProps: {
      "data-tip": faker.hacker.phrase()
    }
  };
  
  this.setState({ items: items.concat(attrs) });
  console.log(items.length);
};

```

**Comment by genlee025** [comment]
Thank you! that solved the problem :)
