### ISSUE TITLE
Error import react-calendar-timeline. Hope to get help from you.

### ISSUE THREAD

**Issue by LeThanhTung92** [namespace-ee/react-calendar-timeline#82]
I have been using react-calendar-timeline for my react webstite
I have installed the necessary libraries

npm install --save react-calendar-timeline
npm install --save react react-dom
npm install --save moment interact.js

Then import to website
import Timeline from 'react-calendar-timeline';
I compile the code with gulp but there was an error on this line
events.js:160
throw er; // Unhandled 'error' event
^
SyntaxError: Unexpected token

Why is this happening now? How to fix? Hope to get help from you.

**Comment by signalwerk** [comment]
@LeThanhTung92 could you provide me with code where I can see the problem?

**Comment by signalwerk** [comment]
I close this issue now. Feel free to reopen it if the problem still exists.
