### ISSUE TITLE
React 17 doesn't work with dependency create-react-context@0.3.0

### ISSUE THREAD

**Issue by maxcww** [namespace-ee/react-calendar-timeline#821]
Hi all, I am trying to include this beautiful library into my project, but I get the following error:

> npm ERR! Found: react@17.0.2
> npm ERR! node_modules/react
> npm ERR!   react@"^17.0.2" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from create-react-context@0.3.0
> npm ERR! node_modules/create-react-context
> npm ERR!   create-react-context@"*" from the root project
> npm ERR! 
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Does anyone have a solution for this, or is it safe to force the install?

**Comment by davidtung383** [comment]
It seems that the project would run React version 16 because of the limitation of "create-react-context"

**Comment by tikakwork** [comment]
Is it possible to remove "create-react-context" in this beautiful library for supporting react version 17 ?

**Comment by maxcww** [comment]
@tikakwork I have just installed the library with --legace-peer-deps. It works even thought create-react-context wants version 16. React itself also tells that 16 to 17 doesnt break if I remember correctly.

**Comment by davidtung383** [comment]
@maxcww does it means the react library of timeline used is 16 instead of 17?

**Comment by maxcww** [comment]
@davidtung383 If you look at the package.json file of this library, it says version "react": "^16.2.0", so I think it does use 16 yes.

**Comment by davidtung383** [comment]
@maxcww then this timeline library cannot enjoy the version upgrade of react now😥

**Comment by maxcww** [comment]
@davidtung383 That does not really matter as according to React https://reactjs.org/blog/2020/08/10/react-v17-rc.html there are no new features ;)

**Comment by davidtung383** [comment]
sounds good~
however, still hope timeline library can support react 17 or later versions since there maybe many updates in the future.

**Comment by maxcww** [comment]
@davidtung383 I dont know whether the creator of this library is still updating it, as the last release was in november 2019...

**Comment by davidtung383** [comment]
@maxcww Would you think re-open this issue can let creators know there is potential problem on timeline library on React version upgrade?
