### ISSUE TITLE
Touch scroll do not work

### ISSUE THREAD

**Issue by Shadowman4205** [namespace-ee/react-calendar-timeline#83]
When enable inspect in chrome in mobile scroll do not respond at all? any idea?

**Comment by eksavoy** [comment]
You can fix this issue with properties :
fixedHeader="fixed"

**Comment by Shadowman4205** [comment]
it is workingnow but it mess up the header.
Cause i have got  a navbar on top and in the middle i have got timeline.

**Comment by Shadowman4205** [comment]
@mariusandra Maybe any suggestion? how make touch scroll work without making headear fixed?

**Comment by mariusandra** [comment]
@Shadowman4205 Hey, a fix is on its way. Once PR #125 is merged you will no longer need `fixedHeader="fixed"` for the touch scroll. I'll update you when that happens!

**Comment by Shadowman4205** [comment]
thank you very much!

**Comment by Shadowman4205** [comment]
Sorry for inconvience is the PR #125 merged?

**Comment by signalwerk** [comment]
@Shadowman4205 sorry for the waiting. @mariusandra asked me to review the PR. I'm going to do that within the next 12h.

**Comment by Shadowman4205** [comment]
@signalwerk 
lol do not tell sorry. Thank you very much!

**Comment by mariusandra** [comment]
@Shadowman4205 Hey, I have just released `v0.15`. Please try it out and let us know if it fixed the problems you were having.

You should no longer need to specify `fixedHeader='fixed'` for the touch scroll to work. Also, the default header mode has changed to `"sticky"`. If that's too much, you may always reset it to `"none"`.

Closing this issue now :)
