### ISSUE TITLE
seconds view on the timeline is missing

### ISSUE THREAD

**Issue by horizon-plaza** [namespace-ee/react-calendar-timeline#835]
**Describe the bug**
Seconds view on the timeline is not showing even after setting the minZoom={60000}

**To Reproduce**

Click through to the second view on below sandbox link. Can only can view minute view and not beyond

https://codesandbox.io/s/timeline-demo-sticky-header-forked-w87q4

**Expected behavior**
Clicking through minutes view should show seconds view

**Comment by horizon-plaza** [comment]
PR for this issue https://github.com/namespace-ee/react-calendar-timeline/pull/836

**Comment by Ilaiwi** [comment]
@horizon-plaza this will be released soon.
