### ISSUE TITLE
DragSnap value is used when computing the item width, sometimes leading to wrong width calculations

### ISSUE THREAD

**Issue by gabriel-deliu** [namespace-ee/react-calendar-timeline#85]
It seems that the dragSnap value is used when computing the item width even if items can't be resized.
`let w = Math.max(itemEnd - itemStart, dragSnap) //react-calendar-timeline/src/lib/utils.js line 186`
This will cause items smaller than the dragSnap value (default 15 min) to be displayed incorrectly as dragSnap long.

Setting a low value to dragSnap is a workaround.

**Comment by signalwerk** [comment]
@gabriel-deliu do you have by any chance an example for me?

**Comment by gabriel-deliu** [comment]
Having dragSnap set to 15 minutes (default), create a 10 minute event. 
Expected: The event should be displayed as taking 10 minutes.
Actual: The event is displayed as taking 15 minutes.

Workaround: Set dragSnap to 10 minutes or lower.

**Comment by signalwerk** [comment]
Oh! I worked today on `calculateDimensions` (https://github.com/namespace-ee/react-calendar-timeline/pull/113). I completely get you now. I also made a [code example](https://www.webpackbin.com/bins/-KnBvRcj2FzvwL8QbT01) to illustrate it. The two Items in Group B are 10min and 15min. I can't work this week on the component anymore but I'll fix that soon. should be easy.

**Comment by mcMickJuice** [comment]
I believe this has been fixed as of 0.17.2 . If not, I'll reopen this.
