### ISSUE TITLE
release.js

### ISSUE THREAD

**Issue by signalwerk** [namespace-ee/react-calendar-timeline#91]
In `package.json` in `npm run release` there is the script `scripts/release.js` referenced. Did someone ever see that file? Or should I kill it in the scripts section of the package?

**Comment by madisvain** [comment]
@mariusandra would probably be the best person to know the answer to this question :)

**Comment by mariusandra** [comment]
Hi, I guess you can kill it. When starting the project I copied some lines from another repository. I think this was one of them.

**Comment by signalwerk** [comment]
@mariusandra @madisvain thx! I'm going to remove it for the next release.

**Comment by signalwerk** [comment]
This is corrected in Version `0.11.2`. now on master.
