### ISSUE TITLE
Fixed widh of timeline cell on any screen width

### ISSUE THREAD

**Issue by alexHlebnikov** [namespace-ee/react-calendar-timeline#942]
Hi! 

I was trying to figure out how it make width of timeline cell always same, f.e. 24px, without any resize because of screen width change? Example: timeline width is 100% - 360px (sidebar width), so if my screen width is 1200px, I should see 940/24 = approx. 39 days on my timeline. And if screen width is 1920px, I should see 1560/24 = approx. 65 days on my timeline.

 Is this behaviour possible to achieve with this library?

**Comment by alexHlebnikov** [comment]
Found a way to do this.

**Comment by roszczypalam** [comment]
Thx for the info. Can you share the answer ?

**Comment by sumansaurabh00001** [comment]
@alexHlebnikov, can you please share the information on how you did this?
